// ═══════════════════════════════════════════════════════
// Intelligence Is Inevitable (IiI)
//
// Saturation theorem, crystallization axioms,
// phase transition dynamics.
// ═══════════════════════════════════════════════════════

/// This is the loop that lifts the agent's guess to a certified result. ``PassIsIdentification``
/// turns the agent path into a system path (Thm 2). ``IdentityCollapse`` adds the
/// fixpoint where verify-side and identify-side are one. [IiI §1]
public protocol AgentPathCertified: PassIsIdentification, IdentityCollapse {}

/// This is knowledge that accumulates irreversibly. Cache permanence (I3, ``CachePermanent``)
/// applied to ``HasLibrary``: the library is append-only. [IiI §2]
public protocol KnowledgeAccumulates: CachePermanent, HasLibrary {}

/// The library saturates: after K tasks, every rule class is covered. Two
/// compressions pin it down:
///   1. `Library: Permanent`, append-only (from I3, ``Permanent``).
///   2. `Library == SaturatedLibrary`, converges to its fixed point.
/// Before, `Library` and `SaturatedLibrary` are free (``Pair``, two axes).
/// After, `Library == SaturatedLibrary` (``Null``, one axis). [IiI §3]
public protocol LibrarySaturates: StructuresFinite, CachePermanent,
    HasLibrary, HasSaturation
    where Library: Permanent, Library == SaturatedLibrary {}

/// The saturated library is generated by a *finite* basis. ``LibrarySaturates``
/// pins `Basis` here in a theorem: finiteness is the measured result, not an
/// assumption, so it is not pinned inline at ``HasBasis`` (``Law`` §2 placement:
/// proven, not defined). [IiI §3]
public protocol BasisIsFinite: LibrarySaturates, HasBasis
where Basis: IntegerValued {}

/// This is encoding selection at level 2, and it also saturates: coverage over the encoding
/// grammar, not uniqueness. ``LibrarySaturates`` extended along ``HasEncoding``,
/// with `Encoding: Permanent` pinning the level-2 axis: coverage accumulates,
/// mirroring the library. [IiI §4]
public protocol EncodingSelectionSaturates: LibrarySaturates,
    HasEncoding
    where Encoding: Permanent {}

// §5 A1: S₀ ⊇ S₁ ⊇ ..., solution set only shrinks. This IS the V=I
// inner-loop result CandidatesOnlyLeave (§5.22); IiI reuses it directly
// (Law §1: the claim lives once, in Identification.swift, no rename here).

/// A2: the system never retracts a result. ``CachePermanent`` (I3) plus
/// ``EqualityDecidable`` makes each individual membership result permanent.
/// [IiI §5 · V=I I3, A4]
public protocol ResultsIrreversible: CachePermanent, EqualityDecidable {}

/// A3: membership in Sₙ is decidable at each step. ``EqualityDecidable`` over
/// ``HasSolutions``, compressing `SolutionSet: Decidable`. [IiI §5 · V=I A4]
public protocol MembershipDecidable: EqualityDecidable,
    HasSolutions
    where SolutionSet: Decidable {}

/// A system that keeps narrowing its options until one is left, and then cannot be
/// budged. Concrete gates prove they are this kind of system by *conforming*: the
/// organization's owner gate (`OwnerGate`) and the grammar's linter (`SpellingGate`)
/// both compile, so the type checker shows each one settles to a single answer. A
/// system with no such gate (a language model, an ungated walk, with `|S| > 1`)
/// cannot conform, and the compiler names the coordinate it is missing.
///
/// Formally, it reaches a terminal state `∃n: |Sₙ| ≤ 1`, forced by four axioms. A1
/// ``CandidatesOnlyLeave`` (V=I §5.22), A2 ``ResultsIrreversible``, A3
/// ``MembershipDecidable``, and A4 the conclusion pinned (§T): `where SolutionSet:`
/// ``Unique``. The build is the certificate. [IiI §5]
public protocol SystemCrystallizes: CandidatesOnlyLeave, ResultsIrreversible,
    MembershipDecidable
    where SolutionSet: Unique {}

/// Lemma 1: the V=I inner pipeline is a crystallizing system. A1–A4 are met.
/// ``SystemCrystallizes`` realized on ``PassIsIdentification``. [IiI §5]
public protocol PipelineCrystallizes: SystemCrystallizes, PassIsIdentification {}

/// Lemma 2: library accumulation is a crystallizing system. A1–A4 are met.
/// ``SystemCrystallizes`` realized on ``LibrarySaturates``. [IiI §5]
public protocol LibraryCrystallizes: SystemCrystallizes, LibrarySaturates {}

/// This is saturation that follows coupon-collector dynamics: `E[τ_sat] = K·H_K`. Bounded
/// comparisons (``ComparisonsAreBounded``) on a saturating library
/// (``LibrarySaturates``) fix the expected time. [IiI §6]
public protocol SaturationDynamics: LibrarySaturates, ComparisonsAreBounded {}

/// The library is revealed, not constructed: `f*` pre-exists. A saturated library
/// (``LibrarySaturates``) with a unique survivor (``ExactlyOneSurvives``) makes
/// discovery a revelation. [IiI §7]
public protocol DiscoveryIsRevelation: LibrarySaturates, ExactlyOneSurvives {}


// ── §3 Intelligence (η): §T-generated ───────────────────────

/// Intelligence is a measured value: efficiency of identification,
/// `η = T_min / T_actual ∈ (0,1]`. A computed quantity over ``HasSigma``, so
/// ``Measurable`` (``Law`` §2). [IiI §3]
public protocol HasEfficiency: HasSigma {
    associatedtype Efficiency: Measurable
}

/// Intelligence is inevitable: under saturation, identification efficiency `η`
/// rises toward its maximum, and the efficiency gain *is* intelligence. A
/// saturating library (``LibrarySaturates``) drives ``HasEfficiency`` to its
/// fixpoint. [IiI §3, §8]
public protocol IntelligenceRises: LibrarySaturates, HasEfficiency {}
