import VerificationIsIdentification
import DocumentKit
import Organization

// GENERATED by `swift package generate org`: one page per roster halving. A door
// to a shelf wears `NameSpan` (its first and last person, phone-book order); a
// door to a person wears `NameOf`; every step page spells the word walked so far.
// All faces are witnesses, read off the types, never authored.


public enum RosterSpan0001To0002Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0068, Emp0064>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0068>.self; Emp0068.self } }
        ListItem { Link { NameOf<Emp0064>.self; Emp0064.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0002.self } }
        Break.self
    }
}

public enum RosterSpan0000To0002Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0064>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0061>.self; Emp0061.self } }
        ListItem { Link { NameSpan<Emp0068, Emp0064>.self; RosterSpan0001To0002.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0005.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0001To0002>.self
    }
}

public enum RosterSpan0004To0005Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0065, Emp0062>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0065>.self; Emp0065.self } }
        ListItem { Link { NameOf<Emp0062>.self; Emp0062.self } }
        ListItem { Link { UpWord.self; RosterSpan0003To0005.self } }
        Break.self
    }
}

public enum RosterSpan0003To0005Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0060, Emp0062>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0060>.self; Emp0060.self } }
        ListItem { Link { NameSpan<Emp0065, Emp0062>.self; RosterSpan0004To0005.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0005.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0004To0005>.self
    }
}

public enum RosterSpan0000To0005Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0062>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0061, Emp0064>.self; RosterSpan0000To0002.self } }
        ListItem { Link { NameSpan<Emp0060, Emp0062>.self; RosterSpan0003To0005.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0011.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0000To0002>.self
        TopicDoor<RosterSpan0003To0005>.self
    }
}

public enum RosterSpan0007To0008Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0067, Emp0066>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0067>.self; Emp0067.self } }
        ListItem { Link { NameOf<Emp0066>.self; Emp0066.self } }
        ListItem { Link { UpWord.self; RosterSpan0006To0008.self } }
        Break.self
    }
}

public enum RosterSpan0006To0008Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0071, Emp0066>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0071>.self; Emp0071.self } }
        ListItem { Link { NameSpan<Emp0067, Emp0066>.self; RosterSpan0007To0008.self } }
        ListItem { Link { UpWord.self; RosterSpan0006To0011.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0007To0008>.self
    }
}

public enum RosterSpan0010To0011Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0070, Emp0069>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0070>.self; Emp0070.self } }
        ListItem { Link { NameOf<Emp0069>.self; Emp0069.self } }
        ListItem { Link { UpWord.self; RosterSpan0009To0011.self } }
        Break.self
    }
}

public enum RosterSpan0009To0011Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0063, Emp0069>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0063>.self; Emp0063.self } }
        ListItem { Link { NameSpan<Emp0070, Emp0069>.self; RosterSpan0010To0011.self } }
        ListItem { Link { UpWord.self; RosterSpan0006To0011.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0010To0011>.self
    }
}

public enum RosterSpan0006To0011Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0071, Emp0069>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0071, Emp0066>.self; RosterSpan0006To0008.self } }
        ListItem { Link { NameSpan<Emp0063, Emp0069>.self; RosterSpan0009To0011.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0011.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0006To0008>.self
        TopicDoor<RosterSpan0009To0011>.self
    }
}

public enum RosterSpan0000To0011Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0069>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0061, Emp0062>.self; RosterSpan0000To0005.self } }
        ListItem { Link { NameSpan<Emp0071, Emp0069>.self; RosterSpan0006To0011.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0024.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0000To0005>.self
        TopicDoor<RosterSpan0006To0011>.self
    }
}

public enum RosterSpan0013To0014Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0145, Emp0008>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0145>.self; Emp0145.self } }
        ListItem { Link { NameOf<Emp0008>.self; Emp0008.self } }
        ListItem { Link { UpWord.self; RosterSpan0012To0014.self } }
        Break.self
    }
}

public enum RosterSpan0012To0014Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0001, Emp0008>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0001>.self; Emp0001.self } }
        ListItem { Link { NameSpan<Emp0145, Emp0008>.self; RosterSpan0013To0014.self } }
        ListItem { Link { UpWord.self; RosterSpan0012To0017.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0013To0014>.self
    }
}

public enum RosterSpan0016To0017Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0004, Emp0148>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0004>.self; Emp0004.self } }
        ListItem { Link { NameOf<Emp0148>.self; Emp0148.self } }
        ListItem { Link { UpWord.self; RosterSpan0015To0017.self } }
        Break.self
    }
}

public enum RosterSpan0015To0017Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0152, Emp0148>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0152>.self; Emp0152.self } }
        ListItem { Link { NameSpan<Emp0004, Emp0148>.self; RosterSpan0016To0017.self } }
        ListItem { Link { UpWord.self; RosterSpan0012To0017.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0016To0017>.self
    }
}

public enum RosterSpan0012To0017Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0001, Emp0148>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0001, Emp0008>.self; RosterSpan0012To0014.self } }
        ListItem { Link { NameSpan<Emp0152, Emp0148>.self; RosterSpan0015To0017.self } }
        ListItem { Link { UpWord.self; RosterSpan0012To0024.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0012To0014>.self
        TopicDoor<RosterSpan0015To0017>.self
    }
}

public enum RosterSpan0019To0020Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0144, Emp0005>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0144>.self; Emp0144.self } }
        ListItem { Link { NameOf<Emp0005>.self; Emp0005.self } }
        ListItem { Link { UpWord.self; RosterSpan0018To0020.self } }
        Break.self
    }
}

public enum RosterSpan0018To0020Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0000, Emp0005>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0000>.self; Emp0000.self } }
        ListItem { Link { NameSpan<Emp0144, Emp0005>.self; RosterSpan0019To0020.self } }
        ListItem { Link { UpWord.self; RosterSpan0018To0024.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0019To0020>.self
    }
}

public enum RosterSpan0021To0022Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0149, Emp0002>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0149>.self; Emp0149.self } }
        ListItem { Link { NameOf<Emp0002>.self; Emp0002.self } }
        ListItem { Link { UpWord.self; RosterSpan0021To0024.self } }
        Break.self
    }
}

public enum RosterSpan0023To0024Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0146, Emp0011>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0146>.self; Emp0146.self } }
        ListItem { Link { NameOf<Emp0011>.self; Emp0011.self } }
        ListItem { Link { UpWord.self; RosterSpan0021To0024.self } }
        Break.self
    }
}

public enum RosterSpan0021To0024Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0149, Emp0011>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0149, Emp0002>.self; RosterSpan0021To0022.self } }
        ListItem { Link { NameSpan<Emp0146, Emp0011>.self; RosterSpan0023To0024.self } }
        ListItem { Link { UpWord.self; RosterSpan0018To0024.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0021To0022>.self
        TopicDoor<RosterSpan0023To0024>.self
    }
}

public enum RosterSpan0018To0024Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0000, Emp0011>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0000, Emp0005>.self; RosterSpan0018To0020.self } }
        ListItem { Link { NameSpan<Emp0149, Emp0011>.self; RosterSpan0021To0024.self } }
        ListItem { Link { UpWord.self; RosterSpan0012To0024.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0018To0020>.self
        TopicDoor<RosterSpan0021To0024>.self
    }
}

public enum RosterSpan0012To0024Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0001, Emp0011>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0001, Emp0148>.self; RosterSpan0012To0017.self } }
        ListItem { Link { NameSpan<Emp0000, Emp0011>.self; RosterSpan0018To0024.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0024.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0012To0017>.self
        TopicDoor<RosterSpan0018To0024>.self
    }
}

public enum RosterSpan0000To0024Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0011>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0061, Emp0069>.self; RosterSpan0000To0011.self } }
        ListItem { Link { NameSpan<Emp0001, Emp0011>.self; RosterSpan0012To0024.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0000To0011>.self
        TopicDoor<RosterSpan0012To0024>.self
    }
}

public enum RosterSpan0026To0027Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0007, Emp0151>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0007>.self; Emp0007.self } }
        ListItem { Link { NameOf<Emp0151>.self; Emp0151.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0027.self } }
        Break.self
    }
}

public enum RosterSpan0025To0027Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0155, Emp0151>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0155>.self; Emp0155.self } }
        ListItem { Link { NameSpan<Emp0007, Emp0151>.self; RosterSpan0026To0027.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0030.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0026To0027>.self
    }
}

public enum RosterSpan0029To0030Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0150, Emp0003>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0150>.self; Emp0150.self } }
        ListItem { Link { NameOf<Emp0003>.self; Emp0003.self } }
        ListItem { Link { UpWord.self; RosterSpan0028To0030.self } }
        Break.self
    }
}

public enum RosterSpan0028To0030Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0006, Emp0003>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0006>.self; Emp0006.self } }
        ListItem { Link { NameSpan<Emp0150, Emp0003>.self; RosterSpan0029To0030.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0030.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0029To0030>.self
    }
}

public enum RosterSpan0025To0030Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0155, Emp0003>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0155, Emp0151>.self; RosterSpan0025To0027.self } }
        ListItem { Link { NameSpan<Emp0006, Emp0003>.self; RosterSpan0028To0030.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0037.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0025To0027>.self
        TopicDoor<RosterSpan0028To0030>.self
    }
}

public enum RosterSpan0032To0033Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0010, Emp0154>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0010>.self; Emp0010.self } }
        ListItem { Link { NameOf<Emp0154>.self; Emp0154.self } }
        ListItem { Link { UpWord.self; RosterSpan0031To0033.self } }
        Break.self
    }
}

public enum RosterSpan0031To0033Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0147, Emp0154>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0147>.self; Emp0147.self } }
        ListItem { Link { NameSpan<Emp0010, Emp0154>.self; RosterSpan0032To0033.self } }
        ListItem { Link { UpWord.self; RosterSpan0031To0037.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0032To0033>.self
    }
}

public enum RosterSpan0034To0035Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0009, Emp0153>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0009>.self; Emp0009.self } }
        ListItem { Link { NameOf<Emp0153>.self; Emp0153.self } }
        ListItem { Link { UpWord.self; RosterSpan0034To0037.self } }
        Break.self
    }
}

public enum RosterSpan0036To0037Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0085, Emp0092>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0085>.self; Emp0085.self } }
        ListItem { Link { NameOf<Emp0092>.self; Emp0092.self } }
        ListItem { Link { UpWord.self; RosterSpan0034To0037.self } }
        Break.self
    }
}

public enum RosterSpan0034To0037Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0009, Emp0092>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0009, Emp0153>.self; RosterSpan0034To0035.self } }
        ListItem { Link { NameSpan<Emp0085, Emp0092>.self; RosterSpan0036To0037.self } }
        ListItem { Link { UpWord.self; RosterSpan0031To0037.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0034To0035>.self
        TopicDoor<RosterSpan0036To0037>.self
    }
}

public enum RosterSpan0031To0037Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0147, Emp0092>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0147, Emp0154>.self; RosterSpan0031To0033.self } }
        ListItem { Link { NameSpan<Emp0009, Emp0092>.self; RosterSpan0034To0037.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0037.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0031To0033>.self
        TopicDoor<RosterSpan0034To0037>.self
    }
}

public enum RosterSpan0025To0037Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0155, Emp0092>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0155, Emp0003>.self; RosterSpan0025To0030.self } }
        ListItem { Link { NameSpan<Emp0147, Emp0092>.self; RosterSpan0031To0037.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0025To0030>.self
        TopicDoor<RosterSpan0031To0037>.self
    }
}

public enum RosterSpan0039To0040Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0084, Emp0089>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0084>.self; Emp0084.self } }
        ListItem { Link { NameOf<Emp0089>.self; Emp0089.self } }
        ListItem { Link { UpWord.self; RosterSpan0038To0040.self } }
        Break.self
    }
}

public enum RosterSpan0038To0040Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0088, Emp0089>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0088>.self; Emp0088.self } }
        ListItem { Link { NameSpan<Emp0084, Emp0089>.self; RosterSpan0039To0040.self } }
        ListItem { Link { UpWord.self; RosterSpan0038To0043.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0039To0040>.self
    }
}

public enum RosterSpan0042To0043Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0095, Emp0091>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0095>.self; Emp0095.self } }
        ListItem { Link { NameOf<Emp0091>.self; Emp0091.self } }
        ListItem { Link { UpWord.self; RosterSpan0041To0043.self } }
        Break.self
    }
}

public enum RosterSpan0041To0043Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0086, Emp0091>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0086>.self; Emp0086.self } }
        ListItem { Link { NameSpan<Emp0095, Emp0091>.self; RosterSpan0042To0043.self } }
        ListItem { Link { UpWord.self; RosterSpan0038To0043.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0042To0043>.self
    }
}

public enum RosterSpan0038To0043Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0088, Emp0091>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0088, Emp0089>.self; RosterSpan0038To0040.self } }
        ListItem { Link { NameSpan<Emp0086, Emp0091>.self; RosterSpan0041To0043.self } }
        ListItem { Link { UpWord.self; RosterSpan0038To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0038To0040>.self
        TopicDoor<RosterSpan0041To0043>.self
    }
}

public enum RosterSpan0045To0046Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0087, Emp0094>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0087>.self; Emp0087.self } }
        ListItem { Link { NameOf<Emp0094>.self; Emp0094.self } }
        ListItem { Link { UpWord.self; RosterSpan0044To0046.self } }
        Break.self
    }
}

public enum RosterSpan0044To0046Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0090, Emp0094>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0090>.self; Emp0090.self } }
        ListItem { Link { NameSpan<Emp0087, Emp0094>.self; RosterSpan0045To0046.self } }
        ListItem { Link { UpWord.self; RosterSpan0044To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0045To0046>.self
    }
}

public enum RosterSpan0047To0048Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0093, Emp0037>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0093>.self; Emp0093.self } }
        ListItem { Link { NameOf<Emp0037>.self; Emp0037.self } }
        ListItem { Link { UpWord.self; RosterSpan0047To0050.self } }
        Break.self
    }
}

public enum RosterSpan0049To0050Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0181, Emp0044>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0181>.self; Emp0181.self } }
        ListItem { Link { NameOf<Emp0044>.self; Emp0044.self } }
        ListItem { Link { UpWord.self; RosterSpan0047To0050.self } }
        Break.self
    }
}

public enum RosterSpan0047To0050Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0093, Emp0044>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0093, Emp0037>.self; RosterSpan0047To0048.self } }
        ListItem { Link { NameSpan<Emp0181, Emp0044>.self; RosterSpan0049To0050.self } }
        ListItem { Link { UpWord.self; RosterSpan0044To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0047To0048>.self
        TopicDoor<RosterSpan0049To0050>.self
    }
}

public enum RosterSpan0044To0050Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0090, Emp0044>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0090, Emp0094>.self; RosterSpan0044To0046.self } }
        ListItem { Link { NameSpan<Emp0093, Emp0044>.self; RosterSpan0047To0050.self } }
        ListItem { Link { UpWord.self; RosterSpan0038To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0044To0046>.self
        TopicDoor<RosterSpan0047To0050>.self
    }
}

public enum RosterSpan0038To0050Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0088, Emp0044>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0088, Emp0091>.self; RosterSpan0038To0043.self } }
        ListItem { Link { NameSpan<Emp0090, Emp0044>.self; RosterSpan0044To0050.self } }
        ListItem { Link { UpWord.self; RosterSpan0025To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0038To0043>.self
        TopicDoor<RosterSpan0044To0050>.self
    }
}

public enum RosterSpan0025To0050Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0155, Emp0044>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0155, Emp0092>.self; RosterSpan0025To0037.self } }
        ListItem { Link { NameSpan<Emp0088, Emp0044>.self; RosterSpan0038To0050.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0050.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0025To0037>.self
        TopicDoor<RosterSpan0038To0050>.self
    }
}

public enum RosterSpan0000To0050Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0044>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0061, Emp0011>.self; RosterSpan0000To0024.self } }
        ListItem { Link { NameSpan<Emp0155, Emp0044>.self; RosterSpan0025To0050.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0000To0024>.self
        TopicDoor<RosterSpan0025To0050>.self
    }
}

public enum RosterSpan0052To0053Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0040, Emp0184>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0040>.self; Emp0040.self } }
        ListItem { Link { NameOf<Emp0184>.self; Emp0184.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0053.self } }
        Break.self
    }
}

public enum RosterSpan0051To0053Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0188, Emp0184>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0188>.self; Emp0188.self } }
        ListItem { Link { NameSpan<Emp0040, Emp0184>.self; RosterSpan0052To0053.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0056.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0052To0053>.self
    }
}

public enum RosterSpan0055To0056Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0180, Emp0041>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0180>.self; Emp0180.self } }
        ListItem { Link { NameOf<Emp0041>.self; Emp0041.self } }
        ListItem { Link { UpWord.self; RosterSpan0054To0056.self } }
        Break.self
    }
}

public enum RosterSpan0054To0056Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0036, Emp0041>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0036>.self; Emp0036.self } }
        ListItem { Link { NameSpan<Emp0180, Emp0041>.self; RosterSpan0055To0056.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0056.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0055To0056>.self
    }
}

public enum RosterSpan0051To0056Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0188, Emp0041>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0188, Emp0184>.self; RosterSpan0051To0053.self } }
        ListItem { Link { NameSpan<Emp0036, Emp0041>.self; RosterSpan0054To0056.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0062.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0051To0053>.self
        TopicDoor<RosterSpan0054To0056>.self
    }
}

public enum RosterSpan0058To0059Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0038, Emp0182>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0038>.self; Emp0038.self } }
        ListItem { Link { NameOf<Emp0182>.self; Emp0182.self } }
        ListItem { Link { UpWord.self; RosterSpan0057To0059.self } }
        Break.self
    }
}

public enum RosterSpan0057To0059Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0185, Emp0182>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0185>.self; Emp0185.self } }
        ListItem { Link { NameSpan<Emp0038, Emp0182>.self; RosterSpan0058To0059.self } }
        ListItem { Link { UpWord.self; RosterSpan0057To0062.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0058To0059>.self
    }
}

public enum RosterSpan0061To0062Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0191, Emp0043>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0191>.self; Emp0191.self } }
        ListItem { Link { NameOf<Emp0043>.self; Emp0043.self } }
        ListItem { Link { UpWord.self; RosterSpan0060To0062.self } }
        Break.self
    }
}

public enum RosterSpan0060To0062Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0047, Emp0043>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0047>.self; Emp0047.self } }
        ListItem { Link { NameSpan<Emp0191, Emp0043>.self; RosterSpan0061To0062.self } }
        ListItem { Link { UpWord.self; RosterSpan0057To0062.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0061To0062>.self
    }
}

public enum RosterSpan0057To0062Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0185, Emp0043>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0185, Emp0182>.self; RosterSpan0057To0059.self } }
        ListItem { Link { NameSpan<Emp0047, Emp0043>.self; RosterSpan0060To0062.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0062.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0057To0059>.self
        TopicDoor<RosterSpan0060To0062>.self
    }
}

public enum RosterSpan0051To0062Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0188, Emp0043>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0188, Emp0041>.self; RosterSpan0051To0056.self } }
        ListItem { Link { NameSpan<Emp0185, Emp0043>.self; RosterSpan0057To0062.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0075.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0051To0056>.self
        TopicDoor<RosterSpan0057To0062>.self
    }
}

public enum RosterSpan0064To0065Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0042, Emp0186>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0042>.self; Emp0042.self } }
        ListItem { Link { NameOf<Emp0186>.self; Emp0186.self } }
        ListItem { Link { UpWord.self; RosterSpan0063To0065.self } }
        Break.self
    }
}

public enum RosterSpan0063To0065Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0187, Emp0186>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0187>.self; Emp0187.self } }
        ListItem { Link { NameSpan<Emp0042, Emp0186>.self; RosterSpan0064To0065.self } }
        ListItem { Link { UpWord.self; RosterSpan0063To0068.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0064To0065>.self
    }
}

public enum RosterSpan0067To0068Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0183, Emp0046>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0183>.self; Emp0183.self } }
        ListItem { Link { NameOf<Emp0046>.self; Emp0046.self } }
        ListItem { Link { UpWord.self; RosterSpan0066To0068.self } }
        Break.self
    }
}

public enum RosterSpan0066To0068Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0039, Emp0046>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0039>.self; Emp0039.self } }
        ListItem { Link { NameSpan<Emp0183, Emp0046>.self; RosterSpan0067To0068.self } }
        ListItem { Link { UpWord.self; RosterSpan0063To0068.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0067To0068>.self
    }
}

public enum RosterSpan0063To0068Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0187, Emp0046>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0187, Emp0186>.self; RosterSpan0063To0065.self } }
        ListItem { Link { NameSpan<Emp0039, Emp0046>.self; RosterSpan0066To0068.self } }
        ListItem { Link { UpWord.self; RosterSpan0063To0075.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0063To0065>.self
        TopicDoor<RosterSpan0066To0068>.self
    }
}

public enum RosterSpan0070To0071Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0045, Emp0189>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0045>.self; Emp0045.self } }
        ListItem { Link { NameOf<Emp0189>.self; Emp0189.self } }
        ListItem { Link { UpWord.self; RosterSpan0069To0071.self } }
        Break.self
    }
}

public enum RosterSpan0069To0071Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0190, Emp0189>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0190>.self; Emp0190.self } }
        ListItem { Link { NameSpan<Emp0045, Emp0189>.self; RosterSpan0070To0071.self } }
        ListItem { Link { UpWord.self; RosterSpan0069To0075.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0070To0071>.self
    }
}

public enum RosterSpan0072To0073Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Carol, Emp0049>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Carol>.self; Carol.self } }
        ListItem { Link { NameOf<Emp0049>.self; Emp0049.self } }
        ListItem { Link { UpWord.self; RosterSpan0072To0075.self } }
        Break.self
    }
}

public enum RosterSpan0074To0075Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0193, Emp0056>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0193>.self; Emp0193.self } }
        ListItem { Link { NameOf<Emp0056>.self; Emp0056.self } }
        ListItem { Link { UpWord.self; RosterSpan0072To0075.self } }
        Break.self
    }
}

public enum RosterSpan0072To0075Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Carol, Emp0056>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Carol, Emp0049>.self; RosterSpan0072To0073.self } }
        ListItem { Link { NameSpan<Emp0193, Emp0056>.self; RosterSpan0074To0075.self } }
        ListItem { Link { UpWord.self; RosterSpan0069To0075.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0072To0073>.self
        TopicDoor<RosterSpan0074To0075>.self
    }
}

public enum RosterSpan0069To0075Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0190, Emp0056>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0190, Emp0189>.self; RosterSpan0069To0071.self } }
        ListItem { Link { NameSpan<Carol, Emp0056>.self; RosterSpan0072To0075.self } }
        ListItem { Link { UpWord.self; RosterSpan0063To0075.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0069To0071>.self
        TopicDoor<RosterSpan0072To0075>.self
    }
}

public enum RosterSpan0063To0075Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0187, Emp0056>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0187, Emp0046>.self; RosterSpan0063To0068.self } }
        ListItem { Link { NameSpan<Emp0190, Emp0056>.self; RosterSpan0069To0075.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0075.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0063To0068>.self
        TopicDoor<RosterSpan0069To0075>.self
    }
}

public enum RosterSpan0051To0075Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0188, Emp0056>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0188, Emp0043>.self; RosterSpan0051To0062.self } }
        ListItem { Link { NameSpan<Emp0187, Emp0056>.self; RosterSpan0063To0075.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0051To0062>.self
        TopicDoor<RosterSpan0063To0075>.self
    }
}

public enum RosterSpan0077To0078Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0196, Emp0048>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0196>.self; Emp0196.self } }
        ListItem { Link { NameOf<Emp0048>.self; Emp0048.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0078.self } }
        Break.self
    }
}

public enum RosterSpan0076To0078Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0052, Emp0048>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0052>.self; Emp0052.self } }
        ListItem { Link { NameSpan<Emp0196, Emp0048>.self; RosterSpan0077To0078.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0081.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0077To0078>.self
    }
}

public enum RosterSpan0080To0081Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0053, Emp0197>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0053>.self; Emp0053.self } }
        ListItem { Link { NameOf<Emp0197>.self; Emp0197.self } }
        ListItem { Link { UpWord.self; RosterSpan0079To0081.self } }
        Break.self
    }
}

public enum RosterSpan0079To0081Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0192, Emp0197>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0192>.self; Emp0192.self } }
        ListItem { Link { NameSpan<Emp0053, Emp0197>.self; RosterSpan0080To0081.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0081.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0080To0081>.self
    }
}

public enum RosterSpan0076To0081Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0052, Emp0197>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0052, Emp0048>.self; RosterSpan0076To0078.self } }
        ListItem { Link { NameSpan<Emp0192, Emp0197>.self; RosterSpan0079To0081.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0088.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0076To0078>.self
        TopicDoor<RosterSpan0079To0081>.self
    }
}

public enum RosterSpan0083To0084Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0194, Emp0059>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0194>.self; Emp0194.self } }
        ListItem { Link { NameOf<Emp0059>.self; Emp0059.self } }
        ListItem { Link { UpWord.self; RosterSpan0082To0084.self } }
        Break.self
    }
}

public enum RosterSpan0082To0084Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0050, Emp0059>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0050>.self; Emp0050.self } }
        ListItem { Link { NameSpan<Emp0194, Emp0059>.self; RosterSpan0083To0084.self } }
        ListItem { Link { UpWord.self; RosterSpan0082To0088.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0083To0084>.self
    }
}

public enum RosterSpan0085To0086Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0055, Emp0199>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0055>.self; Emp0055.self } }
        ListItem { Link { NameOf<Emp0199>.self; Emp0199.self } }
        ListItem { Link { UpWord.self; RosterSpan0085To0088.self } }
        Break.self
    }
}

public enum RosterSpan0087To0088Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0054, Emp0198>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0054>.self; Emp0054.self } }
        ListItem { Link { NameOf<Emp0198>.self; Emp0198.self } }
        ListItem { Link { UpWord.self; RosterSpan0085To0088.self } }
        Break.self
    }
}

public enum RosterSpan0085To0088Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0055, Emp0198>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0055, Emp0199>.self; RosterSpan0085To0086.self } }
        ListItem { Link { NameSpan<Emp0054, Emp0198>.self; RosterSpan0087To0088.self } }
        ListItem { Link { UpWord.self; RosterSpan0082To0088.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0085To0086>.self
        TopicDoor<RosterSpan0087To0088>.self
    }
}

public enum RosterSpan0082To0088Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0050, Emp0198>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0050, Emp0059>.self; RosterSpan0082To0084.self } }
        ListItem { Link { NameSpan<Emp0055, Emp0198>.self; RosterSpan0085To0088.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0088.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0082To0084>.self
        TopicDoor<RosterSpan0085To0088>.self
    }
}

public enum RosterSpan0076To0088Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0052, Emp0198>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0052, Emp0197>.self; RosterSpan0076To0081.self } }
        ListItem { Link { NameSpan<Emp0050, Emp0198>.self; RosterSpan0082To0088.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0076To0081>.self
        TopicDoor<RosterSpan0082To0088>.self
    }
}

public enum RosterSpan0090To0091Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0195, Emp0058>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0195>.self; Emp0195.self } }
        ListItem { Link { NameOf<Emp0058>.self; Emp0058.self } }
        ListItem { Link { UpWord.self; RosterSpan0089To0091.self } }
        Break.self
    }
}

public enum RosterSpan0089To0091Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0051, Emp0058>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0051>.self; Emp0051.self } }
        ListItem { Link { NameSpan<Emp0195, Emp0058>.self; RosterSpan0090To0091.self } }
        ListItem { Link { UpWord.self; RosterSpan0089To0094.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0090To0091>.self
    }
}

public enum RosterSpan0093To0094Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0133, Emp0140>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0133>.self; Emp0133.self } }
        ListItem { Link { NameOf<Emp0140>.self; Emp0140.self } }
        ListItem { Link { UpWord.self; RosterSpan0092To0094.self } }
        Break.self
    }
}

public enum RosterSpan0092To0094Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0057, Emp0140>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0057>.self; Emp0057.self } }
        ListItem { Link { NameSpan<Emp0133, Emp0140>.self; RosterSpan0093To0094.self } }
        ListItem { Link { UpWord.self; RosterSpan0089To0094.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0093To0094>.self
    }
}

public enum RosterSpan0089To0094Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0051, Emp0140>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0051, Emp0058>.self; RosterSpan0089To0091.self } }
        ListItem { Link { NameSpan<Emp0057, Emp0140>.self; RosterSpan0092To0094.self } }
        ListItem { Link { UpWord.self; RosterSpan0089To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0089To0091>.self
        TopicDoor<RosterSpan0092To0094>.self
    }
}

public enum RosterSpan0096To0097Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0132, Emp0137>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0132>.self; Emp0132.self } }
        ListItem { Link { NameOf<Emp0137>.self; Emp0137.self } }
        ListItem { Link { UpWord.self; RosterSpan0095To0097.self } }
        Break.self
    }
}

public enum RosterSpan0095To0097Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0136, Emp0137>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0136>.self; Emp0136.self } }
        ListItem { Link { NameSpan<Emp0132, Emp0137>.self; RosterSpan0096To0097.self } }
        ListItem { Link { UpWord.self; RosterSpan0095To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0096To0097>.self
    }
}

public enum RosterSpan0098To0099Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0134, Emp0143>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0134>.self; Emp0134.self } }
        ListItem { Link { NameOf<Emp0143>.self; Emp0143.self } }
        ListItem { Link { UpWord.self; RosterSpan0098To0101.self } }
        Break.self
    }
}

public enum RosterSpan0100To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0139, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0139>.self; Emp0139.self } }
        ListItem { Link { NameOf<Emp0138>.self; Emp0138.self } }
        ListItem { Link { UpWord.self; RosterSpan0098To0101.self } }
        Break.self
    }
}

public enum RosterSpan0098To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0134, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0134, Emp0143>.self; RosterSpan0098To0099.self } }
        ListItem { Link { NameSpan<Emp0139, Emp0138>.self; RosterSpan0100To0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0095To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0098To0099>.self
        TopicDoor<RosterSpan0100To0101>.self
    }
}

public enum RosterSpan0095To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0136, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0136, Emp0137>.self; RosterSpan0095To0097.self } }
        ListItem { Link { NameSpan<Emp0134, Emp0138>.self; RosterSpan0098To0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0089To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0095To0097>.self
        TopicDoor<RosterSpan0098To0101>.self
    }
}

public enum RosterSpan0089To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0051, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0051, Emp0140>.self; RosterSpan0089To0094.self } }
        ListItem { Link { NameSpan<Emp0136, Emp0138>.self; RosterSpan0095To0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0076To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0089To0094>.self
        TopicDoor<RosterSpan0095To0101>.self
    }
}

public enum RosterSpan0076To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0052, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0052, Emp0198>.self; RosterSpan0076To0088.self } }
        ListItem { Link { NameSpan<Emp0051, Emp0138>.self; RosterSpan0089To0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0051To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0076To0088>.self
        TopicDoor<RosterSpan0089To0101>.self
    }
}

public enum RosterSpan0051To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0188, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0188, Emp0056>.self; RosterSpan0051To0075.self } }
        ListItem { Link { NameSpan<Emp0052, Emp0138>.self; RosterSpan0076To0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0101.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0051To0075>.self
        TopicDoor<RosterSpan0076To0101>.self
    }
}

public enum RosterSpan0000To0101Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0138>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0061, Emp0044>.self; RosterSpan0000To0050.self } }
        ListItem { Link { NameSpan<Emp0188, Emp0138>.self; RosterSpan0051To0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0000To0050>.self
        TopicDoor<RosterSpan0051To0101>.self
    }
}

public enum RosterSpan0103To0104Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0142, Emp0141>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0142>.self; Emp0142.self } }
        ListItem { Link { NameOf<Emp0141>.self; Emp0141.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0104.self } }
        Break.self
    }
}

public enum RosterSpan0102To0104Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0135, Emp0141>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0135>.self; Emp0135.self } }
        ListItem { Link { NameSpan<Emp0142, Emp0141>.self; RosterSpan0103To0104.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0107.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0103To0104>.self
    }
}

public enum RosterSpan0106To0107Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0157, Emp0020>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0157>.self; Emp0157.self } }
        ListItem { Link { NameOf<Emp0020>.self; Emp0020.self } }
        ListItem { Link { UpWord.self; RosterSpan0105To0107.self } }
        Break.self
    }
}

public enum RosterSpan0105To0107Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0013, Emp0020>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0013>.self; Emp0013.self } }
        ListItem { Link { NameSpan<Emp0157, Emp0020>.self; RosterSpan0106To0107.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0107.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0106To0107>.self
    }
}

public enum RosterSpan0102To0107Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0135, Emp0020>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0135, Emp0141>.self; RosterSpan0102To0104.self } }
        ListItem { Link { NameSpan<Emp0013, Emp0020>.self; RosterSpan0105To0107.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0113.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0102To0104>.self
        TopicDoor<RosterSpan0105To0107>.self
    }
}

public enum RosterSpan0109To0110Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0016, Emp0160>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0016>.self; Emp0016.self } }
        ListItem { Link { NameOf<Emp0160>.self; Emp0160.self } }
        ListItem { Link { UpWord.self; RosterSpan0108To0110.self } }
        Break.self
    }
}

public enum RosterSpan0108To0110Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0164, Emp0160>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0164>.self; Emp0164.self } }
        ListItem { Link { NameSpan<Emp0016, Emp0160>.self; RosterSpan0109To0110.self } }
        ListItem { Link { UpWord.self; RosterSpan0108To0113.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0109To0110>.self
    }
}

public enum RosterSpan0112To0113Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0156, Emp0017>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0156>.self; Emp0156.self } }
        ListItem { Link { NameOf<Emp0017>.self; Emp0017.self } }
        ListItem { Link { UpWord.self; RosterSpan0111To0113.self } }
        Break.self
    }
}

public enum RosterSpan0111To0113Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0012, Emp0017>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0012>.self; Emp0012.self } }
        ListItem { Link { NameSpan<Emp0156, Emp0017>.self; RosterSpan0112To0113.self } }
        ListItem { Link { UpWord.self; RosterSpan0108To0113.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0112To0113>.self
    }
}

public enum RosterSpan0108To0113Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0164, Emp0017>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0164, Emp0160>.self; RosterSpan0108To0110.self } }
        ListItem { Link { NameSpan<Emp0012, Emp0017>.self; RosterSpan0111To0113.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0113.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0108To0110>.self
        TopicDoor<RosterSpan0111To0113>.self
    }
}

public enum RosterSpan0102To0113Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0135, Emp0017>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0135, Emp0020>.self; RosterSpan0102To0107.self } }
        ListItem { Link { NameSpan<Emp0164, Emp0017>.self; RosterSpan0108To0113.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0126.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0102To0107>.self
        TopicDoor<RosterSpan0108To0113>.self
    }
}

public enum RosterSpan0115To0116Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0014, Emp0158>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0014>.self; Emp0014.self } }
        ListItem { Link { NameOf<Emp0158>.self; Emp0158.self } }
        ListItem { Link { UpWord.self; RosterSpan0114To0116.self } }
        Break.self
    }
}

public enum RosterSpan0114To0116Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0161, Emp0158>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0161>.self; Emp0161.self } }
        ListItem { Link { NameSpan<Emp0014, Emp0158>.self; RosterSpan0115To0116.self } }
        ListItem { Link { UpWord.self; RosterSpan0114To0119.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0115To0116>.self
    }
}

public enum RosterSpan0118To0119Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0167, Emp0019>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0167>.self; Emp0167.self } }
        ListItem { Link { NameOf<Emp0019>.self; Emp0019.self } }
        ListItem { Link { UpWord.self; RosterSpan0117To0119.self } }
        Break.self
    }
}

public enum RosterSpan0117To0119Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0023, Emp0019>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0023>.self; Emp0023.self } }
        ListItem { Link { NameSpan<Emp0167, Emp0019>.self; RosterSpan0118To0119.self } }
        ListItem { Link { UpWord.self; RosterSpan0114To0119.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0118To0119>.self
    }
}

public enum RosterSpan0114To0119Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0161, Emp0019>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0161, Emp0158>.self; RosterSpan0114To0116.self } }
        ListItem { Link { NameSpan<Emp0023, Emp0019>.self; RosterSpan0117To0119.self } }
        ListItem { Link { UpWord.self; RosterSpan0114To0126.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0114To0116>.self
        TopicDoor<RosterSpan0117To0119>.self
    }
}

public enum RosterSpan0121To0122Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0018, Emp0162>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0018>.self; Emp0018.self } }
        ListItem { Link { NameOf<Emp0162>.self; Emp0162.self } }
        ListItem { Link { UpWord.self; RosterSpan0120To0122.self } }
        Break.self
    }
}

public enum RosterSpan0120To0122Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0163, Emp0162>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0163>.self; Emp0163.self } }
        ListItem { Link { NameSpan<Emp0018, Emp0162>.self; RosterSpan0121To0122.self } }
        ListItem { Link { UpWord.self; RosterSpan0120To0126.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0121To0122>.self
    }
}

public enum RosterSpan0123To0124Page: Screen {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { NameSpan<Emp0015, Emp0159>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0015>.self; Emp0015.self } }
        ListItem { Link { NameOf<Emp0159>.self; Emp0159.self } }
        ListItem { Link { UpWord.self; RosterSpan0123To0126.self } }
        Break.self
    }
}
