import VerificationIsIdentification
import DocumentKit
import Organization

// GENERATED by `swift package generate org`: the walk film's frames — the real
// path to one person, each frame the step's own door witnesses.

enum FilmWord0: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self
    }
}
typealias FilmFrame0 = TimedReveal<FilmCue0, FilmDwell, FilmStepRight<FilmWord0, NameSpan<Emp0061, Emp0138>, NameSpan<Emp0135, Emp0117>>>
enum FilmCue0: Close {}
extension FilmCue0 {
    static var typeName: String { "0" }
}

enum FilmWord1: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self
    }
}
typealias FilmFrame1 = TimedReveal<FilmCue1, FilmDwell, FilmStepLeft<FilmWord1, NameSpan<Emp0135, Emp0033>, NameSpan<Emp0177, Emp0117>>>
enum FilmCue1: Close {}
extension FilmCue1 {
    static var typeName: String { "2" }
}

enum FilmWord2: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self
    }
}
typealias FilmFrame2 = TimedReveal<FilmCue2, FilmDwell, FilmStepRight<FilmWord2, NameSpan<Emp0135, Emp0166>, NameSpan<Emp0021, Emp0033>>>
enum FilmCue2: Close {}
extension FilmCue2 {
    static var typeName: String { "4" }
}

enum FilmWord3: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
    }
}
typealias FilmFrame3 = TimedReveal<FilmCue3, FilmDwell, FilmStepLeft<FilmWord3, NameSpan<Emp0021, Emp0173>, NameSpan<Emp0026, Emp0033>>>
enum FilmCue3: Close {}
extension FilmCue3 {
    static var typeName: String { "6" }
}

enum FilmWord4: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
    }
}
typealias FilmFrame4 = TimedReveal<FilmCue4, FilmDwell, FilmStepLeft<FilmWord4, NameSpan<Emp0021, Emp0032>, NameSpan<Emp0176, Emp0173>>>
enum FilmCue4: Close {}
extension FilmCue4 {
    static var typeName: String { "8" }
}

enum FilmWord5: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
    }
}
typealias FilmFrame5 = TimedReveal<FilmCue5, FilmDwell, FilmStepLeft<FilmWord5, NameSpan<Emp0021, Alice>, NameSpan<Emp0025, Emp0032>>>
enum FilmCue5: Close {}
extension FilmCue5 {
    static var typeName: String { "10" }
}

enum FilmWord6: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
    }
}
typealias FilmFrame6 = TimedReveal<FilmCue6, FilmDwell, FilmStepRight<FilmWord6, NameSpan<Emp0021, Emp0021>, NameSpan<Emp0165, Alice>>>
enum FilmCue6: Close {}
extension FilmCue6 {
    static var typeName: String { "12" }
}

enum FilmWord7: Fragment {
    @StructureBuilder
    static var body: some Structure {
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
    }
}
typealias FilmFrame7 = TimedReveal<FilmCue7, FilmDwell, FilmStepRight<FilmWord7, NameSpan<Emp0165, Emp0165>, NameSpan<Alice, Alice>>>
enum FilmCue7: Close {}
extension FilmCue7 {
    static var typeName: String { "14" }
}

enum FilmDwell: Close {}
extension FilmDwell {
    static var typeName: String { "2" }
}
enum FilmCueEnd: Close {}
extension FilmCueEnd {
    static var typeName: String { "16" }
}
typealias FilmFinale = FrozenReveal<FilmCueEnd, FilmSurvivorArt<NameOf<Alice>, Alice>>

enum WalkFilmAlt: Close {}
extension WalkFilmAlt {
    static var typeName: String {
        "The phone-book walk playing itself to Lovelace, Alice: 8 choices, "
            + "each frame the step's two doors with the taken one marked, ending frozen "
            + "on her name, which is a real link to her page."
    }
}
enum WalkFilmContent: Group {
    @StructureBuilder
    static var body: some Structure {
        FilmGroundRow.self
        FilmFrame0.self
        FilmFrame1.self
        FilmFrame2.self
        FilmFrame3.self
        FilmFrame4.self
        FilmFrame5.self
        FilmFrame6.self
        FilmFrame7.self
        FilmFinale.self
    }
}
enum WalkFilmDiagram: Diagram {
    typealias Size = FilmCanvasSize
    typealias AriaLabel = WalkFilmAlt
    typealias Content = WalkFilmContent
}

func renderWalkFilm() {
    write(WalkFilmDiagram.typeName, "walk-film")
    print("generated 1 walk film (8 frames + finale, SVG clock)")
}
