import VerificationIsIdentification
import DocumentKit
import Organization

// GENERATED by `swift package generate org`: the role walk's drawn doors, one
// strip per fork, faces read off the same types the markdown doors name.

enum RoleWalkDoorsAlt: Close {}
extension RoleWalkDoorsAlt {
    public static var typeName: String { "Two doors: Finance and Engineering, or Sales and People." }
}
typealias RoleWalkDoors = WalkDoorsStrip<
    RoleWalkDoorsAlt,
    RollCall<MoneyOrBuildSide>, SitePath<MoneyOrBuildSide>,
    RollCall<SalesOrPeopleSide>, SitePath<SalesOrPeopleSide>
>
enum MoneyOrBuildSideDoorsAlt: Close {}
extension MoneyOrBuildSideDoorsAlt {
    public static var typeName: String { "Two doors: Finance, or Engineering." }
}
typealias MoneyOrBuildSideDoors = WalkDoorsStrip<
    MoneyOrBuildSideDoorsAlt,
    RollCall<Finance>, SitePath<FinanceRanks>,
    RollCall<Engineering>, SitePath<EngineeringRanks>
>
enum SalesOrPeopleSideDoorsAlt: Close {}
extension SalesOrPeopleSideDoorsAlt {
    public static var typeName: String { "Two doors: Sales, or People." }
}
typealias SalesOrPeopleSideDoors = WalkDoorsStrip<
    SalesOrPeopleSideDoorsAlt,
    RollCall<Sales>, SitePath<SalesRanks>,
    RollCall<People>, SitePath<PeopleRanks>
>
enum FinanceRanksDoorsAlt: Close {}
extension FinanceRanksDoorsAlt {
    public static var typeName: String { "Two doors: the individual contributors, or the leads and managers." }
}
typealias FinanceRanksDoors = WalkDoorsStrip<
    FinanceRanksDoorsAlt,
    RollCall<IndividualContributor>, SitePath<FinanceIndividualContributors>,
    RollCall<LeadOrManagerPair>, SitePath<FinanceLeadOrManager>
>
enum FinanceLeadOrManagerDoorsAlt: Close {}
extension FinanceLeadOrManagerDoorsAlt {
    public static var typeName: String { "Two doors: the leads, or the managers." }
}
typealias FinanceLeadOrManagerDoors = WalkDoorsStrip<
    FinanceLeadOrManagerDoorsAlt,
    RollCall<Lead>, SitePath<FinanceLeads>,
    RollCall<Manager>, SitePath<FinanceManagers>
>
enum EngineeringRanksDoorsAlt: Close {}
extension EngineeringRanksDoorsAlt {
    public static var typeName: String { "Two doors: the individual contributors, or the leads and managers." }
}
typealias EngineeringRanksDoors = WalkDoorsStrip<
    EngineeringRanksDoorsAlt,
    RollCall<IndividualContributor>, SitePath<EngineeringIndividualContributors>,
    RollCall<LeadOrManagerPair>, SitePath<EngineeringLeadOrManager>
>
enum EngineeringLeadOrManagerDoorsAlt: Close {}
extension EngineeringLeadOrManagerDoorsAlt {
    public static var typeName: String { "Two doors: the leads, or the managers." }
}
typealias EngineeringLeadOrManagerDoors = WalkDoorsStrip<
    EngineeringLeadOrManagerDoorsAlt,
    RollCall<Lead>, SitePath<EngineeringLeads>,
    RollCall<Manager>, SitePath<EngineeringManagers>
>
enum SalesRanksDoorsAlt: Close {}
extension SalesRanksDoorsAlt {
    public static var typeName: String { "Two doors: the individual contributors, or the leads and managers." }
}
typealias SalesRanksDoors = WalkDoorsStrip<
    SalesRanksDoorsAlt,
    RollCall<IndividualContributor>, SitePath<SalesIndividualContributors>,
    RollCall<LeadOrManagerPair>, SitePath<SalesLeadOrManager>
>
enum SalesLeadOrManagerDoorsAlt: Close {}
extension SalesLeadOrManagerDoorsAlt {
    public static var typeName: String { "Two doors: the leads, or the managers." }
}
typealias SalesLeadOrManagerDoors = WalkDoorsStrip<
    SalesLeadOrManagerDoorsAlt,
    RollCall<Lead>, SitePath<SalesLeads>,
    RollCall<Manager>, SitePath<SalesManagers>
>
enum PeopleRanksDoorsAlt: Close {}
extension PeopleRanksDoorsAlt {
    public static var typeName: String { "Two doors: the individual contributors, or the leads and managers." }
}
typealias PeopleRanksDoors = WalkDoorsStrip<
    PeopleRanksDoorsAlt,
    RollCall<IndividualContributor>, SitePath<PeopleIndividualContributors>,
    RollCall<LeadOrManagerPair>, SitePath<PeopleLeadOrManager>
>
enum PeopleLeadOrManagerDoorsAlt: Close {}
extension PeopleLeadOrManagerDoorsAlt {
    public static var typeName: String { "Two doors: the leads, or the managers." }
}
typealias PeopleLeadOrManagerDoors = WalkDoorsStrip<
    PeopleLeadOrManagerDoorsAlt,
    RollCall<Lead>, SitePath<PeopleLeads>,
    RollCall<Manager>, SitePath<PeopleManagers>
>
func runRoleDoors() {
    write(RoleWalkDoors.typeName, "role-doors-rolewalk")
    write(MoneyOrBuildSideDoors.typeName, "role-doors-moneyorbuildside")
    write(SalesOrPeopleSideDoors.typeName, "role-doors-salesorpeopleside")
    write(FinanceRanksDoors.typeName, "role-doors-financeranks")
    write(FinanceLeadOrManagerDoors.typeName, "role-doors-financeleadormanager")
    write(EngineeringRanksDoors.typeName, "role-doors-engineeringranks")
    write(EngineeringLeadOrManagerDoors.typeName, "role-doors-engineeringleadormanager")
    write(SalesRanksDoors.typeName, "role-doors-salesranks")
    write(SalesLeadOrManagerDoors.typeName, "role-doors-salesleadormanager")
    write(PeopleRanksDoors.typeName, "role-doors-peopleranks")
    write(PeopleLeadOrManagerDoors.typeName, "role-doors-peopleleadormanager")
    print("generated \(11) role-walk door strips (Vector composition)")
}
