// ═══════════════════════════════════════════════════════
// Intelligence Is Inevitable (IiI) — paper 2
//
// Saturation theorem, crystallization axioms,
// phase transition dynamics.
// ═══════════════════════════════════════════════════════

/// The loop lifts the agent's guess to a certified result. Agent path becomes
/// system path via Thm2; ``VI_Identity`` pins `Left == SolutionSet`, so
/// verification *is* identification. [IiI §1]
public protocol AgentPathCertified: PassIsIdentification, VI_Identity {}

/// Knowledge accumulates irreversibly. Cache permanence (I3, ``CachePermanent``)
/// applied to ``HasLibrary``: the library is append-only. [IiI §2]
public protocol KnowledgeAccumulates: CachePermanent, HasLibrary {}

/// The library saturates: after K tasks, every rule class is covered. Two
/// compressions pin it down:
///   1. `Library: Permanent` — append-only (from I3, ``Permanent``).
///   2. `Library == SaturatedLibrary` — converges to its fixed point.
/// Before, `Library` and `SaturatedLibrary` are free (``Pair``, two axes);
/// after, `Library == SaturatedLibrary` (``Null``, one axis). [IiI §3]
public protocol LibrarySaturates: StructuresFinite, CachePermanent,
    HasLibrary, HasSaturation where Library: Permanent, Library == SaturatedLibrary {}

/// The saturated library is generated by a *finite* basis. ``LibrarySaturates``
/// pins `Basis` here in a theorem — finiteness is the measured result, not an
/// assumption, so it is not pinned inline at ``HasBasis`` (``Law`` §2 placement:
/// proven, not defined). [IiI §3]
public protocol BasisIsFinite: LibrarySaturates, HasBasis where Basis: IntegerValued {}

/// Encoding selection at level 2 also saturates: coverage over the encoding
/// grammar, not uniqueness. ``LibrarySaturates`` extended along ``HasEncoding``,
/// with `Encoding: Permanent` pinning the level-2 axis — coverage accumulates,
/// mirroring the library. [IiI §4]
public protocol EncodingSelectionSaturates: LibrarySaturates,
    HasEncoding where Encoding: Permanent {}

// §5 A1: S₀ ⊇ S₁ ⊇ ... — solution set only shrinks. This IS the V=I
// inner-loop result CandidatesOnlyLeave (§5.22); IiI reuses it directly
// (Law §1: the claim lives once, in VI.swift — no rename here).

/// A2: results are never retracted. ``CachePermanent`` (I3) plus
/// ``EqualityDecidable`` makes each individual membership result permanent.
/// [IiI §5; V=I I3, A4]
public protocol ResultsIrreversible: CachePermanent, EqualityDecidable {}

/// A3: membership in Sₙ is decidable at each step. ``EqualityDecidable`` over
/// ``HasSolutions``, compressing `SolutionSet: Decidable`. [IiI §5; V=I A4]
public protocol MembershipDecidable: EqualityDecidable,
    HasSolutions where SolutionSet: Decidable {}

/// The system reaches a terminal state: `∃n: |Sₙ| ≤ 1`. Four axioms force it.
/// [IiI §5]
/// A1 = ``CandidatesOnlyLeave`` (V=I §5.22), A2 = ``ResultsIrreversible``, A3 = ``MembershipDecidable``.
/// A4 conclusion pinned (§T): S collapses to one survivor — `where SolutionSet: Unique`.
///
/// > Note: Concrete domains certify by *conforming* to this protocol — quantum
/// > measurement, ice crystallization, and certified self-play all compile, so
/// > the type checker has proven they satisfy A1–A4. A system with no gate
/// > (its `SolutionSet` is not ``Unique``, e.g. a language model with |S|>1) is
/// > rejected, and the compiler names the missing coordinate. The build is the
/// > certificate; see the `Domains` target.
public protocol SystemCrystallizes: CandidatesOnlyLeave, ResultsIrreversible,
    MembershipDecidable where SolutionSet: Unique {}

/// Lemma 1: the V=I inner pipeline is a crystallizing system. A1–A4 hold.
/// ``SystemCrystallizes`` realized on ``PassIsIdentification``. [IiI §5]
public protocol PipelineCrystallizes: SystemCrystallizes, PassIsIdentification {}

/// Lemma 2: library accumulation is a crystallizing system. A1–A4 hold.
/// ``SystemCrystallizes`` realized on ``LibrarySaturates``. [IiI §5]
public protocol LibraryCrystallizes: SystemCrystallizes, LibrarySaturates {}

/// Saturation follows coupon-collector dynamics: `E[τ_sat] = K·H_K`. Bounded
/// comparisons (``ComparisonsAreBounded``) on a saturating library
/// (``LibrarySaturates``) fix the expected time. [IiI §6]
public protocol SaturationDynamics: LibrarySaturates, ComparisonsAreBounded {}

/// The library is revealed, not constructed: `f*` pre-exists. A saturated library
/// (``LibrarySaturates``) with a unique survivor (``ExactlyOneSurvives``) makes
/// discovery a revelation. [IiI §7]
public protocol DiscoveryIsRevelation: LibrarySaturates, ExactlyOneSurvives {}


// ── §3 Intelligence (η) — §T-generated ───────────────────────

/// Intelligence is a measured value: efficiency of identification,
/// `η = T_min / T_actual ∈ (0,1]`. A computed quantity over ``HasSigma``, so
/// ``Measurable`` (``Law`` §2). [IiI §3]
public protocol HasEfficiency: HasSigma {
    associatedtype Efficiency: Measurable
}

/// Intelligence is inevitable: under saturation, identification efficiency `η`
/// rises toward its maximum, and the efficiency gain *is* intelligence. A
/// saturating library (``LibrarySaturates``) drives ``HasEfficiency`` to its
/// fixpoint. [IiI §3, §8]
public protocol IntelligenceRises: LibrarySaturates, HasEfficiency {}
