import Foundation
import VerificationIsIdentification
import DocumentKit
import Organization

// GENERATED by `swift package generate org`: one page per roster halving. A door
// to a shelf wears `NameSpan` (its first and last person, phone-book order); a
// door to a person wears `NameOf`; every step page spells the word walked so far.
// All faces are witnesses, read off the types, never authored.


enum RosterSpan0125To0126Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0022, Emp0166>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0022>.self; Emp0022.self } }
        ListItem { Link { NameOf<Emp0166>.self; Emp0166.self } }
        ListItem { Link { UpWord.self; RosterSpan0123To0126.self } }
        Break.self
    }
}

enum RosterSpan0123To0126Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0015, Emp0166>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0015, Emp0159>.self; RosterSpan0123To0124.self } }
        ListItem { Link { NameSpan<Emp0022, Emp0166>.self; RosterSpan0125To0126.self } }
        ListItem { Link { UpWord.self; RosterSpan0120To0126.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0123To0124>.self
        TopicDoor<RosterSpan0125To0126>.self
    }
}

enum RosterSpan0120To0126Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0163, Emp0166>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0163, Emp0162>.self; RosterSpan0120To0122.self } }
        ListItem { Link { NameSpan<Emp0015, Emp0166>.self; RosterSpan0123To0126.self } }
        ListItem { Link { UpWord.self; RosterSpan0114To0126.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0120To0122>.self
        TopicDoor<RosterSpan0123To0126>.self
    }
}

enum RosterSpan0114To0126Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0161, Emp0166>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0161, Emp0019>.self; RosterSpan0114To0119.self } }
        ListItem { Link { NameSpan<Emp0163, Emp0166>.self; RosterSpan0120To0126.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0126.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0114To0119>.self
        TopicDoor<RosterSpan0120To0126>.self
    }
}

enum RosterSpan0102To0126Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0135, Emp0166>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0135, Emp0017>.self; RosterSpan0102To0113.self } }
        ListItem { Link { NameSpan<Emp0161, Emp0166>.self; RosterSpan0114To0126.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0102To0113>.self
        TopicDoor<RosterSpan0114To0126>.self
    }
}

enum RosterSpan0128To0129Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0165, Alice>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0165>.self; Emp0165.self } }
        ListItem { Link { NameOf<Alice>.self; Alice.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0129.self } }
        Break.self
    }
}

enum RosterSpan0127To0129Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0021, Alice>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0021>.self; Emp0021.self } }
        ListItem { Link { NameSpan<Emp0165, Alice>.self; RosterSpan0128To0129.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0132.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0128To0129>.self
    }
}

enum RosterSpan0131To0132Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0169, Emp0032>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0169>.self; Emp0169.self } }
        ListItem { Link { NameOf<Emp0032>.self; Emp0032.self } }
        ListItem { Link { UpWord.self; RosterSpan0130To0132.self } }
        Break.self
    }
}

enum RosterSpan0130To0132Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0025, Emp0032>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0025>.self; Emp0025.self } }
        ListItem { Link { NameSpan<Emp0169, Emp0032>.self; RosterSpan0131To0132.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0132.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0131To0132>.self
    }
}

enum RosterSpan0127To0132Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0021, Emp0032>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0021, Alice>.self; RosterSpan0127To0129.self } }
        ListItem { Link { NameSpan<Emp0025, Emp0032>.self; RosterSpan0130To0132.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0139.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0127To0129>.self
        TopicDoor<RosterSpan0130To0132>.self
    }
}

enum RosterSpan0134To0135Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0028, Emp0172>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0028>.self; Emp0028.self } }
        ListItem { Link { NameOf<Emp0172>.self; Emp0172.self } }
        ListItem { Link { UpWord.self; RosterSpan0133To0135.self } }
        Break.self
    }
}

enum RosterSpan0133To0135Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0176, Emp0172>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0176>.self; Emp0176.self } }
        ListItem { Link { NameSpan<Emp0028, Emp0172>.self; RosterSpan0134To0135.self } }
        ListItem { Link { UpWord.self; RosterSpan0133To0139.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0134To0135>.self
    }
}

enum RosterSpan0136To0137Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0024, Emp0168>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0024>.self; Emp0024.self } }
        ListItem { Link { NameOf<Emp0168>.self; Emp0168.self } }
        ListItem { Link { UpWord.self; RosterSpan0136To0139.self } }
        Break.self
    }
}

enum RosterSpan0138To0139Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0029, Emp0173>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0029>.self; Emp0029.self } }
        ListItem { Link { NameOf<Emp0173>.self; Emp0173.self } }
        ListItem { Link { UpWord.self; RosterSpan0136To0139.self } }
        Break.self
    }
}

enum RosterSpan0136To0139Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0024, Emp0173>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0024, Emp0168>.self; RosterSpan0136To0137.self } }
        ListItem { Link { NameSpan<Emp0029, Emp0173>.self; RosterSpan0138To0139.self } }
        ListItem { Link { UpWord.self; RosterSpan0133To0139.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0136To0137>.self
        TopicDoor<RosterSpan0138To0139>.self
    }
}

enum RosterSpan0133To0139Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0176, Emp0173>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0176, Emp0172>.self; RosterSpan0133To0135.self } }
        ListItem { Link { NameSpan<Emp0024, Emp0173>.self; RosterSpan0136To0139.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0139.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0133To0135>.self
        TopicDoor<RosterSpan0136To0139>.self
    }
}

enum RosterSpan0127To0139Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0021, Emp0173>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0021, Emp0032>.self; RosterSpan0127To0132.self } }
        ListItem { Link { NameSpan<Emp0176, Emp0173>.self; RosterSpan0133To0139.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0127To0132>.self
        TopicDoor<RosterSpan0133To0139>.self
    }
}

enum RosterSpan0141To0142Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0170, Emp0035>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0170>.self; Emp0170.self } }
        ListItem { Link { NameOf<Emp0035>.self; Emp0035.self } }
        ListItem { Link { UpWord.self; RosterSpan0140To0142.self } }
        Break.self
    }
}

enum RosterSpan0140To0142Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0026, Emp0035>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0026>.self; Emp0026.self } }
        ListItem { Link { NameSpan<Emp0170, Emp0035>.self; RosterSpan0141To0142.self } }
        ListItem { Link { UpWord.self; RosterSpan0140To0145.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0141To0142>.self
    }
}

enum RosterSpan0144To0145Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0031, Emp0175>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0031>.self; Emp0031.self } }
        ListItem { Link { NameOf<Emp0175>.self; Emp0175.self } }
        ListItem { Link { UpWord.self; RosterSpan0143To0145.self } }
        Break.self
    }
}

enum RosterSpan0143To0145Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0179, Emp0175>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0179>.self; Emp0179.self } }
        ListItem { Link { NameSpan<Emp0031, Emp0175>.self; RosterSpan0144To0145.self } }
        ListItem { Link { UpWord.self; RosterSpan0140To0145.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0144To0145>.self
    }
}

enum RosterSpan0140To0145Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0026, Emp0175>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0026, Emp0035>.self; RosterSpan0140To0142.self } }
        ListItem { Link { NameSpan<Emp0179, Emp0175>.self; RosterSpan0143To0145.self } }
        ListItem { Link { UpWord.self; RosterSpan0140To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0140To0142>.self
        TopicDoor<RosterSpan0143To0145>.self
    }
}

enum RosterSpan0147To0148Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0174, Emp0027>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0174>.self; Emp0174.self } }
        ListItem { Link { NameOf<Emp0027>.self; Emp0027.self } }
        ListItem { Link { UpWord.self; RosterSpan0146To0148.self } }
        Break.self
    }
}

enum RosterSpan0146To0148Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0030, Emp0027>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0030>.self; Emp0030.self } }
        ListItem { Link { NameSpan<Emp0174, Emp0027>.self; RosterSpan0147To0148.self } }
        ListItem { Link { UpWord.self; RosterSpan0146To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0147To0148>.self
    }
}

enum RosterSpan0149To0150Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0171, Emp0034>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0171>.self; Emp0171.self } }
        ListItem { Link { NameOf<Emp0034>.self; Emp0034.self } }
        ListItem { Link { UpWord.self; RosterSpan0149To0152.self } }
        Break.self
    }
}

enum RosterSpan0151To0152Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0178, Emp0033>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0178>.self; Emp0178.self } }
        ListItem { Link { NameOf<Emp0033>.self; Emp0033.self } }
        ListItem { Link { UpWord.self; RosterSpan0149To0152.self } }
        Break.self
    }
}

enum RosterSpan0149To0152Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0171, Emp0033>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0171, Emp0034>.self; RosterSpan0149To0150.self } }
        ListItem { Link { NameSpan<Emp0178, Emp0033>.self; RosterSpan0151To0152.self } }
        ListItem { Link { UpWord.self; RosterSpan0146To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0149To0150>.self
        TopicDoor<RosterSpan0151To0152>.self
    }
}

enum RosterSpan0146To0152Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0030, Emp0033>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0030, Emp0027>.self; RosterSpan0146To0148.self } }
        ListItem { Link { NameSpan<Emp0171, Emp0033>.self; RosterSpan0149To0152.self } }
        ListItem { Link { UpWord.self; RosterSpan0140To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0146To0148>.self
        TopicDoor<RosterSpan0149To0152>.self
    }
}

enum RosterSpan0140To0152Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0026, Emp0033>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0026, Emp0175>.self; RosterSpan0140To0145.self } }
        ListItem { Link { NameSpan<Emp0030, Emp0033>.self; RosterSpan0146To0152.self } }
        ListItem { Link { UpWord.self; RosterSpan0127To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0140To0145>.self
        TopicDoor<RosterSpan0146To0152>.self
    }
}

enum RosterSpan0127To0152Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0021, Emp0033>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0021, Emp0173>.self; RosterSpan0127To0139.self } }
        ListItem { Link { NameSpan<Emp0026, Emp0033>.self; RosterSpan0140To0152.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0152.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0127To0139>.self
        TopicDoor<RosterSpan0140To0152>.self
    }
}

enum RosterSpan0102To0152Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0135, Emp0033>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0135, Emp0166>.self; RosterSpan0102To0126.self } }
        ListItem { Link { NameSpan<Emp0021, Emp0033>.self; RosterSpan0127To0152.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0102To0126>.self
        TopicDoor<RosterSpan0127To0152>.self
    }
}

enum RosterSpan0154To0155Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0121, Emp0128>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0121>.self; Emp0121.self } }
        ListItem { Link { NameOf<Emp0128>.self; Emp0128.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0155.self } }
        Break.self
    }
}

enum RosterSpan0153To0155Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0177, Emp0128>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0177>.self; Emp0177.self } }
        ListItem { Link { NameSpan<Emp0121, Emp0128>.self; RosterSpan0154To0155.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0158.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0154To0155>.self
    }
}

enum RosterSpan0157To0158Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0120, Emp0125>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0120>.self; Emp0120.self } }
        ListItem { Link { NameOf<Emp0125>.self; Emp0125.self } }
        ListItem { Link { UpWord.self; RosterSpan0156To0158.self } }
        Break.self
    }
}

enum RosterSpan0156To0158Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0124, Emp0125>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0124>.self; Emp0124.self } }
        ListItem { Link { NameSpan<Emp0120, Emp0125>.self; RosterSpan0157To0158.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0158.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0157To0158>.self
    }
}

enum RosterSpan0153To0158Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0177, Emp0125>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0177, Emp0128>.self; RosterSpan0153To0155.self } }
        ListItem { Link { NameSpan<Emp0124, Emp0125>.self; RosterSpan0156To0158.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0164.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0153To0155>.self
        TopicDoor<RosterSpan0156To0158>.self
    }
}

enum RosterSpan0160To0161Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0131, Emp0127>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0131>.self; Emp0131.self } }
        ListItem { Link { NameOf<Emp0127>.self; Emp0127.self } }
        ListItem { Link { UpWord.self; RosterSpan0159To0161.self } }
        Break.self
    }
}

enum RosterSpan0159To0161Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0122, Emp0127>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0122>.self; Emp0122.self } }
        ListItem { Link { NameSpan<Emp0131, Emp0127>.self; RosterSpan0160To0161.self } }
        ListItem { Link { UpWord.self; RosterSpan0159To0164.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0160To0161>.self
    }
}

enum RosterSpan0163To0164Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0123, Emp0130>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0123>.self; Emp0123.self } }
        ListItem { Link { NameOf<Emp0130>.self; Emp0130.self } }
        ListItem { Link { UpWord.self; RosterSpan0162To0164.self } }
        Break.self
    }
}

enum RosterSpan0162To0164Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0126, Emp0130>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0126>.self; Emp0126.self } }
        ListItem { Link { NameSpan<Emp0123, Emp0130>.self; RosterSpan0163To0164.self } }
        ListItem { Link { UpWord.self; RosterSpan0159To0164.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0163To0164>.self
    }
}

enum RosterSpan0159To0164Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0122, Emp0130>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0122, Emp0127>.self; RosterSpan0159To0161.self } }
        ListItem { Link { NameSpan<Emp0126, Emp0130>.self; RosterSpan0162To0164.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0164.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0159To0161>.self
        TopicDoor<RosterSpan0162To0164>.self
    }
}

enum RosterSpan0153To0164Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0177, Emp0130>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0177, Emp0125>.self; RosterSpan0153To0158.self } }
        ListItem { Link { NameSpan<Emp0122, Emp0130>.self; RosterSpan0159To0164.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0177.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0153To0158>.self
        TopicDoor<RosterSpan0159To0164>.self
    }
}

enum RosterSpan0166To0167Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0097, Emp0104>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0097>.self; Emp0097.self } }
        ListItem { Link { NameOf<Emp0104>.self; Emp0104.self } }
        ListItem { Link { UpWord.self; RosterSpan0165To0167.self } }
        Break.self
    }
}

enum RosterSpan0165To0167Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0129, Emp0104>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0129>.self; Emp0129.self } }
        ListItem { Link { NameSpan<Emp0097, Emp0104>.self; RosterSpan0166To0167.self } }
        ListItem { Link { UpWord.self; RosterSpan0165To0170.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0166To0167>.self
    }
}

enum RosterSpan0169To0170Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0096, Emp0101>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0096>.self; Emp0096.self } }
        ListItem { Link { NameOf<Emp0101>.self; Emp0101.self } }
        ListItem { Link { UpWord.self; RosterSpan0168To0170.self } }
        Break.self
    }
}

enum RosterSpan0168To0170Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0100, Emp0101>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0100>.self; Emp0100.self } }
        ListItem { Link { NameSpan<Emp0096, Emp0101>.self; RosterSpan0169To0170.self } }
        ListItem { Link { UpWord.self; RosterSpan0165To0170.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0169To0170>.self
    }
}

enum RosterSpan0165To0170Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0129, Emp0101>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0129, Emp0104>.self; RosterSpan0165To0167.self } }
        ListItem { Link { NameSpan<Emp0100, Emp0101>.self; RosterSpan0168To0170.self } }
        ListItem { Link { UpWord.self; RosterSpan0165To0177.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0165To0167>.self
        TopicDoor<RosterSpan0168To0170>.self
    }
}

enum RosterSpan0172To0173Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0107, Emp0103>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0107>.self; Emp0107.self } }
        ListItem { Link { NameOf<Emp0103>.self; Emp0103.self } }
        ListItem { Link { UpWord.self; RosterSpan0171To0173.self } }
        Break.self
    }
}

enum RosterSpan0171To0173Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0098, Emp0103>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0098>.self; Emp0098.self } }
        ListItem { Link { NameSpan<Emp0107, Emp0103>.self; RosterSpan0172To0173.self } }
        ListItem { Link { UpWord.self; RosterSpan0171To0177.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0172To0173>.self
    }
}

enum RosterSpan0174To0175Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0102, Emp0099>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0102>.self; Emp0102.self } }
        ListItem { Link { NameOf<Emp0099>.self; Emp0099.self } }
        ListItem { Link { UpWord.self; RosterSpan0174To0177.self } }
        Break.self
    }
}

enum RosterSpan0176To0177Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0106, Emp0105>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0106>.self; Emp0106.self } }
        ListItem { Link { NameOf<Emp0105>.self; Emp0105.self } }
        ListItem { Link { UpWord.self; RosterSpan0174To0177.self } }
        Break.self
    }
}

enum RosterSpan0174To0177Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0102, Emp0105>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0102, Emp0099>.self; RosterSpan0174To0175.self } }
        ListItem { Link { NameSpan<Emp0106, Emp0105>.self; RosterSpan0176To0177.self } }
        ListItem { Link { UpWord.self; RosterSpan0171To0177.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0174To0175>.self
        TopicDoor<RosterSpan0176To0177>.self
    }
}

enum RosterSpan0171To0177Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0098, Emp0105>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0098, Emp0103>.self; RosterSpan0171To0173.self } }
        ListItem { Link { NameSpan<Emp0102, Emp0105>.self; RosterSpan0174To0177.self } }
        ListItem { Link { UpWord.self; RosterSpan0165To0177.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0171To0173>.self
        TopicDoor<RosterSpan0174To0177>.self
    }
}

enum RosterSpan0165To0177Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0129, Emp0105>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0129, Emp0101>.self; RosterSpan0165To0170.self } }
        ListItem { Link { NameSpan<Emp0098, Emp0105>.self; RosterSpan0171To0177.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0177.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0165To0170>.self
        TopicDoor<RosterSpan0171To0177>.self
    }
}

enum RosterSpan0153To0177Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0177, Emp0105>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0177, Emp0130>.self; RosterSpan0153To0164.self } }
        ListItem { Link { NameSpan<Emp0129, Emp0105>.self; RosterSpan0165To0177.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0153To0164>.self
        TopicDoor<RosterSpan0165To0177>.self
    }
}

enum RosterSpan0179To0180Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0080, Emp0076>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0080>.self; Emp0080.self } }
        ListItem { Link { NameOf<Emp0076>.self; Emp0076.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0180.self } }
        Break.self
    }
}

enum RosterSpan0178To0180Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0073, Emp0076>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0073>.self; Emp0073.self } }
        ListItem { Link { NameSpan<Emp0080, Emp0076>.self; RosterSpan0179To0180.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0183.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0179To0180>.self
    }
}

enum RosterSpan0182To0183Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0077, Emp0074>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0077>.self; Emp0077.self } }
        ListItem { Link { NameOf<Emp0074>.self; Emp0074.self } }
        ListItem { Link { UpWord.self; RosterSpan0181To0183.self } }
        Break.self
    }
}

enum RosterSpan0181To0183Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0072, Emp0074>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0072>.self; Emp0072.self } }
        ListItem { Link { NameSpan<Emp0077, Emp0074>.self; RosterSpan0182To0183.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0183.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0182To0183>.self
    }
}

enum RosterSpan0178To0183Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0073, Emp0074>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0073, Emp0076>.self; RosterSpan0178To0180.self } }
        ListItem { Link { NameSpan<Emp0072, Emp0074>.self; RosterSpan0181To0183.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0190.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0178To0180>.self
        TopicDoor<RosterSpan0181To0183>.self
    }
}

enum RosterSpan0185To0186Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0079, Emp0078>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0079>.self; Emp0079.self } }
        ListItem { Link { NameOf<Emp0078>.self; Emp0078.self } }
        ListItem { Link { UpWord.self; RosterSpan0184To0186.self } }
        Break.self
    }
}

enum RosterSpan0184To0186Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0083, Emp0078>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0083>.self; Emp0083.self } }
        ListItem { Link { NameSpan<Emp0079, Emp0078>.self; RosterSpan0185To0186.self } }
        ListItem { Link { UpWord.self; RosterSpan0184To0190.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0185To0186>.self
    }
}

enum RosterSpan0187To0188Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0075, Emp0082>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0075>.self; Emp0075.self } }
        ListItem { Link { NameOf<Emp0082>.self; Emp0082.self } }
        ListItem { Link { UpWord.self; RosterSpan0187To0190.self } }
        Break.self
    }
}

enum RosterSpan0189To0190Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0081, Dave>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0081>.self; Emp0081.self } }
        ListItem { Link { NameOf<Dave>.self; Dave.self } }
        ListItem { Link { UpWord.self; RosterSpan0187To0190.self } }
        Break.self
    }
}

enum RosterSpan0187To0190Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0075, Dave>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0075, Emp0082>.self; RosterSpan0187To0188.self } }
        ListItem { Link { NameSpan<Emp0081, Dave>.self; RosterSpan0189To0190.self } }
        ListItem { Link { UpWord.self; RosterSpan0184To0190.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0187To0188>.self
        TopicDoor<RosterSpan0189To0190>.self
    }
}

enum RosterSpan0184To0190Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0083, Dave>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0083, Emp0078>.self; RosterSpan0184To0186.self } }
        ListItem { Link { NameSpan<Emp0075, Dave>.self; RosterSpan0187To0190.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0190.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0184To0186>.self
        TopicDoor<RosterSpan0187To0190>.self
    }
}

enum RosterSpan0178To0190Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0073, Dave>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Emp0073, Emp0074>.self; RosterSpan0178To0183.self } }
        ListItem { Link { NameSpan<Emp0083, Dave>.self; RosterSpan0184To0190.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0178To0183>.self
        TopicDoor<RosterSpan0184To0190>.self
    }
}

enum RosterSpan0192To0193Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0109, Emp0116>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0109>.self; Emp0109.self } }
        ListItem { Link { NameOf<Emp0116>.self; Emp0116.self } }
        ListItem { Link { UpWord.self; RosterSpan0191To0193.self } }
        Break.self
    }
}

enum RosterSpan0191To0193Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Bob, Emp0116>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Bob>.self; Bob.self } }
        ListItem { Link { NameSpan<Emp0109, Emp0116>.self; RosterSpan0192To0193.self } }
        ListItem { Link { UpWord.self; RosterSpan0191To0196.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0192To0193>.self
    }
}

enum RosterSpan0195To0196Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0108, Emp0113>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0108>.self; Emp0108.self } }
        ListItem { Link { NameOf<Emp0113>.self; Emp0113.self } }
        ListItem { Link { UpWord.self; RosterSpan0194To0196.self } }
        Break.self
    }
}

enum RosterSpan0194To0196Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0112, Emp0113>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0112>.self; Emp0112.self } }
        ListItem { Link { NameSpan<Emp0108, Emp0113>.self; RosterSpan0195To0196.self } }
        ListItem { Link { UpWord.self; RosterSpan0191To0196.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0195To0196>.self
    }
}

enum RosterSpan0191To0196Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Bob, Emp0113>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameSpan<Bob, Emp0116>.self; RosterSpan0191To0193.self } }
        ListItem { Link { NameSpan<Emp0112, Emp0113>.self; RosterSpan0194To0196.self } }
        ListItem { Link { UpWord.self; RosterSpan0191To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0191To0193>.self
        TopicDoor<RosterSpan0194To0196>.self
    }
}

enum RosterSpan0198To0199Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0119, Emp0115>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0119>.self; Emp0119.self } }
        ListItem { Link { NameOf<Emp0115>.self; Emp0115.self } }
        ListItem { Link { UpWord.self; RosterSpan0197To0199.self } }
        Break.self
    }
}

enum RosterSpan0197To0199Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0110, Emp0115>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0110>.self; Emp0110.self } }
        ListItem { Link { NameSpan<Emp0119, Emp0115>.self; RosterSpan0198To0199.self } }
        ListItem { Link { UpWord.self; RosterSpan0197To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0198To0199>.self
    }
}

enum RosterSpan0200To0201Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0114, Emp0111>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        ListItem { Link { NameOf<Emp0114>.self; Emp0114.self } }
        ListItem { Link { NameOf<Emp0111>.self; Emp0111.self } }
        ListItem { Link { UpWord.self; RosterSpan0200To0203.self } }
        Break.self
    }
}

enum RosterSpan0202To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0118, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameOf<Emp0118>.self; Emp0118.self } }
        ListItem { Link { NameOf<Emp0117>.self; Emp0117.self } }
        ListItem { Link { UpWord.self; RosterSpan0200To0203.self } }
        Break.self
    }
}

enum RosterSpan0200To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0114, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0114, Emp0111>.self; RosterSpan0200To0201.self } }
        ListItem { Link { NameSpan<Emp0118, Emp0117>.self; RosterSpan0202To0203.self } }
        ListItem { Link { UpWord.self; RosterSpan0197To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0200To0201>.self
        TopicDoor<RosterSpan0202To0203>.self
    }
}

enum RosterSpan0197To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0110, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0110, Emp0115>.self; RosterSpan0197To0199.self } }
        ListItem { Link { NameSpan<Emp0114, Emp0117>.self; RosterSpan0200To0203.self } }
        ListItem { Link { UpWord.self; RosterSpan0191To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0197To0199>.self
        TopicDoor<RosterSpan0200To0203>.self
    }
}

enum RosterSpan0191To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Bob, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Bob, Emp0113>.self; RosterSpan0191To0196.self } }
        ListItem { Link { NameSpan<Emp0110, Emp0117>.self; RosterSpan0197To0203.self } }
        ListItem { Link { UpWord.self; RosterSpan0178To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0191To0196>.self
        TopicDoor<RosterSpan0197To0203>.self
    }
}

enum RosterSpan0178To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0073, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0073, Dave>.self; RosterSpan0178To0190.self } }
        ListItem { Link { NameSpan<Bob, Emp0117>.self; RosterSpan0191To0203.self } }
        ListItem { Link { UpWord.self; RosterSpan0153To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0178To0190>.self
        TopicDoor<RosterSpan0191To0203>.self
    }
}

enum RosterSpan0153To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0177, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0177, Emp0105>.self; RosterSpan0153To0177.self } }
        ListItem { Link { NameSpan<Emp0073, Emp0117>.self; RosterSpan0178To0203.self } }
        ListItem { Link { UpWord.self; RosterSpan0102To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0153To0177>.self
        TopicDoor<RosterSpan0178To0203>.self
    }
}

enum RosterSpan0102To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0135, Emp0117>.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self
        Break.self
        ListItem { Link { NameSpan<Emp0135, Emp0033>.self; RosterSpan0102To0152.self } }
        ListItem { Link { NameSpan<Emp0177, Emp0117>.self; RosterSpan0153To0203.self } }
        ListItem { Link { UpWord.self; RosterSpan0000To0203.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0102To0152>.self
        TopicDoor<RosterSpan0153To0203>.self
    }
}

enum RosterSpan0000To0203Page: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { NameSpan<Emp0061, Emp0117>.self }
        WalkHint.self; Break.self
        ListItem { Link { NameSpan<Emp0061, Emp0138>.self; RosterSpan0000To0101.self } }
        ListItem { Link { NameSpan<Emp0135, Emp0117>.self; RosterSpan0102To0203.self } }
        ListItem { Link { UpWord.self; PeopleHalf.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<RosterSpan0000To0101>.self
        TopicDoor<RosterSpan0102To0203>.self
    }
}
