import Foundation
import VerificationIsIdentification
import DocumentKit
import Organization

// GENERATED by `swift package generate org`: the role walk. Four doors form the
// (department, rank) pair; every step spells its word; the cell pages merge onto
// the cohorts' own symbol pages and read the verdicts through SomeoneAs.

enum RoleWalkDoorsPictureAlt: Close {}
extension RoleWalkDoorsPictureAlt {
    static var typeName: String { "Form a query: which department?" }
}
enum RoleWalkDoorsPictureAsset: Close {}
extension RoleWalkDoorsPictureAsset {
    static var typeName: String { "role-doors-rolewalk" }
}
enum RoleWalkTitle: Close {}
extension RoleWalkTitle {
    static var typeName: String { "Form a query: which department?" }
}
enum RoleWalkPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { RoleWalkTitle.self }
        WalkHint.self; Break.self
        Picture { RoleWalkDoorsPictureAlt.self; RoleWalkDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<MoneyOrBuildSide>.self; MoneyOrBuildSide.self } }
        ListItem { Link { RollCall<SalesOrPeopleSide>.self; SalesOrPeopleSide.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<MoneyOrBuildSide>.self
        TopicDoor<SalesOrPeopleSide>.self
    }
}

enum MoneyOrBuildSideDoorsPictureAlt: Close {}
extension MoneyOrBuildSideDoorsPictureAlt {
    static var typeName: String { "Finance, or Engineering?" }
}
enum MoneyOrBuildSideDoorsPictureAsset: Close {}
extension MoneyOrBuildSideDoorsPictureAsset {
    static var typeName: String { "role-doors-moneyorbuildside" }
}
enum MoneyOrBuildSideTitle: Close {}
extension MoneyOrBuildSideTitle {
    static var typeName: String { "Finance, or Engineering?" }
}
enum MoneyOrBuildSidePage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { MoneyOrBuildSideTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self
        Break.self
        Picture { MoneyOrBuildSideDoorsPictureAlt.self; MoneyOrBuildSideDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<Finance>.self; FinanceRanks.self } }
        ListItem { Link { RollCall<Engineering>.self; EngineeringRanks.self } }
        ListItem { Link { UpWord.self; RoleWalk.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<FinanceRanks>.self
        TopicDoor<EngineeringRanks>.self
    }
}

enum FinanceRanksDoorsPictureAlt: Close {}
extension FinanceRanksDoorsPictureAlt {
    static var typeName: String { "A rank in Finance: the individual contributors, or the leads and managers?" }
}
enum FinanceRanksDoorsPictureAsset: Close {}
extension FinanceRanksDoorsPictureAsset {
    static var typeName: String { "role-doors-financeranks" }
}
enum FinanceRanksTitle: Close {}
extension FinanceRanksTitle {
    static var typeName: String { "A rank in Finance: the individual contributors, or the leads and managers?" }
}
enum FinanceRanksPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { FinanceRanksTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self
        Break.self
        Picture { FinanceRanksDoorsPictureAlt.self; FinanceRanksDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<IndividualContributor>.self; FinanceIndividualContributors.self } }
        ListItem { Link { RollCall<LeadOrManagerPair>.self; FinanceLeadOrManager.self } }
        ListItem { Link { UpWord.self; MoneyOrBuildSide.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<FinanceIndividualContributors>.self
        TopicDoor<FinanceLeadOrManager>.self
    }
}

enum FinanceLeadOrManagerDoorsPictureAlt: Close {}
extension FinanceLeadOrManagerDoorsPictureAlt {
    static var typeName: String { "In Finance: a lead, or a manager?" }
}
enum FinanceLeadOrManagerDoorsPictureAsset: Close {}
extension FinanceLeadOrManagerDoorsPictureAsset {
    static var typeName: String { "role-doors-financeleadormanager" }
}
enum FinanceLeadOrManagerTitle: Close {}
extension FinanceLeadOrManagerTitle {
    static var typeName: String { "In Finance: a lead, or a manager?" }
}
enum FinanceLeadOrManagerPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { FinanceLeadOrManagerTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        Picture { FinanceLeadOrManagerDoorsPictureAlt.self; FinanceLeadOrManagerDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<Lead>.self; FinanceLeads.self } }
        ListItem { Link { RollCall<Manager>.self; FinanceManagers.self } }
        ListItem { Link { UpWord.self; FinanceRanks.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<FinanceLeads>.self
        TopicDoor<FinanceManagers>.self
    }
}

enum EngineeringRanksDoorsPictureAlt: Close {}
extension EngineeringRanksDoorsPictureAlt {
    static var typeName: String { "A rank in Engineering: the individual contributors, or the leads and managers?" }
}
enum EngineeringRanksDoorsPictureAsset: Close {}
extension EngineeringRanksDoorsPictureAsset {
    static var typeName: String { "role-doors-engineeringranks" }
}
enum EngineeringRanksTitle: Close {}
extension EngineeringRanksTitle {
    static var typeName: String { "A rank in Engineering: the individual contributors, or the leads and managers?" }
}
enum EngineeringRanksPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { EngineeringRanksTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        Picture { EngineeringRanksDoorsPictureAlt.self; EngineeringRanksDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<IndividualContributor>.self; EngineeringIndividualContributors.self } }
        ListItem { Link { RollCall<LeadOrManagerPair>.self; EngineeringLeadOrManager.self } }
        ListItem { Link { UpWord.self; MoneyOrBuildSide.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<EngineeringIndividualContributors>.self
        TopicDoor<EngineeringLeadOrManager>.self
    }
}

enum EngineeringLeadOrManagerDoorsPictureAlt: Close {}
extension EngineeringLeadOrManagerDoorsPictureAlt {
    static var typeName: String { "In Engineering: a lead, or a manager?" }
}
enum EngineeringLeadOrManagerDoorsPictureAsset: Close {}
extension EngineeringLeadOrManagerDoorsPictureAsset {
    static var typeName: String { "role-doors-engineeringleadormanager" }
}
enum EngineeringLeadOrManagerTitle: Close {}
extension EngineeringLeadOrManagerTitle {
    static var typeName: String { "In Engineering: a lead, or a manager?" }
}
enum EngineeringLeadOrManagerPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { EngineeringLeadOrManagerTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentLeft.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        Picture { EngineeringLeadOrManagerDoorsPictureAlt.self; EngineeringLeadOrManagerDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<Lead>.self; EngineeringLeads.self } }
        ListItem { Link { RollCall<Manager>.self; EngineeringManagers.self } }
        ListItem { Link { UpWord.self; EngineeringRanks.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<EngineeringLeads>.self
        TopicDoor<EngineeringManagers>.self
    }
}

enum SalesOrPeopleSideDoorsPictureAlt: Close {}
extension SalesOrPeopleSideDoorsPictureAlt {
    static var typeName: String { "Sales, or People?" }
}
enum SalesOrPeopleSideDoorsPictureAsset: Close {}
extension SalesOrPeopleSideDoorsPictureAsset {
    static var typeName: String { "role-doors-salesorpeopleside" }
}
enum SalesOrPeopleSideTitle: Close {}
extension SalesOrPeopleSideTitle {
    static var typeName: String { "Sales, or People?" }
}
enum SalesOrPeopleSidePage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { SalesOrPeopleSideTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self
        Break.self
        Picture { SalesOrPeopleSideDoorsPictureAlt.self; SalesOrPeopleSideDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<Sales>.self; SalesRanks.self } }
        ListItem { Link { RollCall<People>.self; PeopleRanks.self } }
        ListItem { Link { UpWord.self; RoleWalk.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<SalesRanks>.self
        TopicDoor<PeopleRanks>.self
    }
}

enum SalesRanksDoorsPictureAlt: Close {}
extension SalesRanksDoorsPictureAlt {
    static var typeName: String { "A rank in Sales: the individual contributors, or the leads and managers?" }
}
enum SalesRanksDoorsPictureAsset: Close {}
extension SalesRanksDoorsPictureAsset {
    static var typeName: String { "role-doors-salesranks" }
}
enum SalesRanksTitle: Close {}
extension SalesRanksTitle {
    static var typeName: String { "A rank in Sales: the individual contributors, or the leads and managers?" }
}
enum SalesRanksPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { SalesRanksTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self
        Break.self
        Picture { SalesRanksDoorsPictureAlt.self; SalesRanksDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<IndividualContributor>.self; SalesIndividualContributors.self } }
        ListItem { Link { RollCall<LeadOrManagerPair>.self; SalesLeadOrManager.self } }
        ListItem { Link { UpWord.self; SalesOrPeopleSide.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<SalesIndividualContributors>.self
        TopicDoor<SalesLeadOrManager>.self
    }
}

enum SalesLeadOrManagerDoorsPictureAlt: Close {}
extension SalesLeadOrManagerDoorsPictureAlt {
    static var typeName: String { "In Sales: a lead, or a manager?" }
}
enum SalesLeadOrManagerDoorsPictureAsset: Close {}
extension SalesLeadOrManagerDoorsPictureAsset {
    static var typeName: String { "role-doors-salesleadormanager" }
}
enum SalesLeadOrManagerTitle: Close {}
extension SalesLeadOrManagerTitle {
    static var typeName: String { "In Sales: a lead, or a manager?" }
}
enum SalesLeadOrManagerPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { SalesLeadOrManagerTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentLeft.self; StepDot.self; WentRight.self
        Break.self
        Picture { SalesLeadOrManagerDoorsPictureAlt.self; SalesLeadOrManagerDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<Lead>.self; SalesLeads.self } }
        ListItem { Link { RollCall<Manager>.self; SalesManagers.self } }
        ListItem { Link { UpWord.self; SalesRanks.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<SalesLeads>.self
        TopicDoor<SalesManagers>.self
    }
}

enum PeopleRanksDoorsPictureAlt: Close {}
extension PeopleRanksDoorsPictureAlt {
    static var typeName: String { "A rank in People: the individual contributors, or the leads and managers?" }
}
enum PeopleRanksDoorsPictureAsset: Close {}
extension PeopleRanksDoorsPictureAsset {
    static var typeName: String { "role-doors-peopleranks" }
}
enum PeopleRanksTitle: Close {}
extension PeopleRanksTitle {
    static var typeName: String { "A rank in People: the individual contributors, or the leads and managers?" }
}
enum PeopleRanksPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { PeopleRanksTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        Picture { PeopleRanksDoorsPictureAlt.self; PeopleRanksDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<IndividualContributor>.self; PeopleIndividualContributors.self } }
        ListItem { Link { RollCall<LeadOrManagerPair>.self; PeopleLeadOrManager.self } }
        ListItem { Link { UpWord.self; SalesOrPeopleSide.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<PeopleIndividualContributors>.self
        TopicDoor<PeopleLeadOrManager>.self
    }
}

enum PeopleLeadOrManagerDoorsPictureAlt: Close {}
extension PeopleLeadOrManagerDoorsPictureAlt {
    static var typeName: String { "In People: a lead, or a manager?" }
}
enum PeopleLeadOrManagerDoorsPictureAsset: Close {}
extension PeopleLeadOrManagerDoorsPictureAsset {
    static var typeName: String { "role-doors-peopleleadormanager" }
}
enum PeopleLeadOrManagerTitle: Close {}
extension PeopleLeadOrManagerTitle {
    static var typeName: String { "In People: a lead, or a manager?" }
}
enum PeopleLeadOrManagerPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { PeopleLeadOrManagerTitle.self }
        WalkHint.self; Break.self
        WordSoFar.self; WentRight.self; StepDot.self; WentRight.self; StepDot.self; WentRight.self
        Break.self
        Picture { PeopleLeadOrManagerDoorsPictureAlt.self; PeopleLeadOrManagerDoorsPictureAsset.self }
        Break.self
        ListItem { Link { RollCall<Lead>.self; PeopleLeads.self } }
        ListItem { Link { RollCall<Manager>.self; PeopleManagers.self } }
        ListItem { Link { UpWord.self; PeopleRanks.self } }
        Break.self
        TopicsHeadingBlock.self
        TopicDoor<PeopleLeads>.self
        TopicDoor<PeopleManagers>.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum FinanceIndividualContributorsVaultVerdict: Close {}
extension FinanceIndividualContributorsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Finance, IndividualContributor>, FinanceVault>.typeName }
}
enum FinanceIndividualContributorsRepoVerdict: Close {}
extension FinanceIndividualContributorsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Finance, IndividualContributor>, EngineeringRepo>.typeName }
}
enum FinanceIndividualContributorsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<FinanceIndividualContributors>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<FinanceIndividualContributors>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; FinanceIndividualContributorsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; FinanceIndividualContributorsRepoVerdict.self }
        ListItem { Link { UpWord.self; FinanceRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum FinanceLeadsVaultVerdict: Close {}
extension FinanceLeadsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Finance, Lead>, FinanceVault>.typeName }
}
enum FinanceLeadsRepoVerdict: Close {}
extension FinanceLeadsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Finance, Lead>, EngineeringRepo>.typeName }
}
enum FinanceLeadsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<FinanceLeads>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<FinanceLeads>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; FinanceLeadsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; FinanceLeadsRepoVerdict.self }
        ListItem { Link { UpWord.self; FinanceRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum FinanceManagersVaultVerdict: Close {}
extension FinanceManagersVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Finance, Manager>, FinanceVault>.typeName }
}
enum FinanceManagersRepoVerdict: Close {}
extension FinanceManagersRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Finance, Manager>, EngineeringRepo>.typeName }
}
enum FinanceManagersCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<FinanceManagers>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<FinanceManagers>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; FinanceManagersVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; FinanceManagersRepoVerdict.self }
        ListItem { Link { UpWord.self; FinanceRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum EngineeringIndividualContributorsVaultVerdict: Close {}
extension EngineeringIndividualContributorsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Engineering, IndividualContributor>, FinanceVault>.typeName }
}
enum EngineeringIndividualContributorsRepoVerdict: Close {}
extension EngineeringIndividualContributorsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Engineering, IndividualContributor>, EngineeringRepo>.typeName }
}
enum EngineeringIndividualContributorsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<EngineeringIndividualContributors>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<EngineeringIndividualContributors>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; EngineeringIndividualContributorsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; EngineeringIndividualContributorsRepoVerdict.self }
        ListItem { Link { UpWord.self; EngineeringRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum EngineeringLeadsVaultVerdict: Close {}
extension EngineeringLeadsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Engineering, Lead>, FinanceVault>.typeName }
}
enum EngineeringLeadsRepoVerdict: Close {}
extension EngineeringLeadsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Engineering, Lead>, EngineeringRepo>.typeName }
}
enum EngineeringLeadsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<EngineeringLeads>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<EngineeringLeads>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; EngineeringLeadsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; EngineeringLeadsRepoVerdict.self }
        ListItem { Link { UpWord.self; EngineeringRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum EngineeringManagersVaultVerdict: Close {}
extension EngineeringManagersVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Engineering, Manager>, FinanceVault>.typeName }
}
enum EngineeringManagersRepoVerdict: Close {}
extension EngineeringManagersRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Engineering, Manager>, EngineeringRepo>.typeName }
}
enum EngineeringManagersCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<EngineeringManagers>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<EngineeringManagers>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; EngineeringManagersVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; EngineeringManagersRepoVerdict.self }
        ListItem { Link { UpWord.self; EngineeringRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum SalesIndividualContributorsVaultVerdict: Close {}
extension SalesIndividualContributorsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Sales, IndividualContributor>, FinanceVault>.typeName }
}
enum SalesIndividualContributorsRepoVerdict: Close {}
extension SalesIndividualContributorsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Sales, IndividualContributor>, EngineeringRepo>.typeName }
}
enum SalesIndividualContributorsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<SalesIndividualContributors>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<SalesIndividualContributors>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; SalesIndividualContributorsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; SalesIndividualContributorsRepoVerdict.self }
        ListItem { Link { UpWord.self; SalesRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum SalesLeadsVaultVerdict: Close {}
extension SalesLeadsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Sales, Lead>, FinanceVault>.typeName }
}
enum SalesLeadsRepoVerdict: Close {}
extension SalesLeadsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Sales, Lead>, EngineeringRepo>.typeName }
}
enum SalesLeadsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<SalesLeads>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<SalesLeads>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; SalesLeadsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; SalesLeadsRepoVerdict.self }
        ListItem { Link { UpWord.self; SalesRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum SalesManagersVaultVerdict: Close {}
extension SalesManagersVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Sales, Manager>, FinanceVault>.typeName }
}
enum SalesManagersRepoVerdict: Close {}
extension SalesManagersRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<Sales, Manager>, EngineeringRepo>.typeName }
}
enum SalesManagersCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<SalesManagers>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<SalesManagers>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; SalesManagersVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; SalesManagersRepoVerdict.self }
        ListItem { Link { UpWord.self; SalesRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum PeopleIndividualContributorsVaultVerdict: Close {}
extension PeopleIndividualContributorsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<People, IndividualContributor>, FinanceVault>.typeName }
}
enum PeopleIndividualContributorsRepoVerdict: Close {}
extension PeopleIndividualContributorsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<People, IndividualContributor>, EngineeringRepo>.typeName }
}
enum PeopleIndividualContributorsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<PeopleIndividualContributors>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<PeopleIndividualContributors>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; PeopleIndividualContributorsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; PeopleIndividualContributorsRepoVerdict.self }
        ListItem { Link { UpWord.self; PeopleRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum PeopleLeadsVaultVerdict: Close {}
extension PeopleLeadsVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<People, Lead>, FinanceVault>.typeName }
}
enum PeopleLeadsRepoVerdict: Close {}
extension PeopleLeadsRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<People, Lead>, EngineeringRepo>.typeName }
}
enum PeopleLeadsCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<PeopleLeads>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<PeopleLeads>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; PeopleLeadsVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; PeopleLeadsRepoVerdict.self }
        ListItem { Link { UpWord.self; PeopleRanks.self } }
        Break.self
    }
}

// The verdicts, read at a literal static site: a constrained extension does
// not enter the witness table, so the fold would read the base case (the
// same wall the person heroes' dot proxies stand behind).
enum PeopleManagersVaultVerdict: Close {}
extension PeopleManagersVaultVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<People, Manager>, FinanceVault>.typeName }
}
enum PeopleManagersRepoVerdict: Close {}
extension PeopleManagersRepoVerdict {
    static var typeName: String { ViewCapability<SomeoneAs<People, Manager>, EngineeringRepo>.typeName }
}
enum PeopleManagersCellPage: Screen {
    @StructureBuilder
    static var body: some Structure {
        PageTitle { Symbol { RawName<PeopleManagers>.self } }
        RoleCellIntro.self; Break.self
        ListItem { StandingHereWord.self; Tally<PeopleManagers>.self }
        ListItem { Symbol { RawName<FinanceVault>.self }; ViewColonWord.self; PeopleManagersVaultVerdict.self }
        ListItem { Symbol { RawName<EngineeringRepo>.self }; ViewColonWord.self; PeopleManagersRepoVerdict.self }
        ListItem { Link { UpWord.self; PeopleRanks.self } }
        Break.self
    }
}

func renderRoleWalk() {
    write(RoleWalkPage.typeName, "RoleWalk")
    write(MoneyOrBuildSidePage.typeName, "MoneyOrBuildSide")
    write(FinanceRanksPage.typeName, "FinanceRanks")
    write(FinanceLeadOrManagerPage.typeName, "FinanceLeadOrManager")
    write(EngineeringRanksPage.typeName, "EngineeringRanks")
    write(EngineeringLeadOrManagerPage.typeName, "EngineeringLeadOrManager")
    write(SalesOrPeopleSidePage.typeName, "SalesOrPeopleSide")
    write(SalesRanksPage.typeName, "SalesRanks")
    write(SalesLeadOrManagerPage.typeName, "SalesLeadOrManager")
    write(PeopleRanksPage.typeName, "PeopleRanks")
    write(PeopleLeadOrManagerPage.typeName, "PeopleLeadOrManager")
    write(FinanceIndividualContributorsCellPage.typeName, "FinanceIndividualContributors")
    write(FinanceLeadsCellPage.typeName, "FinanceLeads")
    write(FinanceManagersCellPage.typeName, "FinanceManagers")
    write(EngineeringIndividualContributorsCellPage.typeName, "EngineeringIndividualContributors")
    write(EngineeringLeadsCellPage.typeName, "EngineeringLeads")
    write(EngineeringManagersCellPage.typeName, "EngineeringManagers")
    write(SalesIndividualContributorsCellPage.typeName, "SalesIndividualContributors")
    write(SalesLeadsCellPage.typeName, "SalesLeads")
    write(SalesManagersCellPage.typeName, "SalesManagers")
    write(PeopleIndividualContributorsCellPage.typeName, "PeopleIndividualContributors")
    write(PeopleLeadsCellPage.typeName, "PeopleLeads")
    write(PeopleManagersCellPage.typeName, "PeopleManagers")
}
