import Alphabet
import VerificationIsIdentification

// ═══════════════════════════════════════════════════════════════
// LANDING is DocumentKit's own module page, generated by the engine it documents. Reading
// `Landing.typeName` (`DocumentKitDemo/main.swift` writes it to `DocumentKit.docc/
// DocumentKit.md`, the module's doc-extension, title `` ``DocumentKit`` ``, merged onto
// the auto-generated module stub, never a second address) renders the intro prose, the mechanism
// reference, AND the gallery: one page, one build, no hand-authored duplicate kept in step by
// hand. Every gallery example below is a REAL composition, not a description of one. Reading
// this file's output is reading what the engine actually does.
//
// A category marker, local to this file: DocumentKit itself has no `Screen`/`Fragment`
// (those are Organization's naming, not the engine's: `Sources/Organization/View/
// Screen.swift`). `DocumentKit` depends on nothing, so it does not borrow them.
//
// Three attempts at a drawn, two-axis border (a table of pixel images, a text-drawn box, a
// wider table with an extra "island" column) were tried here and removed, kept only in
// SurfaceLaw §S15/§S19/§S20 as the record of why. All three tried to fake a second axis this
// render target does not have (no row-height primitive, GFM has no cell merging), and one
// depended on a monospace font this viewer does not guarantee. The one mechanism that survived
// every check is TEXT flowing on its default (`Gap`/`SpaceBetween`, below), so that is
// where the real richness lives now: not a drawn shape, a RULE TABLE.
// ═══════════════════════════════════════════════════════════════

public protocol GallerySection: Open {}

/// This names the two labels every section repeats: a real call site (`Used like this:`), then
/// what it renders to (`Comes out like this:`), so a reader always knows which is which.
enum UsedLikeThisLabel: Close {}
extension UsedLikeThisLabel {
    static var typeName: String { "Used like this:" }
}
enum ComesOutLikeThisLabel: Close {}
extension ComesOutLikeThisLabel {
    static var typeName: String { "Comes out like this:" }
}

/// This stands in as a link target: `Gallery.self` would read `Gallery.typeName`, which reads
/// `Body.typeName`, which contains the very link reading `Gallery.typeName` again, infinite
/// recursion at the first render (checked directly, the same circularity `AliceUnlocked` avoids
/// by pointing at `SecretPage<...>` instead of itself). A real page would name a real other
/// page. This names an inert leaf, to demonstrate the syntax without depending on one existing.
/// No `typeName` override: `Close`'s inherited default (`Structure`'s, `String(describing:
/// Self.self)`) already reads "ExampleTarget," its real Swift name, so a demo link actually
/// resolves to this (empty, auto-generated) symbol page instead of dangling on a fictional one.
public enum ExampleTarget: Close {}

/// The one asset this file's `Picture` example embeds (Resources/example.svg).
enum ExampleAsset: Close {}
extension ExampleAsset {
    static var typeName: String { "example" }
}

// ── The module title — `` ``DocumentKit`` `` (double-backtick, wrapped through `Symbol` the
// same way `SymbolExample` wraps `ExampleTarget`), the literal text DocC needs to treat this
// page as the module's own landing, a doc-extension merged onto the auto-generated stub. ──

enum ModuleTitleTarget: Close {}
extension ModuleTitleTarget {
    static var typeName: String { "DocumentKit" }
}

// ── Intro — unchanged from the page this replaces. ──

enum LandingIntro: Close {}
extension LandingIntro {
    static var typeName: String {
        "A render engine with no runtime. A page is a type: its `body` composes other types, and reading `typeName` (`Structure`, VerificationIsIdentification) walks the composition once into markdown. There is no second pass and no node tree to interpret — the type is the page, and reading its name is the render."
    }
}

// ── Build a page — new: the five-step method this whole file is itself an instance of. ──

enum BuildAPageHeading: Close {}
extension BuildAPageHeading {
    static var typeName: String { "Build a page" }
}

enum BuildAPageIntro: Close {}
extension BuildAPageIntro {
    static var typeName: String {
        "A page is built the way everything else in this package is built: declare a type, compose its body, read the name."
    }
}

enum BuildAPageStep1: Close {}
extension BuildAPageStep1 {
    static var typeName: String {
        "1. **Declare the screen.** `enum MyPage: Screen {}` — a caseless enum, like every concrete type on the surface (SurfaceLaw §S2). `Screen` is your app's own page kind, one line — `public protocol Screen: Open {}` — declared beside your pages, the way the Organization showcase declares its own. There is nothing to instantiate: the page is the type."
    }
}
enum BuildAPageStep2: Close {}
extension BuildAPageStep2 {
    static var typeName: String {
        "2. **Compose the body.** `@StructureBuilder static var body: some Structure { … }` — statements fold into a `Pair`-cons chain. Every leaf is an atom or another combinator: a name enters through `Symbol`, a count through `Tally`, prose through a prose atom — a type whose `typeName` is the sentence. Organization spells its prose from a JSON manifest through a build plugin. This page carries its own."
    }
}
enum BuildAPageStep3: Close {}
extension BuildAPageStep3 {
    static var typeName: String {
        "3. **Compile.** Type-checking the body is the render happening: a table missing its header rule, a tab out of place, a count that does not fold — each is a build error, not a bad page."
    }
}
enum BuildAPageStep4: Close {}
extension BuildAPageStep4 {
    static var typeName: String {
        "4. **Read it.** `MyPage.typeName` is the markdown. A demo executable writes it into the `.docc` catalog, so a `doc:` link resolves to this content instead of an empty auto-generated stub — that is the whole publishing pipeline."
    }
}
enum BuildAPageStep5: Close {}
extension BuildAPageStep5 {
    static var typeName: String {
        "5. **Curate it.** Add the page to the landing's Topics so it hangs where readers look, not at the navigator's root."
    }
}

// ── Two kinds of combinator — unchanged except the one sentence that used to point at the
// separate Gallery page: the gallery is now further down THIS page. ──

enum TwoKindsHeading: Close {}
extension TwoKindsHeading {
    static var typeName: String { "Two kinds of combinator" }
}

enum TwoKindsIntro: Close {}
extension TwoKindsIntro {
    static var typeName: String {
        "Every combinator on the surface is an `Open` protocol carrying the hole (an `associatedtype`) plus the composition that reads it (`body`), realized by a caseless `enum` — never the reverse. A one-hole combinator's `{ }` door (`init`) lives on the protocol extension, shared by every conformer. A combinator with more than one hole (``Link``, ``Picture``, ``SizedPanel``) folds its statements through a single `Whole: Pair` parameter instead, the door living on the concrete enum. The gallery further down this page is a live instance of every shape below, rendered by the engine it exercises — reading it is reading what each row actually produces, not a description of it."
    }
}

enum CombinatorHeader: Close {}
extension CombinatorHeader {
    static var typeName: String { "Combinator" }
}
enum IsHeader: Close {}
extension IsHeader {
    static var typeName: String { "Is" }
}

enum Row1Combinator: Close {}
extension Row1Combinator {
    static var typeName: String { "``Symbol``" }
}
enum Row1Is: Close {}
extension Row1Is {
    static var typeName: String { "`Target` — a symbol link, the type's own name in backticks" }
}

enum Row2Combinator: Close {}
extension Row2Combinator {
    static var typeName: String { "``Page``" }
}
enum Row2Is: Close {}
extension Row2Is {
    static var typeName: String { "`<doc:Target>` — a link to a page, named by its own identity" }
}

enum Row3Combinator: Close {}
extension Row3Combinator {
    static var typeName: String { "``Link``" }
}
enum Row3Is: Close {}
extension Row3Is {
    static var typeName: String { "`[Label](doc:Target)` — a link whose display text is chosen" }
}

enum Row4Combinator: Close {}
extension Row4Combinator {
    static var typeName: String { "``Picture``" }
}
enum Row4Is: Close {}
extension Row4Is {
    static var typeName: String { "`![Alt](Asset)` — an image embedded in the body, not a link-grid tile" }
}

enum Row5Combinator: Close {}
extension Row5Combinator {
    static var typeName: String { "``Framed``" }
}
enum Row5Is: Close {}
extension Row5Is {
    static var typeName: String { "the same content in a one-cell table — a border, for free, from `Table` alone" }
}

enum Row6Combinator: Close {}
extension Row6Combinator {
    static var typeName: String { "``Table``, ``TableRow``, ``TableCell``" }
}
enum Row6Is: Close {}
extension Row6Is {
    static var typeName: String { "a table — rows of cells, a Pair-cons never an array. `RuleMark` is the header delimiter every table needs to be a table at all" }
}

enum Row7Combinator: Close {}
extension Row7Combinator {
    static var typeName: String { "``ListItem``" }
}
enum Row7Is: Close {}
extension Row7Is {
    static var typeName: String { "one list line" }
}

enum Row8Combinator: Close {}
extension Row8Combinator {
    static var typeName: String { "``Noted``, ``Flagged``, ``Warned``, ``Tipped``" }
}
enum Row8Is: Close {}
extension Row8Is {
    static var typeName: String { "a coloured aside — Note, Important, Warning, Tip" }
}

enum Row9Combinator: Close {}
extension Row9Combinator {
    static var typeName: String { "``TabGroup``" }
}
enum Row9Is: Close {}
extension Row9Is {
    static var typeName: String { "DocC `@TabNavigator`" }
}

enum Row10Combinator: Close {}
extension Row10Combinator {
    static var typeName: String { "``SideBySide``, ``PanelOf``" }
}
enum Row10Is: Close {}
extension Row10Is {
    static var typeName: String { "DocC `@Row`/`@Column`, equal width" }
}

enum Row11Combinator: Close {}
extension Row11Combinator {
    static var typeName: String { "``SizedPanel``" }
}
enum Row11Is: Close {}
extension Row11Is {
    static var typeName: String { "`@Column(size: N)` — a relative weight read off the same magnitude lexicon the vector surface weighs (`WeightOf<U2>` reads 2), never a computed value; the one real foothold this render target has for layout, not a general solver (there is no markdown primitive for an absolute width to land in)" }
}

enum Row12Combinator: Close {}
extension Row12Combinator {
    static var typeName: String { "`Tally`" }
}
enum Row12Is: Close {}
extension Row12Is {
    static var typeName: String { "a `Structure`'s `count`, read as digits — not typed in, folded as the compiler builds" }
}

enum CombinatorTableHeaderRow: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TableCell { CombinatorHeader.self }; TableCell { IsHeader.self }
    }
}
enum CombinatorTableRule: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TableCell { RuleMark.self }; TableCell { RuleMark.self }
    }
}
enum CombinatorTableRows: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TableRow { CombinatorTableHeaderRow.self }
        TableRow { CombinatorTableRule.self }
        TableRow { TableCell { Row1Combinator.self }; TableCell { Row1Is.self } }
        TableRow { TableCell { Row2Combinator.self }; TableCell { Row2Is.self } }
        TableRow { TableCell { Row3Combinator.self }; TableCell { Row3Is.self } }
        TableRow { TableCell { Row4Combinator.self }; TableCell { Row4Is.self } }
        TableRow { TableCell { Row5Combinator.self }; TableCell { Row5Is.self } }
        TableRow { TableCell { Row6Combinator.self }; TableCell { Row6Is.self } }
        TableRow { TableCell { Row7Combinator.self }; TableCell { Row7Is.self } }
        TableRow { TableCell { Row8Combinator.self }; TableCell { Row8Is.self } }
        TableRow { TableCell { Row9Combinator.self }; TableCell { Row9Is.self } }
        TableRow { TableCell { Row10Combinator.self }; TableCell { Row10Is.self } }
        TableRow { TableCell { Row11Combinator.self }; TableCell { Row11Is.self } }
        TableRow { TableCell { Row12Combinator.self }; TableCell { Row12Is.self } }
    }
}

// ── The one rendering path — unchanged, except the same stray link the section above already
// dropped: the old sentence ended by pointing at the gallery's own former, separate page; the
// gallery is now this same page's own last section, so the close reads "gallery included"
// instead, a self-reference rather than a link out. ──

enum RenderingPathHeading: Close {}
extension RenderingPathHeading {
    static var typeName: String { "The one rendering path" }
}

enum RenderingPathIntro: Close {}
extension RenderingPathIntro {
    static var typeName: String {
        "`typeName` (`Structure`) is the whole engine: an atom (`Close`) overrides it to its own character; a combinator's default reads `Body.typeName`, recursing through whatever `body` composed. `DocumentKit` depends only on `VerificationIsIdentification` — the same mechanism draws the Organization showcase and this page, gallery included."
    }
}

enum RenderingPathWarning: Close {}
extension RenderingPathWarning {
    static var typeName: String {
        "`typeName`'s walk concatenates strings on the way back up the tree (`Paired.typeName = L.typeName + R.typeName`), so it is not tail-recursive — one `Structure` with enough total content in its own `body` can exhaust the call stack before it ever mis-renders (checked directly). Prefer several linked pages over one page trying to hold everything, the same choice Organization's showcase already makes."
    }
}

// ── The gallery itself, folded into this page as its last section — every heading below drops
// one level (`###`, not `##`) to nest under it. ──

enum GallerySectionHeading: Close {}
extension GallerySectionHeading {
    static var typeName: String { "The gallery — every mechanism, live" }
}

enum GallerySectionIntro: Close {}
extension GallerySectionIntro {
    static var typeName: String {
        "Each mechanism below is shown three ways: the code that composes it, the markdown it renders to, and the render itself — produced by this page's own build."
    }
}

// ── Symbol ──

enum SymbolCaption: Close {}
extension SymbolCaption {
    static var typeName: String {
        "`Symbol` renders a type's own Swift name in double backticks, the same shape a doc comment uses to link a real symbol. Below, a stand-in type renders as its identifier."
    }
}

enum SymbolExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Symbol { ExampleTarget.self }
    }
}

/// This mirrors `SymbolExample.body` above, by hand (`CodeFence`'s warning), kept adjacent so
/// an edit to one is an edit a reader sees right next to the other.
enum SymbolCode: Close {}
extension SymbolCode {
    static var typeName: String { "Symbol { ExampleTarget.self }" }
}

// ── Page / Link — Page names a target by its own name; Link chooses the display text. ──

enum PageCaption: Close {}
extension PageCaption {
    static var typeName: String {
        "`Page` links to another page by that page's own name — no separate title to keep in sync."
    }
}

enum PageExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Page { ExampleTarget.self }
    }
}

enum PageCode: Close {}
extension PageCode {
    static var typeName: String { "Page { ExampleTarget.self }" }
}

enum LinkLabel: Close {}
extension LinkLabel {
    static var typeName: String { "a chosen label" }
}

enum LinkCaption: Close {}
extension LinkCaption {
    static var typeName: String {
        "`Link` is the same link, with a chosen display text instead of the target's raw name."
    }
}

enum LinkExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Link { LinkLabel.self; ExampleTarget.self }
    }
}

enum LinkCode: Close {}
extension LinkCode {
    static var typeName: String { "Link { LinkLabel.self; ExampleTarget.self }" }
}

// ── Picture — embedded IN the body, distinct from `@PageImage` (a link-grid tile only). ──

enum PictureCaption: Close {}
extension PictureCaption {
    static var typeName: String {
        "`Picture` embeds an image inside the page's content, not only as a link-grid thumbnail."
    }
}

enum PictureExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Picture { Symbol { ExampleTarget.self }; ExampleAsset.self }
    }
}

enum PictureCode: Close {}
extension PictureCode {
    static var typeName: String { "Picture { Symbol { ExampleTarget.self }; ExampleAsset.self }" }
}

// ── Framed — the SAME picture, in a one-cell table. Reads left-aligned, not ringed (checked
// directly — a table cell's own styling does not draw a visible border here); kept as the
// honest version of "put something in a table," not as a border technique. ──

enum FramedCaption: Close {}
extension FramedCaption {
    static var typeName: String {
        "`Framed` places content inside a one-cell table. It renders as plain left-aligned content — DocC does not draw a ring around a table cell, so this is a table, not a border."
    }
}

enum FramedExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Framed { Picture { Symbol { ExampleTarget.self }; ExampleAsset.self } }
    }
}

enum FramedCode: Close {}
extension FramedCode {
    static var typeName: String { "Framed { Picture { Symbol { ExampleTarget.self }; ExampleAsset.self } }" }
}

// ── Spacer — flanking real content with two of these gives horizontal padding: an inserted
// object that only holds width, the cheapest read of "insert something that just holds space." ──

enum SpacerCaption: Close {}
extension SpacerCaption {
    static var typeName: String {
        "`Spacer` is a column holding only width, no content. Two of them, flanking real content, pad it horizontally."
    }
}

enum SpacerExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        SideBySide {
            Spacer<WeightOf<U1>>.self
            PanelOf { Symbol { ExampleTarget.self } }
            Spacer<WeightOf<U1>>.self
        }
    }
}

enum SpacerCode: Close {}
extension SpacerCode {
    static var typeName: String {
        """
        SideBySide {
            Spacer<WeightOf<U1>>.self
            PanelOf { Symbol { ExampleTarget.self } }
            Spacer<WeightOf<U1>>.self
        }
        """
    }
}

// ── Gap — a RULE TABLE, not one pair. The space between two workflow states is not stored on
// either state — it is read off WHICH TWO are adjacent, the same conditional-conformance shape
// `View`/`Administer`/`Delete` (Organization/System/Policy.swift) already use for access,
// applied here to a business rule instead: an expected step gets a plain arrow, a step that
// skips or backslides gets a named, wider gap. Five rules, five literal call sites (`Gap`'s own
// warning, Markup.swift, and §S17 — each proxy resolves its OWN pairing, once, with nothing
// generic in between) — the mechanism does not care whether it is asked to model two states or
// five; the richness is in how large a rule table you are willing to write by hand. ──

enum ToDo: Close {}
extension ToDo {
    static var typeName: String { "ToDo" }
}
enum Doing: Close {}
extension Doing {
    static var typeName: String { "Doing" }
}
enum Done: Close {}
extension Done {
    static var typeName: String { "Done" }
}
enum Blocked: Close {}
extension Blocked {
    static var typeName: String { "Blocked" }
}

// Expected steps: a plain arrow, nothing to flag.
extension SpaceBetween
where Left == ToDo, Right == Doing {
    static var typeName: String { " -> " }
}
extension SpaceBetween
where Left == Doing, Right == Done {
    static var typeName: String { " -> " }
}
extension SpaceBetween
where Left == Blocked, Right == Doing {
    static var typeName: String { " -> resumed -> " }
}
// Exceptional steps: a wider, named gap. The space itself carries the flag, not a property on
// either state.
extension SpaceBetween
where Left == ToDo, Right == Done {
    static var typeName: String { "  ⚠ skipped review ⚠  " }
}
extension SpaceBetween
where Left == Doing, Right == Blocked {
    static var typeName: String { "  ⚠ needs attention ⚠  " }
}

enum NormalToDoDoing: Close {}
extension NormalToDoDoing {
    static var typeName: String {
        SpaceBetween<
            ToDo,
            Doing
        >.typeName
    }
}
enum NormalDoingDone: Close {}
extension NormalDoingDone {
    static var typeName: String {
        SpaceBetween<
            Doing,
            Done
        >.typeName
    }
}
enum ResumedBlockedDoing: Close {}
extension ResumedBlockedDoing {
    static var typeName: String {
        SpaceBetween<
            Blocked,
            Doing
        >.typeName
    }
}
enum SkippedToDoDone: Close {}
extension SkippedToDoDone {
    static var typeName: String {
        SpaceBetween<
            ToDo,
            Done
        >.typeName
    }
}
enum FlaggedDoingBlocked: Close {}
extension FlaggedDoingBlocked {
    static var typeName: String {
        SpaceBetween<
            Doing,
            Blocked
        >.typeName
    }
}

enum GapCaption: Close {}
extension GapCaption {
    static var typeName: String {
        "A gap belongs to which two states are adjacent, not to either state alone. Below, five workflow transitions: an expected step gets a plain arrow, a step that skips or backslides gets a named, wider gap."
    }
}

enum GapExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        ToDo.self; NormalToDoDoing.self; Doing.self
        Break.self
        Doing.self; NormalDoingDone.self; Done.self
        Break.self
        Blocked.self; ResumedBlockedDoing.self; Doing.self
        Break.self
        ToDo.self; SkippedToDoDone.self; Done.self
        Break.self
        Doing.self; FlaggedDoingBlocked.self; Blocked.self
    }
}

enum GapCode: Close {}
extension GapCode {
    static var typeName: String {
        """
        // the rule lives on the SPACE, stated once per pairing:
        extension SpaceBetween where Left == ToDo, Right == Doing {
            static var typeName: String { " -> " }
        }
        extension SpaceBetween where Left == ToDo, Right == Done {
            static var typeName: String { "  ⚠ skipped review ⚠  " }
        }

        // read through a non-generic proxy (Surface Law §S17), once per pairing:
        enum NormalToDoDoing: Close {}
        extension NormalToDoDoing {
            static var typeName: String { SpaceBetween<ToDo, Doing>.typeName }
        }

        // used in a body:
        ToDo.self; NormalToDoDoing.self; Doing.self
        """
    }
}

// ── SpacerBetween — the same rule table, rendering a real `@Column(size:)` weight instead of
// text: the gap next to `Loud` is wider than the gap between two `Quiet`s. Two rows, same
// shape, different weight — the behavior lives in which two things are adjacent, never in a
// property either one carries. ──

enum Quiet: Close {}
extension Quiet {
    static var typeName: String { "quiet" }
}
enum Loud: Close {}
extension Loud {
    static var typeName: String { "LOUD" }
}

extension SpacerBetween
where Left == Quiet, Right == Loud {
    static var typeName: String { Spacer<WeightOf<Plus<U2, U1>>>.typeName }
}

enum WideGapQuietLoud: Close {}
extension WideGapQuietLoud {
    static var typeName: String {
        SpacerBetween<
            Quiet,
            Loud
        >.typeName
    }
}
enum ThinGapQuietQuiet: Close {}
extension ThinGapQuietQuiet {
    static var typeName: String {
        SpacerBetween<
            Quiet,
            Quiet
        >.typeName
    }
}

enum SpacerBetweenCaption: Close {}
extension SpacerBetweenCaption {
    static var typeName: String {
        "The same rule, rendering a real column width instead of text: the gap beside a LOUD neighbor is wider than the gap between two quiet neighbors."
    }
}

enum SpacerBetweenExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        SideBySide {
            PanelOf { Quiet.self }
            WideGapQuietLoud.self
            PanelOf { Loud.self }
        }
        SideBySide {
            PanelOf { Quiet.self }
            ThinGapQuietQuiet.self
            PanelOf { Quiet.self }
        }
    }
}

enum SpacerBetweenCode: Close {}
extension SpacerBetweenCode {
    static var typeName: String {
        """
        extension SpacerBetween where Left == Quiet, Right == Loud {
            static var typeName: String { Spacer<WeightOf<Plus<U2, U1>>>.typeName }
        }

        enum WideGapQuietLoud: Close {}
        extension WideGapQuietLoud {
            static var typeName: String { SpacerBetween<Quiet, Loud>.typeName }
        }

        // used in a body:
        SideBySide {
            PanelOf { Quiet.self }
            WideGapQuietLoud.self
            PanelOf { Loud.self }
        }
        """
    }
}

// ── Table — TableRow/TableCell, with the header's own delimiter row (RuleMark): without it,
// this is not a table at all, just a paragraph with pipes in it (checked directly). ──

enum FieldHeading: Close {}
extension FieldHeading {
    static var typeName: String { "Field" }
}
enum ValueHeading: Close {}
extension ValueHeading {
    static var typeName: String { "Value" }
}
enum EngineFieldName: Close {}
extension EngineFieldName {
    static var typeName: String { "Engine" }
}
enum EngineFieldValue: Close {}
extension EngineFieldValue {
    static var typeName: String { "DocumentKit" }
}

enum TableCaption: Close {}
extension TableCaption {
    static var typeName: String { "A header row, its required delimiter row, then data." }
}

enum TableExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Table {
            TableRow { TableCell { FieldHeading.self }; TableCell { ValueHeading.self } }
            TableRow { TableCell { RuleMark.self }; TableCell { RuleMark.self } }
            TableRow { TableCell { EngineFieldName.self }; TableCell { EngineFieldValue.self } }
        }
    }
}

enum TableCode: Close {}
extension TableCode {
    static var typeName: String {
        """
        Table {
            TableRow { TableCell { FieldHeading.self }; TableCell { ValueHeading.self } }
            TableRow { TableCell { RuleMark.self }; TableCell { RuleMark.self } }
            TableRow { TableCell { EngineFieldName.self }; TableCell { EngineFieldValue.self } }
        }
        """
    }
}

// ── List ──

enum ListItemOne: Close {}
extension ListItemOne {
    static var typeName: String { "a body is a type" }
}
enum ListItemTwo: Close {}
extension ListItemTwo {
    static var typeName: String { "typeName walks it once" }
}

enum ListCaption: Close {}
extension ListCaption {
    static var typeName: String { "A bullet list, one item per line." }
}

enum ListExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        ListItem { ListItemOne.self }
        ListItem { ListItemTwo.self }
    }
}

enum ListCode: Close {}
extension ListCode {
    static var typeName: String {
        """
        ListItem { ListItemOne.self }
        ListItem { ListItemTwo.self }
        """
    }
}

// ── Callouts — Note, Important, Warning, Tip: the same shape, four labels. ──

enum CalloutMessage: Close {}
extension CalloutMessage {
    static var typeName: String { "the same combinator, four labels" }
}

enum CalloutsCaption: Close {}
extension CalloutsCaption {
    static var typeName: String { "The same box, four labels: Note, Important, Warning, Tip." }
}

enum NoteExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Noted { CalloutMessage.self }
    }
}
enum ImportantExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Flagged { CalloutMessage.self }
    }
}
enum WarningExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Warned { CalloutMessage.self }
    }
}
enum TipExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Tipped { CalloutMessage.self }
    }
}

enum CalloutsCode: Close {}
extension CalloutsCode {
    static var typeName: String {
        """
        Noted { CalloutMessage.self }
        Flagged { CalloutMessage.self }
        Warned { CalloutMessage.self }
        Tipped { CalloutMessage.self }
        """
    }
}

// ── Tabs ──

enum FirstTabLabel: Close {}
extension FirstTabLabel {
    static var typeName: String { "One" }
}
enum SecondTabLabel: Close {}
extension SecondTabLabel {
    static var typeName: String { "Two" }
}
enum FirstTabBody: Close {}
extension FirstTabBody {
    static var typeName: String { "the first tab's content" }
}
enum SecondTabBody: Close {}
extension SecondTabBody {
    static var typeName: String { "the second tab's content" }
}

enum TabsCaption: Close {}
extension TabsCaption {
    static var typeName: String { "Two panes, selectable at read time." }
}

enum TabsInner: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        At.self; TabLabel.self; ParenOpen.self; Quote.self; FirstTabLabel.self; Quote.self; ParenClose.self; OpenBrace.self
        FirstTabBody.self
        Newline.self
        CloseBrace.self
        At.self; TabLabel.self; ParenOpen.self; Quote.self; SecondTabLabel.self; Quote.self; ParenClose.self; OpenBrace.self
        SecondTabBody.self
        Newline.self
        CloseBrace.self
    }
}
enum TabsExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TabGroup { TabsInner.self }
    }
}

enum TabsCode: Close {}
extension TabsCode {
    static var typeName: String {
        """
        // no `@Tab` combinator yet: DocC requires the parenthesized form, so the atoms are
        // written directly, the same call `Section` above makes:
        TabGroup {
            At.self; TabLabel.self; ParenOpen.self; Quote.self; FirstTabLabel.self; Quote.self; ParenClose.self; OpenBrace.self
            FirstTabBody.self
            Newline.self
            CloseBrace.self
            At.self; TabLabel.self; ParenOpen.self; Quote.self; SecondTabLabel.self; Quote.self; ParenClose.self; OpenBrace.self
            SecondTabBody.self
            Newline.self
            CloseBrace.self
        }
        """
    }
}

// ── Columns — SideBySide + PanelOf, unweighted: equal width, side by side. ──

enum LeftPanelBody: Close {}
extension LeftPanelBody {
    static var typeName: String { "left" }
}
enum RightPanelBody: Close {}
extension RightPanelBody {
    static var typeName: String { "right" }
}

enum ColumnsCaption: Close {}
extension ColumnsCaption {
    static var typeName: String { "Two panels, side by side, equal width." }
}

enum ColumnsExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        SideBySide {
            PanelOf { LeftPanelBody.self }
            PanelOf { RightPanelBody.self }
        }
    }
}

enum ColumnsCode: Close {}
extension ColumnsCode {
    static var typeName: String {
        """
        SideBySide {
            PanelOf { LeftPanelBody.self }
            PanelOf { RightPanelBody.self }
        }
        """
    }
}

// ── SizedPanel — the weight reads the shared magnitude lexicon (`WeightOf<U2>`): a 1:2 split.
// `Block` ("█", repeated by hand) makes the ratio visible through TEXT flow, the one thing
// already proven to render the same everywhere (§S19/§S20) — one square per unit of weight. ──

enum Block: Close {}
extension Block {
    static var typeName: String { "█" }
}

enum Bar1: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Block.self
    }
}
enum Bar2: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Block.self
        Block.self
    }
}

enum SizedPanelCaption: Close {}
extension SizedPanelCaption {
    static var typeName: String {
        "Two panels at a stated 1:2 ratio. The ratio renders here as repeated `█` blocks — column width itself does not visibly change in this renderer."
    }
}

enum SizedPanelExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        SideBySide {
            SizedPanel { Bar1.self; WeightOf<U1>.self }
            SizedPanel { Bar2.self; WeightOf<U2>.self }
        }
    }
}

enum SizedPanelCode: Close {}
extension SizedPanelCode {
    static var typeName: String {
        """
        SideBySide {
            SizedPanel { Bar1.self; WeightOf<U1>.self }
            SizedPanel { Bar2.self; WeightOf<U2>.self }
        }
        """
    }
}

// ── Tally — a Structure's `count`, read as digits: not typed in, folded as the compiler builds. ──

enum CountedTriple: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Letter.a.self; Letter.b.self; Letter.c.self
    }
}

enum TallyCaption: Close {}
extension TallyCaption {
    static var typeName: String { "A type's own count, read off as digits — never typed in by hand." }
}

enum TallyExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Tally { CountedTriple.self }
    }
}

enum TallyCode: Close {}
extension TallyCode {
    static var typeName: String { "Tally { CountedTriple.self }" }
}

// ── The whole gallery, one page — a doc-extension on its own symbol (no second address needed:
// there is only ever one state to show), the same call Organization's `EmployeeCard` makes. ──

enum SymbolHeading: Close {}
extension SymbolHeading {
    static var typeName: String { "Symbol" }
}
enum PageHeading: Close {}
extension PageHeading {
    static var typeName: String { "Page" }
}
enum LinkHeading: Close {}
extension LinkHeading {
    static var typeName: String { "Link" }
}
enum PictureHeading: Close {}
extension PictureHeading {
    static var typeName: String { "Picture" }
}
enum FramedHeading: Close {}
extension FramedHeading {
    static var typeName: String { "Framed" }
}
enum SpacerHeading: Close {}
extension SpacerHeading {
    static var typeName: String { "Spacer" }
}
enum GapHeading: Close {}
extension GapHeading {
    static var typeName: String { "Gap — a rule table" }
}
enum SpacerBetweenHeading: Close {}
extension SpacerBetweenHeading {
    static var typeName: String { "Spacer, chosen by neighbor" }
}
enum TableHeading: Close {}
extension TableHeading {
    static var typeName: String { "Table" }
}
enum ListHeading: Close {}
extension ListHeading {
    static var typeName: String { "List" }
}
enum CalloutsHeading: Close {}
extension CalloutsHeading {
    static var typeName: String { "Callouts" }
}
enum TabsHeading: Close {}
extension TabsHeading {
    static var typeName: String { "Tabs" }
}
enum ColumnsHeading: Close {}
extension ColumnsHeading {
    static var typeName: String { "Columns" }
}
enum SizedPanelHeading: Close {}
extension SizedPanelHeading {
    static var typeName: String { "Weighted columns" }
}
enum TallyHeading: Close {}
extension TallyHeading {
    static var typeName: String { "Tally" }
}

// ══════════════════════════════════════════════════════════════════════════════
// THE SECOND MEDIUM: VECTOR. `Vector.swift`'s SVG mechanism, documented on
// THIS page the same way the markdown gallery above documents itself: every prose block below
// quotes or closely follows that file's own header comments (the canvas contract, the gate
// tiers), and the two examples at the end are REAL `Diagram` compositions (`VectorCanvasExample
// Diagram`/`VectorHoverExampleDiagram` below) read straight into an actual SVG file
// (`DocumentKitDemo/main.swift` writes them), not a description of one.
// ══════════════════════════════════════════════════════════════════════════════

enum VectorSectionHeading: Close {}
extension VectorSectionHeading {
    static var typeName: String { "The second medium: Vector" }
}

enum VectorSectionIntro: Close {}
extension VectorSectionIntro {
    static var typeName: String {
        "The gallery above is markdown, DocC's own document medium. `Vector` is DocumentKit's second: SVG, read by the identical mechanism — an atom is a `Close` reading its own `typeName`, a combinator is an `Open` protocol whose `body` composes atoms. A `viewBox` fixes the coordinate system, so embedding the result as an `<img>` scales both axes together, deterministically. Both examples at the end of this section are real compositions, generating their own drawing, the same way every markdown example above generates its own text."
    }
}

enum CanvasContractHeading: Close {}
extension CanvasContractHeading {
    static var typeName: String { "The canvas contract" }
}

enum CanvasContractGuaranteed: Close {}
extension CanvasContractGuaranteed {
    static var typeName: String {
        "**Guaranteed.** A canvas fixes its own coordinate space: `viewBox` W×H is a pixel grid that belongs to the composition. Inside it, placement is absolute (`Placed`), and the host cannot reach in — no margin, no centering, no theme rule moves anything within the `viewBox`. The host may scale the canvas only as a whole, uniformly: the aspect is preserved, so a known width fixes the height. Nothing drifts."
    }
}
enum CanvasContractNotGuaranteed: Close {}
extension CanvasContractNotGuaranteed {
    static var typeName: String {
        "**Not guaranteed.** The absolute on-screen size: markdown offers no pixel pin, so the canvas renders at container width — the right shape always, the exact screen pixels never promised. Text metrics: glyph width is the platform font's. The craft is a fixed font family and generous boxes — state the box, never compute the fit."
    }
}

// ── Roles and themes ──

enum RolesHeading: Close {}
extension RolesHeading {
    static var typeName: String { "Roles and themes" }
}

enum RolesIntro: Close {}
extension RolesIntro {
    static var typeName: String {
        "Light and dark are two projections of the same eight roles, each declared once, carrying both a light and a dark value. A role reaches a canvas by whichever of two mechanisms fits that canvas's own use: inline canvases (anything the inline-swap hook, `footer.html`, turns into real DOM) read a role as `var(--vi-<role>, <light-hex>)`, switched live by `prefers-color-scheme`, with a light fallback that still reads correctly even with no CSS in scope at all — a bare `<img>`. The small, numerous, non-interactive grid tiles use the other mechanism instead: a second, literal `x~dark.svg` file beside `x.svg`, DocC's own native asset-swap. Both read the same eight roles. Only where a role's value lands differs, and that choice is the canvas's own, made once, at the driver's edge. One rule holds regardless of mechanism: a canvas's ground is transparent, so text never floats — every label sits on a surface role (card, track, chip), never directly on the transparent ground, because a floating label is only legible on the one host theme its fallback hex happens to match."
    }
}

enum RoleHeader: Close {}
extension RoleHeader {
    static var typeName: String { "Role" }
}
enum WhatItIsHeader: Close {}
extension WhatItIsHeader {
    static var typeName: String { "What it is" }
}

enum RoleRow1Role: Close {}
extension RoleRow1Role {
    static var typeName: String { "`SurfaceCard`" }
}
enum RoleRow1Is: Close {}
extension RoleRow1Is {
    static var typeName: String { "a card's own background" }
}

enum RoleRow2Role: Close {}
extension RoleRow2Role {
    static var typeName: String { "`SurfaceTrack`" }
}
enum RoleRow2Is: Close {}
extension RoleRow2Is {
    static var typeName: String { "a track or chip's own background" }
}

enum RoleRow3Role: Close {}
extension RoleRow3Role {
    static var typeName: String { "`TextPrimary`" }
}
enum RoleRow3Is: Close {}
extension RoleRow3Is {
    static var typeName: String { "primary text, on either surface above" }
}

enum RoleRow4Role: Close {}
extension RoleRow4Role {
    static var typeName: String { "`TextSecondary`" }
}
enum RoleRow4Is: Close {}
extension RoleRow4Is {
    static var typeName: String { "secondary text, on either surface above" }
}

enum RoleRow5Role: Close {}
extension RoleRow5Role {
    static var typeName: String { "`AccentRole`" }
}
enum RoleRow5Is: Close {}
extension RoleRow5Is {
    static var typeName: String { "the one scarce accent — a hero element per screen, never wallpaper" }
}

enum RoleRow6Role: Close {}
extension RoleRow6Role {
    static var typeName: String { "`OnAccent`" }
}
enum RoleRow6Is: Close {}
extension RoleRow6Is {
    static var typeName: String { "text legible against `AccentRole`" }
}

enum RoleRow7Role: Close {}
extension RoleRow7Role {
    static var typeName: String { "`ActionRole`" }
}
enum RoleRow7Is: Close {}
extension RoleRow7Is {
    static var typeName: String { "the interactive voice — links, live values" }
}

enum RoleRow8Role: Close {}
extension RoleRow8Role {
    static var typeName: String { "`LineRole`" }
}
enum RoleRow8Is: Close {}
extension RoleRow8Is {
    static var typeName: String { "a thin border, or a denied/neutral dot" }
}

enum RolesTableHeaderRow: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TableCell { RoleHeader.self }; TableCell { WhatItIsHeader.self }
    }
}
enum RolesTableRule: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TableCell { RuleMark.self }; TableCell { RuleMark.self }
    }
}
enum RolesTableRows: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        TableRow { RolesTableHeaderRow.self }
        TableRow { RolesTableRule.self }
        TableRow { TableCell { RoleRow1Role.self }; TableCell { RoleRow1Is.self } }
        TableRow { TableCell { RoleRow2Role.self }; TableCell { RoleRow2Is.self } }
        TableRow { TableCell { RoleRow3Role.self }; TableCell { RoleRow3Is.self } }
        TableRow { TableCell { RoleRow4Role.self }; TableCell { RoleRow4Is.self } }
        TableRow { TableCell { RoleRow5Role.self }; TableCell { RoleRow5Is.self } }
        TableRow { TableCell { RoleRow6Role.self }; TableCell { RoleRow6Is.self } }
        TableRow { TableCell { RoleRow7Role.self }; TableCell { RoleRow7Is.self } }
        TableRow { TableCell { RoleRow8Role.self }; TableCell { RoleRow8Is.self } }
    }
}

// ── Gate tiers ──

enum GateTiersHeading: Close {}
extension GateTiersHeading {
    static var typeName: String { "Gate tiers" }
}

enum GateTiersBody: Close {}
extension GateTiersBody {
    static var typeName: String {
        "**Compile gate.** An illegal type does not build (`Legible`, `WithinBounds` — the strongest form). **Generation gate.** An illegal value stops `generate` with a named precondition (`BudgetedLabel`) — weaker, still before anything ships. **Host gate.** What only the browser decides (hover, theme) — declared, never trusted with correctness."
    }
}

enum LiveGatesLine: Close {}
extension LiveGatesLine {
    static var typeName: String {
        "Three of these are live in the site today. The five `Legible*` protocols above (`LegibleOnSurfaceCard`, `LegibleOnSurfaceTrack`, `LegibleOnAccentRole`, and two more) are compile gates on every (foreground, background) pairing — an unreadable pair does not build. `WithinCyclesHero` (Organization's review-cycle diagram) is the same tier applied to placement: a canvas's closed set of legal positions, so a position only one canvas vetted cannot satisfy a different canvas's layout by accident. `BudgetedLabel` is the generation gate — a stated character ceiling, checked once, at generate time, against the real text a label carries (checked directly: lowering a label's budget below its longest real name crashes `generate` with exactly this precondition, then raised back)."
    }
}

// ── The interactive layer ──

enum InteractiveLayerHeading: Close {}
extension InteractiveLayerHeading {
    static var typeName: String { "The interactive layer" }
}

enum LinkedLine: Close {}
extension LinkedLine {
    static var typeName: String {
        "`Linked` wraps a subtree in a real link: `Target` is a page path from the site's own closed set of addresses, never an arbitrary URL, named at the call site, not computed. It is always emitted — inert inside a plain `<img>` (DocC's own embed choice) — and becomes a real, clickable DOM anchor only once the host inlines the canvas (the inline-swap hook, `footer.html`), a decision the host makes about how to embed the medium, not a capability this file adds."
    }
}
enum PageSlugLine: Close {}
extension PageSlugLine {
    static var typeName: String {
        "`PageSlug<X>` reads a page type's own Swift name, lowercased — the same URL slug DocC's static-hosting build assigns it. A caller builds a real site path from a page type with this, never a string kept in sync by hand."
    }
}
enum HoverRevealLine: Close {}
extension HoverRevealLine {
    static var typeName: String {
        "`HoverReveal` pairs a `Trigger` and a `Panel`: hovering either reveals the panel, while the trigger's own click still navigates. The panel must survive the pointer's travel to it, so the reveal is keyed on either half's hover, the close is a delay rather than an instant cutoff, and `pointer-events` is never touched mid-transition (SurfaceLaw §S26 — found by checking directly, not assumed)."
    }
}
enum SelfShowingLine: Close {}
extension SelfShowingLine {
    static var typeName: String {
        "`SelfShowing` costs nothing beyond an empty conformance: a canvas that opts in can read its own already-compiled composition back out as text and print it as a small `{ }` chip on the page — nothing here is a second copy of what compiled, so nothing here can drift from it."
    }
}

// ── Example 1 — a drawn canvas: a plate and a label, the contract above made concrete. ──

public typealias VectorExampleSurface = Times<U8, Plus<U16, Plus<U8, Plus<U4, U2>>>>   // 240
public typealias VectorExampleHeightStructure = Times<U2, Plus<U32, U16>>               // 96
typealias VectorExampleColumnWide = Plus<U64, Plus<U32, Plus<U16, U8>>>   // half the surface: one tour station's column
typealias VectorExampleTriggerSlot = Plus<U32, U8>   // the reveal trigger's slot; its dot stands at the middle
typealias VectorExamplePanelInset = Plus<U32, Plus<U8, U4>>   // the revealed panel's text stands this far in
public typealias VectorExampleCanvasSize = CanvasSize<VectorExampleSurface, VectorExampleHeightStructure>

public enum VectorCanvasExampleAlt: Close {}
extension VectorCanvasExampleAlt {
    public static var typeName: String { "A plate reading Vector." }
}
enum VectorCanvasExampleAsset: Close {}
extension VectorCanvasExampleAsset {
    static var typeName: String { "vector-canvas-example" }
}

enum VectorCanvasExampleText: Close {}
extension VectorCanvasExampleText {
    static var typeName: String { "Vector" }
}

enum VectorCanvasExamplePlate: RoundedFullBleedRect {
    typealias W = Tally<VectorExampleSurface>
    typealias H = Tally<VectorExampleHeightStructure>
    typealias Radius = R16
    typealias Fill = SurfaceCard
}
enum VectorCanvasExampleLabelY: Close {}
extension VectorCanvasExampleLabelY {
    static var typeName: String { "56" }
}
enum VectorCanvasExampleLabelSpan: SpanLabel {
    typealias Y = VectorCanvasExampleLabelY
    typealias FillColor = TextPrimary
    typealias Size = TitleT
    typealias Weight = WeightRegular
    typealias Content = VectorCanvasExampleText
}
enum VectorCanvasExampleLabel: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<S24Breath>.self
        Flexible<VectorCanvasExampleLabelSpan>.self
    }
}
public enum VectorCanvasExampleContent: Group {
    @StructureBuilder
    public static var body: some Structure {
        VectorCanvasExamplePlate.self
        VectorCanvasExampleLabel.self
    }
}
public enum VectorCanvasExampleDiagram: Diagram {
    public typealias Size = VectorExampleCanvasSize
    public typealias AriaLabel = VectorCanvasExampleAlt
    public typealias Content = VectorCanvasExampleContent
}

enum DrawnCanvasHeading: Close {}
extension DrawnCanvasHeading {
    static var typeName: String { "A drawn canvas" }
}
enum DrawnCanvasCaption: Close {}
extension DrawnCanvasCaption {
    static var typeName: String {
        "A canvas, a plate, and a label — the three pieces the contract above names, composed the way any `Diagram` is."
    }
}
enum DrawnCanvasExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Picture { VectorCanvasExampleAlt.self; VectorCanvasExampleAsset.self }
    }
}
enum DrawnCanvasCode: Close {}
extension DrawnCanvasCode {
    static var typeName: String {
        """
        public enum VectorCanvasExampleContent: Group {
            public static var body: some Structure {
                VectorCanvasExamplePlate.self
                VectorCanvasExampleLabel.self
            }
        }
        public enum VectorCanvasExampleDiagram: Diagram {
            public typealias Size = VectorExampleCanvasSize
            public typealias AriaLabel = VectorCanvasExampleAlt
            public typealias Content = VectorCanvasExampleContent
        }
        """
    }
}

// ── Example 2 — hover reveals more: a Linked trigger, a Panel, paired by HoverReveal. ──

enum VectorExampleSitePath<X>: Close {}
extension VectorExampleSitePath {
    static var typeName: String { "/documentation/documentkit/" + PageSlug<X>.typeName }
}

public enum VectorHoverExampleAlt: Close {}
extension VectorHoverExampleAlt {
    public static var typeName: String { "A dot that reveals a panel on hover. Its click still navigates." }
}
enum VectorHoverExampleAsset: Close {}
extension VectorHoverExampleAsset {
    static var typeName: String { "vector-hover-example" }
}

enum VectorHoverDotCY: Close {}
extension VectorHoverDotCY {
    static var typeName: String { "20" }
}
enum VectorHoverDotSpan: SpanDot {
    typealias CY = VectorHoverDotCY
    typealias R = R10
    typealias Fill = ActionRole
}
enum VectorHoverExampleTrigger: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Fixed<VectorExampleTriggerSlot, SpanLink<VectorExampleSitePath<ExampleTarget>, VectorHoverDotSpan>>.self
        RestAir.self
    }
}

enum VectorHoverPanelPlate: RoundedFullBleedRect {
    typealias W = Tally<VectorExampleSurface>
    typealias H = Tally<VectorExampleHeightStructure>
    typealias Radius = R10
    typealias Fill = SurfaceTrack
}
enum VectorHoverPanelText: Close {}
extension VectorHoverPanelText {
    static var typeName: String { "Revealed on hover" }
}
enum VectorHoverPanelLabelY: Close {}
extension VectorHoverPanelLabelY {
    static var typeName: String { "54" }
}
enum VectorHoverPanelLabelSpan: SpanLabel {
    typealias Y = VectorHoverPanelLabelY
    typealias FillColor = TextPrimary
    typealias Size = TextL
    typealias Weight = WeightRegular
    typealias Content = VectorHoverPanelText
}
enum VectorHoverPanelLabel: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<VectorExamplePanelInset>.self
        Flexible<VectorHoverPanelLabelSpan>.self
    }
}
enum VectorHoverExamplePanel: Group {
    @StructureBuilder
    static var body: some Structure {
        VectorHoverPanelPlate.self
        VectorHoverPanelLabel.self
    }
}
enum VectorHoverExampleReveal: HoverReveal {
    typealias Trigger = VectorHoverExampleTrigger
    typealias Panel = VectorHoverExamplePanel
}
public enum VectorHoverExampleContent: Group {
    @StructureBuilder
    public static var body: some Structure {
        HoverRevealStyle.self
        VectorHoverExampleReveal.self
    }
}
public enum VectorHoverExampleDiagram: Diagram {
    public typealias Size = VectorExampleCanvasSize
    public typealias AriaLabel = VectorHoverExampleAlt
    public typealias Content = VectorHoverExampleContent
}

enum HoverExampleHeading: Close {}
extension HoverExampleHeading {
    static var typeName: String { "Hover reveals more" }
}
enum HoverExampleCaption: Close {}
extension HoverExampleCaption {
    static var typeName: String {
        "A trigger and a panel, paired by `HoverReveal` — hover the dot below to see the panel, and its click still navigates."
    }
}
enum HoverExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Picture { VectorHoverExampleAlt.self; VectorHoverExampleAsset.self }
    }
}
enum HoverExampleCode: Close {}
extension HoverExampleCode {
    static var typeName: String {
        """
        enum VectorHoverExampleReveal: HoverReveal {
            typealias Trigger = VectorHoverExampleTrigger
            typealias Panel = VectorHoverExamplePanel
        }
        """
    }
}

// ── Example 3 — the gate, both ways: one declaration, ONE line different, one compiles, one
//    does not. `GatedTextOnSurfaceCard` (Design.swift) requires `Fg: LegibleOnSurfaceCard` — a
//    compile gate, not a review note. The refusal below is the real compiler's own words,
//    quoted verbatim (checked directly), not a paraphrase of what it might say. ──

enum GateExampleHeading: Close {}
extension GateExampleHeading {
    static var typeName: String { "The gate, both ways" }
}
enum GateExampleCaption: Close {}
extension GateExampleCaption {
    static var typeName: String {
        "`GatedTextOnSurfaceCard` requires `Fg: LegibleOnSurfaceCard` (Design.swift) — a compile gate, not a review note. The same declaration, one legal foreground and one illegal one."
    }
}
enum GateCompilesLabel: Close {}
extension GateCompilesLabel {
    static var typeName: String { "This compiles:" }
}
enum GateLegalCode: Close {}
extension GateLegalCode {
    static var typeName: String {
        """
        enum LegalLabel: GatedTextOnSurfaceCard {
            typealias Fg = TextPrimary   // TextPrimary: LegibleOnSurfaceCard
            typealias X = N0
            typealias Y = N0
            typealias Anchor = AnchorStart
            typealias Size = TextS
            typealias Content = ProbeText
        }
        """
    }
}
enum GateRefusesLabel: Close {}
extension GateRefusesLabel {
    static var typeName: String { "This does not — the compiler's own words:" }
}
enum GateIllegalCode: Close {}
extension GateIllegalCode {
    static var typeName: String {
        """
        enum IllegalLabel: GatedTextOnSurfaceCard {
            typealias Fg = SurfaceTrack   // a background, not a legible foreground
            typealias X = N0
            typealias Y = N0
            typealias Anchor = AnchorStart
            typealias Size = TextS
            typealias Content = ProbeText
        }
        """
    }
}
enum GateErrorQuote: Close {}
extension GateErrorQuote {
    static var typeName: String {
        """
        error: type 'IllegalLabel' does not conform to protocol 'GatedTextOnSurfaceCard'
        note: possibly intended match 'IllegalLabel.Fg' (aka 'SurfaceTrack') does not
        conform to 'LegibleOnSurfaceCard'
        """
    }
}

// ── Example 4 — a canvas that shows its own code: `SelfShowing` (Vector.swift) costs nothing
//    beyond the marker. DocumentKit has no decompiler (Organization/VectorDemo's own SelfShowing
//    badge reads one, a driver-level, value-level concern this module cannot depend on) — so the
//    badge here links to a page carrying this SAME canvas's own composition, read off the SAME
//    atom the code block below shows: it cannot drift from what actually compiled, because
//    nothing here is a second copy of it. ──

enum SelfShowingExampleSource {}   // a bare name-token — PageSlug only reads String(describing:)

enum SelfShowingExampleSourceCode: Close {}
extension SelfShowingExampleSourceCode {
    static var typeName: String {
        """
        public enum VectorSelfShowingExampleDiagram: Diagram, SelfShowing {
            public typealias Size = VectorExampleCanvasSize
            public typealias AriaLabel = VectorSelfShowingExampleAlt
            public typealias Content = VectorSelfShowingExampleContent
        }
        """
    }
}
/// The source page's title IS the canvas's own drawn word: one atom, two readings.
typealias SelfShowingExampleSourceTitle = VectorSelfShowingExampleText
enum SelfShowingExampleSourceCaption: Close {}
extension SelfShowingExampleSourceCaption {
    static var typeName: String {
        "The composition the badge on the canvas points to — the same atom the gallery's code block reads, never a second copy."
    }
}
public enum SelfShowingExampleSourcePage: GallerySection {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { SelfShowingExampleSourceTitle.self }
        SelfShowingExampleSourceCaption.self
        Break.self
        CodeSample { SelfShowingExampleSourceCode.self }
    }
}

public enum VectorSelfShowingExampleAlt: Close {}
extension VectorSelfShowingExampleAlt {
    public static var typeName: String { "A plate reading Self-showing, with a chip that links to its own source." }
}
enum VectorSelfShowingExampleAsset: Close {}
extension VectorSelfShowingExampleAsset {
    static var typeName: String { "vector-selfshowing-example" }
}
enum VectorSelfShowingExampleText: Close {}
extension VectorSelfShowingExampleText {
    static var typeName: String { "Self-showing" }
}
enum VectorSelfShowingExamplePlate: RoundedFullBleedRect {
    typealias W = Tally<VectorExampleSurface>
    typealias H = Tally<VectorExampleHeightStructure>
    typealias Radius = R16
    typealias Fill = SurfaceCard
}
enum VectorSelfShowingExampleLabelY: Close {}
extension VectorSelfShowingExampleLabelY {
    static var typeName: String { "56" }
}
enum VectorSelfShowingExampleLabelSpan: SpanLabel {
    typealias Y = VectorSelfShowingExampleLabelY
    typealias FillColor = TextPrimary
    typealias Size = TitleT
    typealias Weight = WeightRegular
    typealias Content = VectorSelfShowingExampleText
}
enum VectorSelfShowingExampleLabel: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<S24Breath>.self
        Flexible<VectorSelfShowingExampleLabelSpan>.self
    }
}

enum SelfShowingBadgeChipText: Close {}
extension SelfShowingBadgeChipText {
    static var typeName: String { "{ }" }
}
enum SelfShowingBadgeChipHeight: Close {}
extension SelfShowingBadgeChipHeight {
    static var typeName: String { "20" }
}
enum SelfShowingBadgeChipTrack: SpanTrack {
    typealias H = SelfShowingBadgeChipHeight
    typealias Radius = R6
    typealias Fill = SurfaceTrack
}
enum SelfShowingBadgeChipTextDY: Close {}
extension SelfShowingBadgeChipTextDY {
    static var typeName: String { "14" }
}
enum SelfShowingBadgeChipLabel: SpanLabel {
    typealias Y = SelfShowingBadgeChipTextDY
    typealias FillColor = TextSecondary
    typealias Size = TextS
    typealias Weight = WeightRegular
    typealias Content = SelfShowingBadgeChipText
}
enum SelfShowingBadgeChipInterior: HFlow {
    typealias Given = BadgeChipWide
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<HairBreath>.self
        Flexible<SelfShowingBadgeChipLabel>.self
    }
}
enum SelfShowingBadgeChipRow: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        RestAir.self
        Fixed<
            BadgeChipWide,
            SpanLink<
                VectorExampleSitePath<SelfShowingExampleSource>,
                Layered<SelfShowingBadgeChipTrack, SpanHosted<SelfShowingBadgeChipInterior>>
            >
        >.self
        Air<HairBreath>.self
    }
}
enum SelfShowingBadgeChipY: Close {}
extension SelfShowingBadgeChipY {
    static var typeName: String { "68" }
}
enum SelfShowingBadgeDropped: Dropped {
    typealias Y = SelfShowingBadgeChipY
    typealias Content = SelfShowingBadgeChipRow
}
public enum VectorSelfShowingExampleContent: Group {
    @StructureBuilder
    public static var body: some Structure {
        VectorSelfShowingExamplePlate.self
        VectorSelfShowingExampleLabel.self
        SelfShowingBadgeDropped.self
    }
}
public enum VectorSelfShowingExampleDiagram: Diagram, SelfShowing {
    public typealias Size = VectorExampleCanvasSize
    public typealias AriaLabel = VectorSelfShowingExampleAlt
    public typealias Content = VectorSelfShowingExampleContent
}

enum SelfShowingExampleHeading: Close {}
extension SelfShowingExampleHeading {
    static var typeName: String { "A canvas that shows its own code" }
}
enum SelfShowingExampleCaption: Close {}
extension SelfShowingExampleCaption {
    static var typeName: String {
        "`SelfShowing` costs nothing beyond the marker — the badge in the corner links to a page carrying this canvas's composition, read off the same atom the code block below shows, so it cannot drift from what actually compiled."
    }
}
enum SelfShowingExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Picture { VectorSelfShowingExampleAlt.self; VectorSelfShowingExampleAsset.self }
    }
}

// ── Example 5 — a linked tour: two canvases, each `Linked` to the OTHER's own page (`Target`
//    is a page path from the site's own closed set, never an arbitrary URL). The gallery below
//    previews Station A; visiting either station's own page and clicking its dot is the real
//    tour — the click navigates to the OTHER station, whose own dot navigates back. ──

enum VectorTourStationA {}   // bare name-tokens — PageSlug only reads String(describing:)
enum VectorTourStationB {}

enum VectorTourDotCY: Close {}
extension VectorTourDotCY {
    static var typeName: String { "40" }
}
enum VectorTourDot: SpanDot {
    typealias CY = VectorTourDotCY
    typealias R = R20
    typealias Fill = ActionRole
}
enum VectorTourStationALinkToB: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Fixed<VectorExampleColumnWide, SpanLink<VectorExampleSitePath<VectorTourStationB>, VectorTourDot>>.self
        RestAir.self
    }
}
enum VectorTourLabelY: Close {}
extension VectorTourLabelY {
    static var typeName: String { "76" }
}
enum VectorTourLabelAText: Close {}
extension VectorTourLabelAText {
    static var typeName: String { "Station A" }
}
enum VectorTourLabelBText: Close {}
extension VectorTourLabelBText {
    static var typeName: String { "Station B" }
}
enum VectorTourLabelSpan<T: Structure>: SpanLabelMid {
    typealias Y = VectorTourLabelY
    typealias FillColor = TextPrimary
    typealias Size = TextS
    typealias Weight = WeightRegular
    typealias Content = T
}
enum VectorTourLabelA: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Fixed<VectorExampleColumnWide, VectorTourLabelSpan<VectorTourLabelAText>>.self
        RestAir.self
    }
}
enum VectorTourLabelB: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<VectorExampleColumnWide>.self
        Fixed<VectorExampleColumnWide, VectorTourLabelSpan<VectorTourLabelBText>>.self
        RestAir.self
    }
}

public enum VectorTourExampleAlt: Close {}
extension VectorTourExampleAlt {
    public static var typeName: String { "Station A, a dot linked to Station B's page." }
}
enum VectorTourExampleAsset: Close {}
extension VectorTourExampleAsset {
    static var typeName: String { "vector-tour-station-a" }
}
public enum VectorTourStationAContent: Group {
    @StructureBuilder
    public static var body: some Structure {
        VectorTourStationALinkToB.self
        VectorTourLabelA.self
    }
}
public enum VectorTourStationADiagram: Diagram {
    public typealias Size = VectorExampleCanvasSize
    public typealias AriaLabel = VectorTourExampleAlt
    public typealias Content = VectorTourStationAContent
}

enum VectorTourStationBLinkToA: HFlow {
    typealias Given = VectorExampleSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<VectorExampleColumnWide>.self
        Fixed<VectorExampleColumnWide, SpanLink<VectorExampleSitePath<VectorTourStationA>, VectorTourDot>>.self
        RestAir.self
    }
}
public enum VectorTourStationBAlt: Close {}
extension VectorTourStationBAlt {
    public static var typeName: String { "Station B, a dot linked back to Station A's page." }
}
public enum VectorTourStationBContent: Group {
    @StructureBuilder
    public static var body: some Structure {
        VectorTourStationBLinkToA.self
        VectorTourLabelB.self
    }
}
public enum VectorTourStationBDiagram: Diagram {
    public typealias Size = VectorExampleCanvasSize
    public typealias AriaLabel = VectorTourStationBAlt
    public typealias Content = VectorTourStationBContent
}

enum VectorTourHeading: Close {}
extension VectorTourHeading {
    static var typeName: String { "A linked tour" }
}
enum VectorTourCaption: Close {}
extension VectorTourCaption {
    static var typeName: String {
        "Two canvases, each `Linked` to the other's page. Visit Station A below, click its dot, land on Station B — click its dot to land back on Station A. Inert here, a plain `<img>`. Real once the host inlines it."
    }
}
enum VectorTourCode: Close {}
extension VectorTourCode {
    static var typeName: String {
        """
        enum VectorTourStationALinkToB: HFlow {
            static var body: some Structure & Divides {
                Fixed<
                    VectorExampleColumnWide,
                    SpanLink<VectorExampleSitePath<VectorTourStationB>, VectorTourDot>
                >.self
                RestAir.self
            }
        }
        // Station B mirrors it, linked back to Station A.
        """
    }
}
enum VectorTourExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Picture { VectorTourExampleAlt.self; VectorTourExampleAsset.self }
    }
}

enum VectorTourStationACaption: Close {}
extension VectorTourStationACaption {
    static var typeName: String { "Click the dot to cross to Station B." }
}
enum VectorTourStationBCaption: Close {}
extension VectorTourStationBCaption {
    static var typeName: String { "Click the dot to cross back to Station A." }
}

/// These are the two station pages themselves. Each embedding the OTHER canvas is missing on
/// purpose: a station shows only its dot, the tour IS the click from one page to the other, not
/// both drawn at once (that would be the gallery preview again, not a tour).
public enum VectorTourStationAPage: GallerySection {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { VectorTourLabelAText.self }
        VectorTourStationACaption.self
        Break.self
        Picture { VectorTourExampleAlt.self; VectorTourExampleAsset.self }
    }
}
public enum VectorTourStationBPage: GallerySection {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { VectorTourLabelBText.self }
        VectorTourStationBCaption.self
        Break.self
        Picture { VectorTourStationBAlt.self; VectorTourStationBAsset.self }
    }
}
enum VectorTourStationBAsset: Close {}
extension VectorTourStationBAsset {
    static var typeName: String { "vector-tour-station-b" }
}

// ── Example 6 — RolesPlate, both themes: the eight roles table above, drawn instead of merely
//    tabulated. Mechanism (A)'s second consumer (DESIGN11) — a `Palette`, instantiated twice,
//    the same edge substitution `LightCardPalette`/`DarkCardPalette` already stands on, written
//    to `roles-plate.svg`/`roles-plate~dark.svg`, DocC's own native asset-swap for a grid tile.
//    Associated-type names carry a `Color` suffix so a palette's OWN requirement never collides
//    with the global role atom of the (almost) same name it is bound to. ──

public protocol RolesPalette {
    associatedtype CardColor: Structure
    associatedtype TrackColor: Structure
    associatedtype PrimaryColor: Structure
    associatedtype SecondaryColor: Structure
    associatedtype AccentColor: Structure
    associatedtype ActionColor: Structure
    associatedtype LineColor: Structure
    associatedtype OnAccentColor: Structure
}
public enum LightRolesPalette: RolesPalette {
    public typealias CardColor = SurfaceCard
    public typealias TrackColor = SurfaceTrack
    public typealias PrimaryColor = TextPrimary
    public typealias SecondaryColor = TextSecondary
    public typealias AccentColor = AccentRole
    public typealias ActionColor = ActionRole
    public typealias LineColor = LineRole
    public typealias OnAccentColor = OnAccent
}
public enum DarkRolesPalette: RolesPalette {
    public typealias CardColor = SurfaceCardDark
    public typealias TrackColor = SurfaceTrackDark
    public typealias PrimaryColor = TextPrimaryDark
    public typealias SecondaryColor = TextSecondaryDark
    public typealias AccentColor = AccentRoleDark
    public typealias ActionColor = ActionRoleDark
    public typealias LineColor = LineRoleDark
    public typealias OnAccentColor = OnAccentDark
}

enum RolesPlateWidth: Close {}
extension RolesPlateWidth {
    static var typeName: String { "240" }
}
enum RolesPlateHeight: Close {}
extension RolesPlateHeight {
    static var typeName: String { "148" }
}
public typealias RolesPlateHeightStructure = Times<U4, Plus<U32, Plus<U4, U1>>>   // 148
public typealias RolesPlateSize = CanvasSize<RolesPlateSurface, RolesPlateHeightStructure>
enum RolesPlateRow1Y: Close {}
extension RolesPlateRow1Y {
static var typeName: String { "16" } }
enum RolesPlateRow2Y: Close {}
extension RolesPlateRow2Y {
static var typeName: String { "76" } }
enum RolesPlateLabelRow1Y: Close {}
extension RolesPlateLabelRow1Y {
static var typeName: String { "56" } }
enum RolesPlateLabelRow2Y: Close {}
extension RolesPlateLabelRow2Y {
static var typeName: String { "116" } }
enum RolesPlateSwatchH: Close {}
extension RolesPlateSwatchH {
static var typeName: String { "24" } }
enum RolesPlateCardLabelText: Close {}
extension RolesPlateCardLabelText {
static var typeName: String { "Card" } }
enum RolesPlateTrackLabelText: Close {}
extension RolesPlateTrackLabelText {
static var typeName: String { "Track" } }
enum RolesPlatePrimaryLabelText: Close {}
extension RolesPlatePrimaryLabelText {
static var typeName: String { "Primary" } }
enum RolesPlateSecondaryLabelText: Close {}
extension RolesPlateSecondaryLabelText {
static var typeName: String { "Secondary" } }
enum RolesPlateAccentLabelText: Close {}
extension RolesPlateAccentLabelText {
static var typeName: String { "Accent" } }
enum RolesPlateActionLabelText: Close {}
extension RolesPlateActionLabelText {
static var typeName: String { "Action" } }
enum RolesPlateLineLabelText: Close {}
extension RolesPlateLineLabelText {
static var typeName: String { "Line" } }
enum RolesPlateOnAccentLabelText: Close {}
extension RolesPlateOnAccentLabelText {
static var typeName: String { "On accent" } }

enum RolesPlateBackingPlate<
    Palette: RolesPalette
>: RoundedFullBleedRect {
    typealias W = RolesPlateWidth
    typealias H = RolesPlateHeight
    typealias Radius = R16
    typealias Fill = Palette.CardColor
}

/// One cell speaks for all eight: the swatch is a slice-filling outlined track lowered to
/// its row, the label sits under it on the same slice's start. The grid is two weighed
/// rows over the plate, margin 8, swatch 50, breath 8, and no cell holds a position.
enum RolesSwatchFace<
    Fill: Structure,
    Line: Structure
>: SpanTrackOutlined {
    typealias H = RolesPlateSwatchH
    typealias Radius = R4
    typealias Fill = Fill
    typealias Stroke = Line
}
enum RolesCellLabel<
    Ink: Structure,
    T: Structure,
    LabelY: Structure
>: SpanLabel {
    typealias Y = LabelY
    typealias FillColor = Ink
    typealias Size = TextXXS
    typealias Weight = WeightRegular
    typealias Content = T
}
typealias RolesCell<
    Fill: Structure,
    Line: Structure,
    Ink: Structure,
    T: Structure,
    RowY: Structure,
    LabelY: Structure
> = Layered<
    SpanLowered<RowY, RolesSwatchFace<Fill, Line>>,
    RolesCellLabel<Ink, T, LabelY>
>
public typealias RolesPlateSurface = Times<
    U4,
    Plus<
        U32,
        Plus<
            U16,
            Plus<
                U8,
                U4
            >
        >
    >
>   // four sixties: the plate's whole width
enum RolesPlateRowOne<Palette: RolesPalette>: HFlow {
    typealias Given = RolesPlateSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.CardColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateCardLabelText, RolesPlateRow1Y, RolesPlateLabelRow1Y>>.self
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.TrackColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateTrackLabelText, RolesPlateRow1Y, RolesPlateLabelRow1Y>>.self
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.PrimaryColor, Palette.LineColor, Palette.PrimaryColor, RolesPlatePrimaryLabelText, RolesPlateRow1Y, RolesPlateLabelRow1Y>>.self
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.SecondaryColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateSecondaryLabelText, RolesPlateRow1Y, RolesPlateLabelRow1Y>>.self
        RestAir.self
    }
}
enum RolesPlateRowTwo<Palette: RolesPalette>: HFlow {
    typealias Given = RolesPlateSurface
    @StructureBuilder
    static var body: some Structure & Divides {
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.AccentColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateAccentLabelText, RolesPlateRow2Y, RolesPlateLabelRow2Y>>.self
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.ActionColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateActionLabelText, RolesPlateRow2Y, RolesPlateLabelRow2Y>>.self
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.LineColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateLineLabelText, RolesPlateRow2Y, RolesPlateLabelRow2Y>>.self
        Air<U8>.self
        Fixed<Plus<U32, Plus<U16, U2>>, RolesCell<Palette.OnAccentColor, Palette.LineColor, Palette.PrimaryColor, RolesPlateOnAccentLabelText, RolesPlateRow2Y, RolesPlateLabelRow2Y>>.self
        RestAir.self
    }
}
public enum RolesPlateContent<Palette: RolesPalette>: Group {
    @StructureBuilder
    public static var body: some Structure {
        RolesPlateBackingPlate<Palette>.self
        RolesPlateRowOne<Palette>.self
        RolesPlateRowTwo<Palette>.self
    }
}
public enum RolesPlateAlt: Close {}
extension RolesPlateAlt {
    public static var typeName: String { "The eight roles, each as its own colour swatch." }
}
public enum RolesPlate<Palette: RolesPalette>: Diagram {
    public typealias Size = RolesPlateSize
    public typealias AriaLabel = RolesPlateAlt
    public typealias Content = RolesPlateContent<Palette>
}

enum RolesPlateHeading: Close {}
extension RolesPlateHeading {
    static var typeName: String { "RolesPlate, both themes" }
}
enum RolesPlateCaption: Close {}
extension RolesPlateCaption {
    static var typeName: String {
        "The table above, drawn: the same `Palette`, instantiated once per theme, the same edge substitution `LightCardPalette`/`DarkCardPalette` already stands on. DocC swaps the file, never the type."
    }
}
enum RolesPlateCode: Close {}
extension RolesPlateCode {
    static var typeName: String {
        """
        writeSVG(RolesPlate<LightRolesPalette>.typeName, "roles-plate")
        writeSVG(RolesPlate<DarkRolesPalette>.typeName, "roles-plate~dark")
        """
    }
}
enum RolesPlateAsset: Close {}
extension RolesPlateAsset {
    static var typeName: String { "roles-plate" }
}
enum RolesPlateExample: GallerySection {
    @StructureBuilder
    static var body: some Structure {
        Picture { RolesPlateAlt.self; RolesPlateAsset.self }
    }
}

/// This is the whole module landing: title, prose sections, the mechanism table, then the
/// gallery itself, folded in as this page's last section. `Symbol { ModuleTitleTarget.self }`,
/// not `Symbol { Landing.self }`: a type's title referencing itself would read
/// `Landing.typeName`, which reads `Body.typeName`, which starts with the title again, infinite
/// recursion at the first render (checked directly, exactly the circularity `AliceUnlocked`
/// avoids by pointing at `SecretPage<...>` instead of itself).
public enum Landing: GallerySection {
    @StructureBuilder
    public static var body: some Structure {
        PageTitle { Symbol { ModuleTitleTarget.self } }
        LandingIntro.self
        Break.self

        DoubleHash.self; BuildAPageHeading.self; Break.self
        BuildAPageIntro.self
        Break.self
        BuildAPageStep1.self
        Newline.self
        BuildAPageStep2.self
        Newline.self
        BuildAPageStep3.self
        Newline.self
        BuildAPageStep4.self
        Newline.self
        BuildAPageStep5.self
        Break.self

        DoubleHash.self; TwoKindsHeading.self; Break.self
        TwoKindsIntro.self
        Break.self
        Table { CombinatorTableRows.self }
        Break.self

        DoubleHash.self; RenderingPathHeading.self; Break.self
        RenderingPathIntro.self
        Break.self
        Warned { RenderingPathWarning.self }

        DoubleHash.self; GallerySectionHeading.self; Break.self
        GallerySectionIntro.self
        Break.self

        TripleHash.self; SymbolHeading.self; Break.self
        SymbolCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { SymbolCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        SymbolExample.self
        Break.self

        TripleHash.self; PageHeading.self; Break.self
        PageCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { PageCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        PageExample.self
        Break.self

        TripleHash.self; LinkHeading.self; Break.self
        LinkCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { LinkCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        LinkExample.self
        Break.self

        TripleHash.self; PictureHeading.self; Break.self
        PictureCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { PictureCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        PictureExample.self
        Break.self

        TripleHash.self; FramedHeading.self; Break.self
        FramedCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { FramedCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        FramedExample.self
        Break.self

        TripleHash.self; SpacerHeading.self; Break.self
        SpacerCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { SpacerCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        SpacerExample.self
        Break.self

        TripleHash.self; GapHeading.self; Break.self
        GapCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { GapCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        GapExample.self
        Break.self

        TripleHash.self; SpacerBetweenHeading.self; Break.self
        SpacerBetweenCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { SpacerBetweenCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        SpacerBetweenExample.self
        Break.self

        TripleHash.self; TableHeading.self; Break.self
        TableCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { TableCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        TableExample.self
        Break.self

        TripleHash.self; ListHeading.self; Break.self
        ListCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { ListCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        ListExample.self
        Break.self

        TripleHash.self; CalloutsHeading.self; Break.self
        CalloutsCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { CalloutsCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        NoteExample.self
        ImportantExample.self
        WarningExample.self
        TipExample.self
        Break.self

        TripleHash.self; TabsHeading.self; Break.self
        TabsCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { TabsCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        TabsExample.self
        Break.self

        TripleHash.self; ColumnsHeading.self; Break.self
        ColumnsCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { ColumnsCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        ColumnsExample.self
        Break.self

        TripleHash.self; SizedPanelHeading.self; Break.self
        SizedPanelCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { SizedPanelCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        SizedPanelExample.self
        Break.self

        TripleHash.self; TallyHeading.self; Break.self
        TallyCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { TallyCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        TallyExample.self
        Break.self

        DoubleHash.self; VectorSectionHeading.self; Break.self
        VectorSectionIntro.self
        Break.self

        TripleHash.self; CanvasContractHeading.self; Break.self
        CanvasContractGuaranteed.self
        Break.self
        CanvasContractNotGuaranteed.self
        Break.self

        TripleHash.self; RolesHeading.self; Break.self
        RolesIntro.self
        Break.self
        Table { RolesTableRows.self }
        Break.self

        TripleHash.self; GateTiersHeading.self; Break.self
        GateTiersBody.self
        Break.self
        LiveGatesLine.self
        Break.self

        TripleHash.self; InteractiveLayerHeading.self; Break.self
        LinkedLine.self
        Break.self
        PageSlugLine.self
        Break.self
        HoverRevealLine.self
        Break.self
        SelfShowingLine.self
        Break.self

        TripleHash.self; DrawnCanvasHeading.self; Break.self
        DrawnCanvasCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { DrawnCanvasCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        DrawnCanvasExample.self
        Break.self

        TripleHash.self; HoverExampleHeading.self; Break.self
        HoverExampleCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { HoverExampleCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        HoverExample.self
        Break.self

        TripleHash.self; GateExampleHeading.self; Break.self
        GateExampleCaption.self
        Break.self
        GateCompilesLabel.self
        Break.self
        CodeSample { GateLegalCode.self }
        Break.self
        GateRefusesLabel.self
        Break.self
        CodeSample { GateIllegalCode.self }
        Break.self
        TripleBacktick.self
        GateErrorQuote.self
        Newline.self
        TripleBacktick.self
        Break.self

        TripleHash.self; SelfShowingExampleHeading.self; Break.self
        SelfShowingExampleCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { SelfShowingExampleSourceCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        SelfShowingExample.self
        Break.self

        TripleHash.self; VectorTourHeading.self; Break.self
        VectorTourCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { VectorTourCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        VectorTourExample.self
        Break.self

        TripleHash.self; RolesPlateHeading.self; Break.self
        RolesPlateCaption.self
        Break.self
        UsedLikeThisLabel.self
        Break.self
        CodeSample { RolesPlateCode.self }
        Break.self
        ComesOutLikeThisLabel.self
        Break.self
        RolesPlateExample.self
    }
}
