import VerificationIsIdentification

// GENERATED by `swift package generate org`: the twelve (department, rank)
// cohorts a role-walk lands on. Each is a plain composed body; `count` is the
// cohort's size, counted by the type checker as this compiles.

// Everyone standing in the (Finance, IndividualContributor) pair.
public enum FinanceIndividualContributors: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0000.self; Emp0015.self; Emp0030.self; Emp0042.self; Emp0057.self; Emp0072.self;
        Emp0084.self; Emp0099.self; Emp0114.self; Emp0126.self; Emp0141.self; Emp0156.self;
        Emp0168.self; Emp0183.self; Emp0198.self; Carol.self;
    }
}

// Everyone standing in the (Finance, Lead) pair.
public enum FinanceLeads: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0001.self; Emp0016.self; Emp0028.self; Emp0043.self; Emp0058.self; Emp0070.self;
        Emp0085.self; Emp0100.self; Emp0112.self; Emp0127.self; Emp0142.self; Emp0154.self;
        Emp0169.self; Emp0184.self; Emp0196.self;
    }
}

// Everyone standing in the (Finance, Manager) pair.
public enum FinanceManagers: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0002.self; Emp0014.self; Emp0029.self; Emp0044.self; Emp0056.self; Emp0071.self;
        Emp0086.self; Emp0098.self; Emp0113.self; Emp0128.self; Emp0140.self; Emp0155.self;
        Emp0170.self; Emp0182.self; Emp0197.self; Alice.self;
    }
}

// Everyone standing in the (Engineering, IndividualContributor) pair.
public enum EngineeringIndividualContributors: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0003.self; Emp0006.self; Emp0018.self; Emp0021.self; Emp0033.self; Emp0045.self;
        Emp0048.self; Emp0060.self; Emp0063.self; Emp0075.self; Emp0087.self; Emp0090.self;
        Emp0102.self; Emp0105.self; Emp0117.self; Emp0129.self; Emp0132.self; Emp0144.self;
        Emp0147.self; Emp0159.self; Emp0171.self; Emp0174.self; Emp0186.self; Emp0189.self;
    }
}

// Everyone standing in the (Engineering, Lead) pair.
public enum EngineeringLeads: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0004.self; Emp0007.self; Emp0019.self; Emp0031.self; Emp0034.self; Emp0046.self;
        Emp0049.self; Emp0061.self; Emp0073.self; Emp0076.self; Emp0088.self; Emp0091.self;
        Emp0103.self; Emp0115.self; Emp0118.self; Emp0130.self; Emp0133.self; Emp0145.self;
        Emp0157.self; Emp0160.self; Emp0172.self; Emp0175.self; Emp0187.self; Emp0199.self;
        Bob.self;
    }
}

// Everyone standing in the (Engineering, Manager) pair.
public enum EngineeringManagers: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0005.self; Emp0017.self; Emp0020.self; Emp0032.self; Emp0035.self; Emp0047.self;
        Emp0059.self; Emp0062.self; Emp0074.self; Emp0077.self; Emp0089.self; Emp0101.self;
        Emp0104.self; Emp0116.self; Emp0119.self; Emp0131.self; Emp0143.self; Emp0146.self;
        Emp0158.self; Emp0161.self; Emp0173.self; Emp0185.self; Emp0188.self; Dave.self;
    }
}

// Everyone standing in the (Sales, IndividualContributor) pair.
public enum SalesIndividualContributors: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0009.self; Emp0024.self; Emp0036.self; Emp0039.self; Emp0051.self; Emp0066.self;
        Emp0078.self; Emp0081.self; Emp0093.self; Emp0108.self; Emp0120.self; Emp0123.self;
        Emp0135.self; Emp0150.self; Emp0162.self; Emp0165.self; Emp0177.self; Emp0192.self;
    }
}

// Everyone standing in the (Sales, Lead) pair.
public enum SalesLeads: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0010.self; Emp0022.self; Emp0025.self; Emp0037.self; Emp0052.self; Emp0064.self;
        Emp0067.self; Emp0079.self; Emp0094.self; Emp0106.self; Emp0109.self; Emp0121.self;
        Emp0136.self; Emp0148.self; Emp0151.self; Emp0163.self; Emp0178.self; Emp0190.self;
        Emp0193.self;
    }
}

// Everyone standing in the (Sales, Manager) pair.
public enum SalesManagers: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0008.self; Emp0011.self; Emp0023.self; Emp0038.self; Emp0050.self; Emp0053.self;
        Emp0065.self; Emp0080.self; Emp0092.self; Emp0095.self; Emp0107.self; Emp0122.self;
        Emp0134.self; Emp0137.self; Emp0149.self; Emp0164.self; Emp0176.self; Emp0179.self;
        Emp0191.self;
    }
}

// Everyone standing in the (People, IndividualContributor) pair.
public enum PeopleIndividualContributors: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0012.self; Emp0027.self; Emp0054.self; Emp0069.self; Emp0096.self; Emp0111.self;
        Emp0138.self; Emp0153.self; Emp0180.self; Emp0195.self;
    }
}

// Everyone standing in the (People, Lead) pair.
public enum PeopleLeads: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0013.self; Emp0040.self; Emp0055.self; Emp0082.self; Emp0097.self; Emp0124.self;
        Emp0139.self; Emp0166.self; Emp0181.self;
    }
}

// Everyone standing in the (People, Manager) pair.
public enum PeopleManagers: Team {
    @StructureBuilder
    public static var body: some Structure {
        Emp0026.self; Emp0041.self; Emp0068.self; Emp0083.self; Emp0110.self; Emp0125.self;
        Emp0152.self; Emp0167.self; Emp0194.self;
    }
}

// ── The role walk's fork faces: compositions of the real department and rank
//    types, read by RollCall on the walk pages. ──
public enum MoneyOrBuildSide: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Finance.self; Engineering.self
    }
}
public enum SalesOrPeopleSide: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Sales.self; People.self
    }
}
public enum LeadOrManagerPair: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Lead.self; Manager.self
    }
}
/// The role space's root: the walk that forms a (department, rank) pair starts here.
public enum RoleWalk: Halves {
    @StructureBuilder
    public static var body: some Structure {
        MoneyOrBuildSide.self; SalesOrPeopleSide.self
    }
}
public enum FinanceRanks: Halves {
    @StructureBuilder
    public static var body: some Structure {
        IndividualContributor.self; FinanceLeadOrManager.self
    }
}
public enum FinanceLeadOrManager: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Lead.self; Manager.self
    }
}
public enum EngineeringRanks: Halves {
    @StructureBuilder
    public static var body: some Structure {
        IndividualContributor.self; EngineeringLeadOrManager.self
    }
}
public enum EngineeringLeadOrManager: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Lead.self; Manager.self
    }
}
public enum SalesRanks: Halves {
    @StructureBuilder
    public static var body: some Structure {
        IndividualContributor.self; SalesLeadOrManager.self
    }
}
public enum SalesLeadOrManager: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Lead.self; Manager.self
    }
}
public enum PeopleRanks: Halves {
    @StructureBuilder
    public static var body: some Structure {
        IndividualContributor.self; PeopleLeadOrManager.self
    }
}
public enum PeopleLeadOrManager: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Lead.self; Manager.self
    }
}
