import VerificationIsIdentification
import DocumentKit

// GENERATED by `swift package generate org`: the roster as a walkable halving, in
// phone-book order (family, given, handle). Each node is a plain composed body —
// the fork is `Pair` itself (DocumentKit Walk) — and the walk pages read these types, so a
// door cannot say what its half does not hold. Span indices are positions on the
// alphabetical shelf; the midpoint split keeps every walk within ⌈log₂ 200⌉ choices.


public enum RosterSpan0001To0002: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0068.self
        Emp0064.self
    }
}

public enum RosterSpan0000To0002: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0061.self
        RosterSpan0001To0002.self
    }
}

public enum RosterSpan0004To0005: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0065.self
        Emp0062.self
    }
}

public enum RosterSpan0003To0005: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0060.self
        RosterSpan0004To0005.self
    }
}

public enum RosterSpan0000To0005: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0000To0002.self
        RosterSpan0003To0005.self
    }
}

public enum RosterSpan0007To0008: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0067.self
        Emp0066.self
    }
}

public enum RosterSpan0006To0008: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0071.self
        RosterSpan0007To0008.self
    }
}

public enum RosterSpan0010To0011: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0070.self
        Emp0069.self
    }
}

public enum RosterSpan0009To0011: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0063.self
        RosterSpan0010To0011.self
    }
}

public enum RosterSpan0006To0011: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0006To0008.self
        RosterSpan0009To0011.self
    }
}

public enum RosterSpan0000To0011: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0000To0005.self
        RosterSpan0006To0011.self
    }
}

public enum RosterSpan0013To0014: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0145.self
        Emp0008.self
    }
}

public enum RosterSpan0012To0014: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0001.self
        RosterSpan0013To0014.self
    }
}

public enum RosterSpan0016To0017: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0004.self
        Emp0148.self
    }
}

public enum RosterSpan0015To0017: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0152.self
        RosterSpan0016To0017.self
    }
}

public enum RosterSpan0012To0017: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0012To0014.self
        RosterSpan0015To0017.self
    }
}

public enum RosterSpan0019To0020: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0144.self
        Emp0005.self
    }
}

public enum RosterSpan0018To0020: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0000.self
        RosterSpan0019To0020.self
    }
}

public enum RosterSpan0021To0022: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0149.self
        Emp0002.self
    }
}

public enum RosterSpan0023To0024: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0146.self
        Emp0011.self
    }
}

public enum RosterSpan0021To0024: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0021To0022.self
        RosterSpan0023To0024.self
    }
}

public enum RosterSpan0018To0024: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0018To0020.self
        RosterSpan0021To0024.self
    }
}

public enum RosterSpan0012To0024: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0012To0017.self
        RosterSpan0018To0024.self
    }
}

public enum RosterSpan0000To0024: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0000To0011.self
        RosterSpan0012To0024.self
    }
}

public enum RosterSpan0026To0027: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0007.self
        Emp0151.self
    }
}

public enum RosterSpan0025To0027: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0155.self
        RosterSpan0026To0027.self
    }
}

public enum RosterSpan0029To0030: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0150.self
        Emp0003.self
    }
}

public enum RosterSpan0028To0030: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0006.self
        RosterSpan0029To0030.self
    }
}

public enum RosterSpan0025To0030: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0025To0027.self
        RosterSpan0028To0030.self
    }
}

public enum RosterSpan0032To0033: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0010.self
        Emp0154.self
    }
}

public enum RosterSpan0031To0033: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0147.self
        RosterSpan0032To0033.self
    }
}

public enum RosterSpan0034To0035: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0009.self
        Emp0153.self
    }
}

public enum RosterSpan0036To0037: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0085.self
        Emp0092.self
    }
}

public enum RosterSpan0034To0037: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0034To0035.self
        RosterSpan0036To0037.self
    }
}

public enum RosterSpan0031To0037: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0031To0033.self
        RosterSpan0034To0037.self
    }
}

public enum RosterSpan0025To0037: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0025To0030.self
        RosterSpan0031To0037.self
    }
}

public enum RosterSpan0039To0040: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0084.self
        Emp0089.self
    }
}

public enum RosterSpan0038To0040: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0088.self
        RosterSpan0039To0040.self
    }
}

public enum RosterSpan0042To0043: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0095.self
        Emp0091.self
    }
}

public enum RosterSpan0041To0043: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0086.self
        RosterSpan0042To0043.self
    }
}

public enum RosterSpan0038To0043: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0038To0040.self
        RosterSpan0041To0043.self
    }
}

public enum RosterSpan0045To0046: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0087.self
        Emp0094.self
    }
}

public enum RosterSpan0044To0046: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0090.self
        RosterSpan0045To0046.self
    }
}

public enum RosterSpan0047To0048: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0093.self
        Emp0037.self
    }
}

public enum RosterSpan0049To0050: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0181.self
        Emp0044.self
    }
}

public enum RosterSpan0047To0050: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0047To0048.self
        RosterSpan0049To0050.self
    }
}

public enum RosterSpan0044To0050: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0044To0046.self
        RosterSpan0047To0050.self
    }
}

public enum RosterSpan0038To0050: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0038To0043.self
        RosterSpan0044To0050.self
    }
}

public enum RosterSpan0025To0050: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0025To0037.self
        RosterSpan0038To0050.self
    }
}

public enum RosterSpan0000To0050: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0000To0024.self
        RosterSpan0025To0050.self
    }
}

public enum RosterSpan0052To0053: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0040.self
        Emp0184.self
    }
}

public enum RosterSpan0051To0053: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0188.self
        RosterSpan0052To0053.self
    }
}

public enum RosterSpan0055To0056: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0180.self
        Emp0041.self
    }
}

public enum RosterSpan0054To0056: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0036.self
        RosterSpan0055To0056.self
    }
}

public enum RosterSpan0051To0056: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0051To0053.self
        RosterSpan0054To0056.self
    }
}

public enum RosterSpan0058To0059: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0038.self
        Emp0182.self
    }
}

public enum RosterSpan0057To0059: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0185.self
        RosterSpan0058To0059.self
    }
}

public enum RosterSpan0061To0062: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0191.self
        Emp0043.self
    }
}

public enum RosterSpan0060To0062: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0047.self
        RosterSpan0061To0062.self
    }
}

public enum RosterSpan0057To0062: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0057To0059.self
        RosterSpan0060To0062.self
    }
}

public enum RosterSpan0051To0062: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0051To0056.self
        RosterSpan0057To0062.self
    }
}

public enum RosterSpan0064To0065: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0042.self
        Emp0186.self
    }
}

public enum RosterSpan0063To0065: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0187.self
        RosterSpan0064To0065.self
    }
}

public enum RosterSpan0067To0068: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0183.self
        Emp0046.self
    }
}

public enum RosterSpan0066To0068: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0039.self
        RosterSpan0067To0068.self
    }
}

public enum RosterSpan0063To0068: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0063To0065.self
        RosterSpan0066To0068.self
    }
}

public enum RosterSpan0070To0071: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0045.self
        Emp0189.self
    }
}

public enum RosterSpan0069To0071: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0190.self
        RosterSpan0070To0071.self
    }
}

public enum RosterSpan0072To0073: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Carol.self
        Emp0049.self
    }
}

public enum RosterSpan0074To0075: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0193.self
        Emp0056.self
    }
}

public enum RosterSpan0072To0075: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0072To0073.self
        RosterSpan0074To0075.self
    }
}

public enum RosterSpan0069To0075: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0069To0071.self
        RosterSpan0072To0075.self
    }
}

public enum RosterSpan0063To0075: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0063To0068.self
        RosterSpan0069To0075.self
    }
}

public enum RosterSpan0051To0075: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0051To0062.self
        RosterSpan0063To0075.self
    }
}

public enum RosterSpan0077To0078: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0196.self
        Emp0048.self
    }
}

public enum RosterSpan0076To0078: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0052.self
        RosterSpan0077To0078.self
    }
}

public enum RosterSpan0080To0081: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0053.self
        Emp0197.self
    }
}

public enum RosterSpan0079To0081: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0192.self
        RosterSpan0080To0081.self
    }
}

public enum RosterSpan0076To0081: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0076To0078.self
        RosterSpan0079To0081.self
    }
}

public enum RosterSpan0083To0084: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0194.self
        Emp0059.self
    }
}

public enum RosterSpan0082To0084: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0050.self
        RosterSpan0083To0084.self
    }
}

public enum RosterSpan0085To0086: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0055.self
        Emp0199.self
    }
}

public enum RosterSpan0087To0088: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0054.self
        Emp0198.self
    }
}

public enum RosterSpan0085To0088: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0085To0086.self
        RosterSpan0087To0088.self
    }
}

public enum RosterSpan0082To0088: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0082To0084.self
        RosterSpan0085To0088.self
    }
}

public enum RosterSpan0076To0088: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0076To0081.self
        RosterSpan0082To0088.self
    }
}

public enum RosterSpan0090To0091: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0195.self
        Emp0058.self
    }
}

public enum RosterSpan0089To0091: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0051.self
        RosterSpan0090To0091.self
    }
}

public enum RosterSpan0093To0094: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0133.self
        Emp0140.self
    }
}

public enum RosterSpan0092To0094: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0057.self
        RosterSpan0093To0094.self
    }
}

public enum RosterSpan0089To0094: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0089To0091.self
        RosterSpan0092To0094.self
    }
}

public enum RosterSpan0096To0097: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0132.self
        Emp0137.self
    }
}

public enum RosterSpan0095To0097: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0136.self
        RosterSpan0096To0097.self
    }
}

public enum RosterSpan0098To0099: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0134.self
        Emp0143.self
    }
}

public enum RosterSpan0100To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0139.self
        Emp0138.self
    }
}

public enum RosterSpan0098To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0098To0099.self
        RosterSpan0100To0101.self
    }
}

public enum RosterSpan0095To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0095To0097.self
        RosterSpan0098To0101.self
    }
}

public enum RosterSpan0089To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0089To0094.self
        RosterSpan0095To0101.self
    }
}

public enum RosterSpan0076To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0076To0088.self
        RosterSpan0089To0101.self
    }
}

public enum RosterSpan0051To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0051To0075.self
        RosterSpan0076To0101.self
    }
}

public enum RosterSpan0000To0101: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0000To0050.self
        RosterSpan0051To0101.self
    }
}

public enum RosterSpan0103To0104: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0142.self
        Emp0141.self
    }
}

public enum RosterSpan0102To0104: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0135.self
        RosterSpan0103To0104.self
    }
}

public enum RosterSpan0106To0107: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0157.self
        Emp0020.self
    }
}

public enum RosterSpan0105To0107: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0013.self
        RosterSpan0106To0107.self
    }
}

public enum RosterSpan0102To0107: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0102To0104.self
        RosterSpan0105To0107.self
    }
}

public enum RosterSpan0109To0110: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0016.self
        Emp0160.self
    }
}

public enum RosterSpan0108To0110: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0164.self
        RosterSpan0109To0110.self
    }
}

public enum RosterSpan0112To0113: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0156.self
        Emp0017.self
    }
}

public enum RosterSpan0111To0113: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0012.self
        RosterSpan0112To0113.self
    }
}

public enum RosterSpan0108To0113: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0108To0110.self
        RosterSpan0111To0113.self
    }
}

public enum RosterSpan0102To0113: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0102To0107.self
        RosterSpan0108To0113.self
    }
}

public enum RosterSpan0115To0116: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0014.self
        Emp0158.self
    }
}

public enum RosterSpan0114To0116: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0161.self
        RosterSpan0115To0116.self
    }
}

public enum RosterSpan0118To0119: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0167.self
        Emp0019.self
    }
}

public enum RosterSpan0117To0119: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0023.self
        RosterSpan0118To0119.self
    }
}

public enum RosterSpan0114To0119: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0114To0116.self
        RosterSpan0117To0119.self
    }
}

public enum RosterSpan0121To0122: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0018.self
        Emp0162.self
    }
}

public enum RosterSpan0120To0122: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0163.self
        RosterSpan0121To0122.self
    }
}

public enum RosterSpan0123To0124: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0015.self
        Emp0159.self
    }
}
