import VerificationIsIdentification
import DocumentKit

// GENERATED by `swift package generate org`: the roster as a walkable halving, in
// phone-book order (family, given, handle). Each node is a plain composed body —
// the fork is `Pair` itself (DocumentKit Walk) — and the walk pages read these types, so a
// door cannot say what its half does not hold. Span indices are positions on the
// alphabetical shelf; the midpoint split keeps every walk within ⌈log₂ 200⌉ choices.


public enum RosterSpan0125To0126: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0022.self
        Emp0166.self
    }
}

public enum RosterSpan0123To0126: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0123To0124.self
        RosterSpan0125To0126.self
    }
}

public enum RosterSpan0120To0126: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0120To0122.self
        RosterSpan0123To0126.self
    }
}

public enum RosterSpan0114To0126: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0114To0119.self
        RosterSpan0120To0126.self
    }
}

public enum RosterSpan0102To0126: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0102To0113.self
        RosterSpan0114To0126.self
    }
}

public enum RosterSpan0128To0129: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0165.self
        Alice.self
    }
}

public enum RosterSpan0127To0129: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0021.self
        RosterSpan0128To0129.self
    }
}

public enum RosterSpan0131To0132: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0169.self
        Emp0032.self
    }
}

public enum RosterSpan0130To0132: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0025.self
        RosterSpan0131To0132.self
    }
}

public enum RosterSpan0127To0132: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0127To0129.self
        RosterSpan0130To0132.self
    }
}

public enum RosterSpan0134To0135: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0028.self
        Emp0172.self
    }
}

public enum RosterSpan0133To0135: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0176.self
        RosterSpan0134To0135.self
    }
}

public enum RosterSpan0136To0137: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0024.self
        Emp0168.self
    }
}

public enum RosterSpan0138To0139: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0029.self
        Emp0173.self
    }
}

public enum RosterSpan0136To0139: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0136To0137.self
        RosterSpan0138To0139.self
    }
}

public enum RosterSpan0133To0139: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0133To0135.self
        RosterSpan0136To0139.self
    }
}

public enum RosterSpan0127To0139: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0127To0132.self
        RosterSpan0133To0139.self
    }
}

public enum RosterSpan0141To0142: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0170.self
        Emp0035.self
    }
}

public enum RosterSpan0140To0142: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0026.self
        RosterSpan0141To0142.self
    }
}

public enum RosterSpan0144To0145: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0031.self
        Emp0175.self
    }
}

public enum RosterSpan0143To0145: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0179.self
        RosterSpan0144To0145.self
    }
}

public enum RosterSpan0140To0145: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0140To0142.self
        RosterSpan0143To0145.self
    }
}

public enum RosterSpan0147To0148: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0174.self
        Emp0027.self
    }
}

public enum RosterSpan0146To0148: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0030.self
        RosterSpan0147To0148.self
    }
}

public enum RosterSpan0149To0150: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0171.self
        Emp0034.self
    }
}

public enum RosterSpan0151To0152: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0178.self
        Emp0033.self
    }
}

public enum RosterSpan0149To0152: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0149To0150.self
        RosterSpan0151To0152.self
    }
}

public enum RosterSpan0146To0152: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0146To0148.self
        RosterSpan0149To0152.self
    }
}

public enum RosterSpan0140To0152: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0140To0145.self
        RosterSpan0146To0152.self
    }
}

public enum RosterSpan0127To0152: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0127To0139.self
        RosterSpan0140To0152.self
    }
}

public enum RosterSpan0102To0152: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0102To0126.self
        RosterSpan0127To0152.self
    }
}

public enum RosterSpan0154To0155: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0121.self
        Emp0128.self
    }
}

public enum RosterSpan0153To0155: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0177.self
        RosterSpan0154To0155.self
    }
}

public enum RosterSpan0157To0158: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0120.self
        Emp0125.self
    }
}

public enum RosterSpan0156To0158: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0124.self
        RosterSpan0157To0158.self
    }
}

public enum RosterSpan0153To0158: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0153To0155.self
        RosterSpan0156To0158.self
    }
}

public enum RosterSpan0160To0161: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0131.self
        Emp0127.self
    }
}

public enum RosterSpan0159To0161: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0122.self
        RosterSpan0160To0161.self
    }
}

public enum RosterSpan0163To0164: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0123.self
        Emp0130.self
    }
}

public enum RosterSpan0162To0164: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0126.self
        RosterSpan0163To0164.self
    }
}

public enum RosterSpan0159To0164: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0159To0161.self
        RosterSpan0162To0164.self
    }
}

public enum RosterSpan0153To0164: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0153To0158.self
        RosterSpan0159To0164.self
    }
}

public enum RosterSpan0166To0167: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0097.self
        Emp0104.self
    }
}

public enum RosterSpan0165To0167: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0129.self
        RosterSpan0166To0167.self
    }
}

public enum RosterSpan0169To0170: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0096.self
        Emp0101.self
    }
}

public enum RosterSpan0168To0170: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0100.self
        RosterSpan0169To0170.self
    }
}

public enum RosterSpan0165To0170: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0165To0167.self
        RosterSpan0168To0170.self
    }
}

public enum RosterSpan0172To0173: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0107.self
        Emp0103.self
    }
}

public enum RosterSpan0171To0173: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0098.self
        RosterSpan0172To0173.self
    }
}

public enum RosterSpan0174To0175: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0102.self
        Emp0099.self
    }
}

public enum RosterSpan0176To0177: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0106.self
        Emp0105.self
    }
}

public enum RosterSpan0174To0177: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0174To0175.self
        RosterSpan0176To0177.self
    }
}

public enum RosterSpan0171To0177: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0171To0173.self
        RosterSpan0174To0177.self
    }
}

public enum RosterSpan0165To0177: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0165To0170.self
        RosterSpan0171To0177.self
    }
}

public enum RosterSpan0153To0177: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0153To0164.self
        RosterSpan0165To0177.self
    }
}

public enum RosterSpan0179To0180: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0080.self
        Emp0076.self
    }
}

public enum RosterSpan0178To0180: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0073.self
        RosterSpan0179To0180.self
    }
}

public enum RosterSpan0182To0183: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0077.self
        Emp0074.self
    }
}

public enum RosterSpan0181To0183: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0072.self
        RosterSpan0182To0183.self
    }
}

public enum RosterSpan0178To0183: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0178To0180.self
        RosterSpan0181To0183.self
    }
}

public enum RosterSpan0185To0186: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0079.self
        Emp0078.self
    }
}

public enum RosterSpan0184To0186: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0083.self
        RosterSpan0185To0186.self
    }
}

public enum RosterSpan0187To0188: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0075.self
        Emp0082.self
    }
}

public enum RosterSpan0189To0190: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0081.self
        Dave.self
    }
}

public enum RosterSpan0187To0190: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0187To0188.self
        RosterSpan0189To0190.self
    }
}

public enum RosterSpan0184To0190: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0184To0186.self
        RosterSpan0187To0190.self
    }
}

public enum RosterSpan0178To0190: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0178To0183.self
        RosterSpan0184To0190.self
    }
}

public enum RosterSpan0192To0193: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0109.self
        Emp0116.self
    }
}

public enum RosterSpan0191To0193: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Bob.self
        RosterSpan0192To0193.self
    }
}

public enum RosterSpan0195To0196: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0108.self
        Emp0113.self
    }
}

public enum RosterSpan0194To0196: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0112.self
        RosterSpan0195To0196.self
    }
}

public enum RosterSpan0191To0196: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0191To0193.self
        RosterSpan0194To0196.self
    }
}

public enum RosterSpan0198To0199: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0119.self
        Emp0115.self
    }
}

public enum RosterSpan0197To0199: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0110.self
        RosterSpan0198To0199.self
    }
}

public enum RosterSpan0200To0201: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0114.self
        Emp0111.self
    }
}

public enum RosterSpan0202To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        Emp0118.self
        Emp0117.self
    }
}

public enum RosterSpan0200To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0200To0201.self
        RosterSpan0202To0203.self
    }
}

public enum RosterSpan0197To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0197To0199.self
        RosterSpan0200To0203.self
    }
}

public enum RosterSpan0191To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0191To0196.self
        RosterSpan0197To0203.self
    }
}

public enum RosterSpan0178To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0178To0190.self
        RosterSpan0191To0203.self
    }
}

public enum RosterSpan0153To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0153To0177.self
        RosterSpan0178To0203.self
    }
}

public enum RosterSpan0102To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0102To0152.self
        RosterSpan0153To0203.self
    }
}

public enum RosterSpan0000To0203: Halves {
    @StructureBuilder
    public static var body: some Structure {
        RosterSpan0000To0101.self
        RosterSpan0102To0203.self
    }
}


/// The phone book's root shelf under one stable name: the hand-written pages, the
/// diagram, and the audit reach the walk through this alias, so the universe can
/// change size without touching them.
public typealias RosterWalkRoot = RosterSpan0000To0203
