import VerificationIsIdentification
import DocumentKit

// GENERATED by `swift package generate org` — the render side of the company of 200.
// `RosterTableRow(_:)` (View/Employees.swift) is generic: one declaration, reused per
// person, the same relationship `Emp####` has to `Employee, Person`.
public enum FullRosterRows: Fragment {
    @StructureBuilder
    public static var body: some Structure {
        TableRow { RosterHeader.self }; TableRow { RosterRule.self }; RosterTableRow { Emp0000.self };
        RosterTableRow { Emp0001.self }; RosterTableRow { Emp0002.self }; RosterTableRow { Emp0003.self };
        RosterTableRow { Emp0004.self }; RosterTableRow { Emp0005.self }; RosterTableRow { Emp0006.self };
        RosterTableRow { Emp0007.self }; RosterTableRow { Emp0008.self }; RosterTableRow { Emp0009.self };
        RosterTableRow { Emp0010.self }; RosterTableRow { Emp0011.self }; RosterTableRow { Emp0012.self };
        RosterTableRow { Emp0013.self }; RosterTableRow { Emp0014.self }; RosterTableRow { Emp0015.self };
        RosterTableRow { Emp0016.self }; RosterTableRow { Emp0017.self }; RosterTableRow { Emp0018.self };
        RosterTableRow { Emp0019.self }; RosterTableRow { Emp0020.self }; RosterTableRow { Emp0021.self };
        RosterTableRow { Emp0022.self }; RosterTableRow { Emp0023.self }; RosterTableRow { Emp0024.self };
        RosterTableRow { Emp0025.self }; RosterTableRow { Emp0026.self }; RosterTableRow { Emp0027.self };
        RosterTableRow { Emp0028.self }; RosterTableRow { Emp0029.self }; RosterTableRow { Emp0030.self };
        RosterTableRow { Emp0031.self }; RosterTableRow { Emp0032.self }; RosterTableRow { Emp0033.self };
        RosterTableRow { Emp0034.self }; RosterTableRow { Emp0035.self }; RosterTableRow { Emp0036.self };
        RosterTableRow { Emp0037.self }; RosterTableRow { Emp0038.self }; RosterTableRow { Emp0039.self };
        RosterTableRow { Emp0040.self }; RosterTableRow { Emp0041.self }; RosterTableRow { Emp0042.self };
        RosterTableRow { Emp0043.self }; RosterTableRow { Emp0044.self }; RosterTableRow { Emp0045.self };
        RosterTableRow { Emp0046.self }; RosterTableRow { Emp0047.self }; RosterTableRow { Emp0048.self };
        RosterTableRow { Emp0049.self }; RosterTableRow { Emp0050.self }; RosterTableRow { Emp0051.self };
        RosterTableRow { Emp0052.self }; RosterTableRow { Emp0053.self }; RosterTableRow { Emp0054.self };
        RosterTableRow { Emp0055.self }; RosterTableRow { Emp0056.self }; RosterTableRow { Emp0057.self };
        RosterTableRow { Emp0058.self }; RosterTableRow { Emp0059.self }; RosterTableRow { Emp0060.self };
        RosterTableRow { Emp0061.self }; RosterTableRow { Emp0062.self }; RosterTableRow { Emp0063.self };
        RosterTableRow { Emp0064.self }; RosterTableRow { Emp0065.self }; RosterTableRow { Emp0066.self };
        RosterTableRow { Emp0067.self }; RosterTableRow { Emp0068.self }; RosterTableRow { Emp0069.self };
        RosterTableRow { Emp0070.self }; RosterTableRow { Emp0071.self }; RosterTableRow { Emp0072.self };
        RosterTableRow { Emp0073.self }; RosterTableRow { Emp0074.self }; RosterTableRow { Emp0075.self };
        RosterTableRow { Emp0076.self }; RosterTableRow { Emp0077.self }; RosterTableRow { Emp0078.self };
        RosterTableRow { Emp0079.self }; RosterTableRow { Emp0080.self }; RosterTableRow { Emp0081.self };
        RosterTableRow { Emp0082.self }; RosterTableRow { Emp0083.self }; RosterTableRow { Emp0084.self };
        RosterTableRow { Emp0085.self }; RosterTableRow { Emp0086.self }; RosterTableRow { Emp0087.self };
        RosterTableRow { Emp0088.self }; RosterTableRow { Emp0089.self }; RosterTableRow { Emp0090.self };
        RosterTableRow { Emp0091.self }; RosterTableRow { Emp0092.self }; RosterTableRow { Emp0093.self };
        RosterTableRow { Emp0094.self }; RosterTableRow { Emp0095.self }; RosterTableRow { Emp0096.self };
        RosterTableRow { Emp0097.self }; RosterTableRow { Emp0098.self }; RosterTableRow { Emp0099.self };
        RosterTableRow { Emp0100.self }; RosterTableRow { Emp0101.self }; RosterTableRow { Emp0102.self };
        RosterTableRow { Emp0103.self }; RosterTableRow { Emp0104.self }; RosterTableRow { Emp0105.self };
        RosterTableRow { Emp0106.self }; RosterTableRow { Emp0107.self }; RosterTableRow { Emp0108.self };
        RosterTableRow { Emp0109.self }; RosterTableRow { Emp0110.self }; RosterTableRow { Emp0111.self };
        RosterTableRow { Emp0112.self }; RosterTableRow { Emp0113.self }; RosterTableRow { Emp0114.self };
        RosterTableRow { Emp0115.self }; RosterTableRow { Emp0116.self }; RosterTableRow { Emp0117.self };
        RosterTableRow { Emp0118.self }; RosterTableRow { Emp0119.self }; RosterTableRow { Emp0120.self };
        RosterTableRow { Emp0121.self }; RosterTableRow { Emp0122.self }; RosterTableRow { Emp0123.self };
        RosterTableRow { Emp0124.self }; RosterTableRow { Emp0125.self }; RosterTableRow { Emp0126.self };
        RosterTableRow { Emp0127.self }; RosterTableRow { Emp0128.self }; RosterTableRow { Emp0129.self };
        RosterTableRow { Emp0130.self }; RosterTableRow { Emp0131.self }; RosterTableRow { Emp0132.self };
        RosterTableRow { Emp0133.self }; RosterTableRow { Emp0134.self }; RosterTableRow { Emp0135.self };
        RosterTableRow { Emp0136.self }; RosterTableRow { Emp0137.self }; RosterTableRow { Emp0138.self };
        RosterTableRow { Emp0139.self }; RosterTableRow { Emp0140.self }; RosterTableRow { Emp0141.self };
        RosterTableRow { Emp0142.self }; RosterTableRow { Emp0143.self }; RosterTableRow { Emp0144.self };
        RosterTableRow { Emp0145.self }; RosterTableRow { Emp0146.self }; RosterTableRow { Emp0147.self };
        RosterTableRow { Emp0148.self }; RosterTableRow { Emp0149.self }; RosterTableRow { Emp0150.self };
        RosterTableRow { Emp0151.self }; RosterTableRow { Emp0152.self }; RosterTableRow { Emp0153.self };
        RosterTableRow { Emp0154.self }; RosterTableRow { Emp0155.self }; RosterTableRow { Emp0156.self };
        RosterTableRow { Emp0157.self }; RosterTableRow { Emp0158.self }; RosterTableRow { Emp0159.self };
        RosterTableRow { Emp0160.self }; RosterTableRow { Emp0161.self }; RosterTableRow { Emp0162.self };
        RosterTableRow { Emp0163.self }; RosterTableRow { Emp0164.self }; RosterTableRow { Emp0165.self };
        RosterTableRow { Emp0166.self }; RosterTableRow { Emp0167.self }; RosterTableRow { Emp0168.self };
        RosterTableRow { Emp0169.self }; RosterTableRow { Emp0170.self }; RosterTableRow { Emp0171.self };
        RosterTableRow { Emp0172.self }; RosterTableRow { Emp0173.self }; RosterTableRow { Emp0174.self };
        RosterTableRow { Emp0175.self }; RosterTableRow { Emp0176.self }; RosterTableRow { Emp0177.self };
        RosterTableRow { Emp0178.self }; RosterTableRow { Emp0179.self }; RosterTableRow { Emp0180.self };
        RosterTableRow { Emp0181.self }; RosterTableRow { Emp0182.self }; RosterTableRow { Emp0183.self };
        RosterTableRow { Emp0184.self }; RosterTableRow { Emp0185.self }; RosterTableRow { Emp0186.self };
        RosterTableRow { Emp0187.self }; RosterTableRow { Emp0188.self }; RosterTableRow { Emp0189.self };
        RosterTableRow { Emp0190.self }; RosterTableRow { Emp0191.self }; RosterTableRow { Emp0192.self };
        RosterTableRow { Emp0193.self }; RosterTableRow { Emp0194.self }; RosterTableRow { Emp0195.self };
        RosterTableRow { Emp0196.self }; RosterTableRow { Emp0197.self }; RosterTableRow { Emp0198.self };
        RosterTableRow { Emp0199.self };
    }
}

enum GeneratedRosterTopics: Fragment {
    @StructureBuilder
    static var body: some Structure {
        ListItem { Symbol { Emp0000.self } }
        ListItem { Symbol { Emp0001.self } }
        ListItem { Symbol { Emp0002.self } }
        ListItem { Symbol { Emp0003.self } }
        ListItem { Symbol { Emp0004.self } }
        ListItem { Symbol { Emp0005.self } }
        ListItem { Symbol { Emp0006.self } }
        ListItem { Symbol { Emp0007.self } }
        ListItem { Symbol { Emp0008.self } }
        ListItem { Symbol { Emp0009.self } }
        ListItem { Symbol { Emp0010.self } }
        ListItem { Symbol { Emp0011.self } }
        ListItem { Symbol { Emp0012.self } }
        ListItem { Symbol { Emp0013.self } }
        ListItem { Symbol { Emp0014.self } }
        ListItem { Symbol { Emp0015.self } }
        ListItem { Symbol { Emp0016.self } }
        ListItem { Symbol { Emp0017.self } }
        ListItem { Symbol { Emp0018.self } }
        ListItem { Symbol { Emp0019.self } }
        ListItem { Symbol { Emp0020.self } }
        ListItem { Symbol { Emp0021.self } }
        ListItem { Symbol { Emp0022.self } }
        ListItem { Symbol { Emp0023.self } }
        ListItem { Symbol { Emp0024.self } }
        ListItem { Symbol { Emp0025.self } }
        ListItem { Symbol { Emp0026.self } }
        ListItem { Symbol { Emp0027.self } }
        ListItem { Symbol { Emp0028.self } }
        ListItem { Symbol { Emp0029.self } }
        ListItem { Symbol { Emp0030.self } }
        ListItem { Symbol { Emp0031.self } }
        ListItem { Symbol { Emp0032.self } }
        ListItem { Symbol { Emp0033.self } }
        ListItem { Symbol { Emp0034.self } }
        ListItem { Symbol { Emp0035.self } }
        ListItem { Symbol { Emp0036.self } }
        ListItem { Symbol { Emp0037.self } }
        ListItem { Symbol { Emp0038.self } }
        ListItem { Symbol { Emp0039.self } }
        ListItem { Symbol { Emp0040.self } }
        ListItem { Symbol { Emp0041.self } }
        ListItem { Symbol { Emp0042.self } }
        ListItem { Symbol { Emp0043.self } }
        ListItem { Symbol { Emp0044.self } }
        ListItem { Symbol { Emp0045.self } }
        ListItem { Symbol { Emp0046.self } }
        ListItem { Symbol { Emp0047.self } }
        ListItem { Symbol { Emp0048.self } }
        ListItem { Symbol { Emp0049.self } }
        ListItem { Symbol { Emp0050.self } }
        ListItem { Symbol { Emp0051.self } }
        ListItem { Symbol { Emp0052.self } }
        ListItem { Symbol { Emp0053.self } }
        ListItem { Symbol { Emp0054.self } }
        ListItem { Symbol { Emp0055.self } }
        ListItem { Symbol { Emp0056.self } }
        ListItem { Symbol { Emp0057.self } }
        ListItem { Symbol { Emp0058.self } }
        ListItem { Symbol { Emp0059.self } }
        ListItem { Symbol { Emp0060.self } }
        ListItem { Symbol { Emp0061.self } }
        ListItem { Symbol { Emp0062.self } }
        ListItem { Symbol { Emp0063.self } }
        ListItem { Symbol { Emp0064.self } }
        ListItem { Symbol { Emp0065.self } }
        ListItem { Symbol { Emp0066.self } }
        ListItem { Symbol { Emp0067.self } }
        ListItem { Symbol { Emp0068.self } }
        ListItem { Symbol { Emp0069.self } }
        ListItem { Symbol { Emp0070.self } }
        ListItem { Symbol { Emp0071.self } }
        ListItem { Symbol { Emp0072.self } }
        ListItem { Symbol { Emp0073.self } }
        ListItem { Symbol { Emp0074.self } }
        ListItem { Symbol { Emp0075.self } }
        ListItem { Symbol { Emp0076.self } }
        ListItem { Symbol { Emp0077.self } }
        ListItem { Symbol { Emp0078.self } }
        ListItem { Symbol { Emp0079.self } }
        ListItem { Symbol { Emp0080.self } }
        ListItem { Symbol { Emp0081.self } }
        ListItem { Symbol { Emp0082.self } }
        ListItem { Symbol { Emp0083.self } }
        ListItem { Symbol { Emp0084.self } }
        ListItem { Symbol { Emp0085.self } }
        ListItem { Symbol { Emp0086.self } }
        ListItem { Symbol { Emp0087.self } }
        ListItem { Symbol { Emp0088.self } }
        ListItem { Symbol { Emp0089.self } }
        ListItem { Symbol { Emp0090.self } }
        ListItem { Symbol { Emp0091.self } }
        ListItem { Symbol { Emp0092.self } }
        ListItem { Symbol { Emp0093.self } }
        ListItem { Symbol { Emp0094.self } }
        ListItem { Symbol { Emp0095.self } }
        ListItem { Symbol { Emp0096.self } }
        ListItem { Symbol { Emp0097.self } }
        ListItem { Symbol { Emp0098.self } }
        ListItem { Symbol { Emp0099.self } }
        ListItem { Symbol { Emp0100.self } }
        ListItem { Symbol { Emp0101.self } }
        ListItem { Symbol { Emp0102.self } }
        ListItem { Symbol { Emp0103.self } }
        ListItem { Symbol { Emp0104.self } }
        ListItem { Symbol { Emp0105.self } }
        ListItem { Symbol { Emp0106.self } }
        ListItem { Symbol { Emp0107.self } }
        ListItem { Symbol { Emp0108.self } }
        ListItem { Symbol { Emp0109.self } }
        ListItem { Symbol { Emp0110.self } }
        ListItem { Symbol { Emp0111.self } }
        ListItem { Symbol { Emp0112.self } }
        ListItem { Symbol { Emp0113.self } }
        ListItem { Symbol { Emp0114.self } }
        ListItem { Symbol { Emp0115.self } }
        ListItem { Symbol { Emp0116.self } }
        ListItem { Symbol { Emp0117.self } }
        ListItem { Symbol { Emp0118.self } }
        ListItem { Symbol { Emp0119.self } }
        ListItem { Symbol { Emp0120.self } }
        ListItem { Symbol { Emp0121.self } }
        ListItem { Symbol { Emp0122.self } }
        ListItem { Symbol { Emp0123.self } }
        ListItem { Symbol { Emp0124.self } }
        ListItem { Symbol { Emp0125.self } }
        ListItem { Symbol { Emp0126.self } }
        ListItem { Symbol { Emp0127.self } }
        ListItem { Symbol { Emp0128.self } }
        ListItem { Symbol { Emp0129.self } }
        ListItem { Symbol { Emp0130.self } }
        ListItem { Symbol { Emp0131.self } }
        ListItem { Symbol { Emp0132.self } }
        ListItem { Symbol { Emp0133.self } }
        ListItem { Symbol { Emp0134.self } }
        ListItem { Symbol { Emp0135.self } }
        ListItem { Symbol { Emp0136.self } }
        ListItem { Symbol { Emp0137.self } }
        ListItem { Symbol { Emp0138.self } }
        ListItem { Symbol { Emp0139.self } }
        ListItem { Symbol { Emp0140.self } }
        ListItem { Symbol { Emp0141.self } }
        ListItem { Symbol { Emp0142.self } }
        ListItem { Symbol { Emp0143.self } }
        ListItem { Symbol { Emp0144.self } }
        ListItem { Symbol { Emp0145.self } }
        ListItem { Symbol { Emp0146.self } }
        ListItem { Symbol { Emp0147.self } }
        ListItem { Symbol { Emp0148.self } }
        ListItem { Symbol { Emp0149.self } }
        ListItem { Symbol { Emp0150.self } }
        ListItem { Symbol { Emp0151.self } }
        ListItem { Symbol { Emp0152.self } }
        ListItem { Symbol { Emp0153.self } }
        ListItem { Symbol { Emp0154.self } }
        ListItem { Symbol { Emp0155.self } }
        ListItem { Symbol { Emp0156.self } }
        ListItem { Symbol { Emp0157.self } }
        ListItem { Symbol { Emp0158.self } }
        ListItem { Symbol { Emp0159.self } }
        ListItem { Symbol { Emp0160.self } }
        ListItem { Symbol { Emp0161.self } }
        ListItem { Symbol { Emp0162.self } }
        ListItem { Symbol { Emp0163.self } }
        ListItem { Symbol { Emp0164.self } }
        ListItem { Symbol { Emp0165.self } }
        ListItem { Symbol { Emp0166.self } }
        ListItem { Symbol { Emp0167.self } }
        ListItem { Symbol { Emp0168.self } }
        ListItem { Symbol { Emp0169.self } }
        ListItem { Symbol { Emp0170.self } }
        ListItem { Symbol { Emp0171.self } }
        ListItem { Symbol { Emp0172.self } }
        ListItem { Symbol { Emp0173.self } }
        ListItem { Symbol { Emp0174.self } }
        ListItem { Symbol { Emp0175.self } }
        ListItem { Symbol { Emp0176.self } }
        ListItem { Symbol { Emp0177.self } }
        ListItem { Symbol { Emp0178.self } }
        ListItem { Symbol { Emp0179.self } }
        ListItem { Symbol { Emp0180.self } }
        ListItem { Symbol { Emp0181.self } }
        ListItem { Symbol { Emp0182.self } }
        ListItem { Symbol { Emp0183.self } }
        ListItem { Symbol { Emp0184.self } }
        ListItem { Symbol { Emp0185.self } }
        ListItem { Symbol { Emp0186.self } }
        ListItem { Symbol { Emp0187.self } }
        ListItem { Symbol { Emp0188.self } }
        ListItem { Symbol { Emp0189.self } }
        ListItem { Symbol { Emp0190.self } }
        ListItem { Symbol { Emp0191.self } }
        ListItem { Symbol { Emp0192.self } }
        ListItem { Symbol { Emp0193.self } }
        ListItem { Symbol { Emp0194.self } }
        ListItem { Symbol { Emp0195.self } }
        ListItem { Symbol { Emp0196.self } }
        ListItem { Symbol { Emp0197.self } }
        ListItem { Symbol { Emp0198.self } }
        ListItem { Symbol { Emp0199.self } }
    }
}
